### ISSUE TITLE
GitHub complaining about file larger than 50 Mbytes

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1146]
Syncing my local git repo with the post-1105-merge master branch at GitHub produces this:
```
Fast-forward
 taxcalc/StageIFactors.csv             |     20 +-
 taxcalc/WEIGHTS.csv                   | 219816 ++++++++++++++++++++++++++++++-
 taxcalc/comparison/reform_results.txt |     98 +-
 taxcalc/growth.json                   |     26 +-
 taxcalc/growth.py                     |      6 +-
 taxcalc/policy.py                     |     16 +-
 taxcalc/tests/pufcsv_agg_expect.txt   |     36 +-
 taxcalc/tests/pufcsv_mtr_expect.txt   |     36 +-
 taxcalc/tests/test_growth.py          |      2 +-
 9 files changed, 219944 insertions(+), 112 deletions(-)
Counting objects: 41, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (41/41), done.
Writing objects: 100% (41/41), 16.58 MiB | 2.77 MiB/s, done.
Total 41 (delta 29), reused 0 (delta 0)
remote: Resolving deltas: 100% (29/29), completed with 13 local objects.
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File taxcalc/WEIGHTS.csv is 50.08 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
To https://github.com/martinholmer/tax-calculator.git
   1e72951..1ba5442  master -> master
```
This looks like a performance warning/suggestion, but I have so little experience with Git and GitHub that I thought I would check.

@MattHJensen @talumbau @andersonfrailey @Amy-Xu

**Comment by zrisher** [comment]
@martinholmer I just noticed this when pulling the latest commit as well. The issue is that git has to maintain revision information in your local `tax-calculator/.git` folder. When you're storing large files in the repo directly that folder can grow quite large and git operations can slow down. 

I haven't ever used [Git LFS](https://git-lfs.github.com/), but it sounds like a good solution to that general problem, and definitely something we should consider for the `taxpuf` repo.

In this particular case, I wonder if it makes sense for the weights file to be part of the `tax-calculator` repo. Isn't it only useful in combination with `puf.csv`? If that's the case, perhaps it belongs in `taxpuf`. On my computer, the `tax-calculator` repo folder is 529.5 MB, of which 418.6 MB is `.git` and 48.6 MB is `puf.csv`. That means `WEIGHTS.csv` takes up 80% of the ~ 62.3 MB of tracked files.

**Comment by martinholmer** [comment]
@zrisher said about the very large new `WEIGHTS.csv` file in issue #1146:
> ... I wonder if it makes sense for the weights file to be part of the tax-calculator repo. Isn't it only useful in combination with puf.csv?  If that's the case, perhaps it belongs in [the] taxpuf [repo].  On my computer, the tax-calculator repo folder is 529.5 MB, of which 418.6 MB is .git and 48.6 MB is puf.csv. That means WEIGHTS.csv takes up 80% of the ~ 62.3 MB of tracked files.

@MattHJensen, @Amy-Xu, @andersonfrailey, what do you think about Zach's idea of moving the `WEIGHTS.csv` file from the tax-calculator repo to the taxpuf repo?  Isn't his impression (that `WEIGHTS.csv` is used only in conjunction with the `puf.csv` file) correct?

**Comment by martinholmer** [comment]
@martinholmer said:
>  what do you think about Zach's idea of moving the `WEIGHTS.csv` file from the tax-calculator repo to the taxpuf repo? Isn't his impression (that `WEIGHTS.csv` is used only in conjunction with the `puf.csv` file) correct?

If Zach's impression is correct, then doesn't the logic of moving the file from the tax-calculator repo to the taxpuf repo also apply to the `StageIFactors.csv` file?  In other words, the content of the `StageIFactors.csv` file is appropriate for use only with the `puf.csv` file, right?

Also, shouldn't these two files also be renamed?  Otherwise, there could be a name collision when the new CPS-based `cps.csv` file is introduced with its own weights file and factors file.  Isn't that the plan for the new `cps.csv` file?  When moved to the taxpuf repo, perhaps these two files could be renamed something like `puf-weights.csv` and `puf-factors.csv`.  And then, when the new CPS-based `cps.csv` file is included in the tax-calculator repo (because there are not privacy concerns about the CPS data), it would be accompanied by files named something like `cps-weights.csv` and `cps-factors.csv`.

@MattHJensen @Amy-Xu @andersonfrailey @zrisher

**Comment by MattHJensen** [comment]
> If Zach's impression is correct, then doesn't the logic of moving the file from the tax-calculator repo to the taxpuf repo also apply to the StageIFactors.csv file? In other words, the content of the StageIFactors.csv file is appropriate for use only with the puf.csv file, right?

> Also, shouldn't these two files also be renamed? Otherwise, there could be a name collision when the new CPS-based cps.csv file is introduced with its own weights file and factors file. Isn't that the plan for the new cps.csv file? When moved to the taxpuf repo, perhaps these two files could be renamed something like puf-weights.csv and puf-factors.csv. And then, when the new CPS-based cps.csv file is included in the tax-calculator repo (because there are not privacy concerns about the CPS data), it would be accompanied by files named something like cps-weights.csv and cps-factors.csv.

All of @martinholmer's and @zrisher's comments make sense to me. @andersonfrailey, what do you think?

**Comment by zrisher** [comment]
> If Zach's impression is correct, then doesn't the logic of moving the file from the tax-calculator repo to the taxpuf repo also apply to the StageIFactors.csv file? 

My understanding of `StageIFactors.csv` could be flawed, but I believe it contains some assumed economic growth factors, which could be useful to anyone that wants to age a particular set of record data but doesn't want to provide their own growth assumptions.  It's basically "default data" for growth configuration, just as "current_law_policy.json" is default data (and meta/schema data) for policy configuration. If I want to test the affect of a certain policy on my own tax data for many years, I can simply assume my wages will grow in line with the rest of the economy and rely on the data in this file automatically. Right?

If the CPS file comes with its own set of growth assumptions though, we would need to decide which should be the default for Tax Calculator.

> Also, shouldn't these two files also be renamed? Otherwise, there could be a name collision when the new CPS-based cps.csv file is introduced with its own weights file and factors file.

If the CPS data is similar to the PUF data in its versioning process, perhaps it deserves its own repo/package on which `taxcalc` depends, similar to `taxpuf`? If that was the case, the all the PUF files could be read from the conda-installed `../../taxpuf` directory, and all the CPS files could be read from a separate conda-installed directory. They never need to be moved directly into the tax-calculator folder, because the packages provide helper methods to read the data directly as a Dataframe.

**Comment by martinholmer** [comment]
@zrisher said:
> My understanding of `StageIFactors.csv` could be flawed, but I believe it contains some assumed economic growth factors, which could be useful to anyone that wants to age a particular set of record data but doesn't want to provide their own growth assumptions. It's basically "default data" for growth configuration, just as `current_law_policy.json` is default data (and meta/schema data) for policy configuration.

Yes, I believe that is the role of the Stage I factors, but the key question is how are the values of those factors determined.  If they are determined in a way that makes the projected `puf.csv` aggregates (wages, etc.) be equal to certain target aggregate amounts, then `StageIFactors.csv` is dependent on `puf.csv`.  On the other hand, if the value of the factors are determined without any regard to projected `puf.csv` aggregate totals, then `StageIFactors.csv` is independent on `puf.csv` and can be used with any input dataset.

So, @MattHJensen and @andersonfrailey and @Amy-Xu, which is it?

**Comment by martinholmer** [comment]
@zrisher said:
> If the CPS data is similar to the PUF data in its versioning process, perhaps it deserves its own repo/package on which taxcalc depends, similar to taxpuf?

I was imagining that, because the `cps.csv` data has no privacy restrictions like the `puf.csv`, the `cps.csv` file (and any associated weights and factors files) would be an integral part of the taxcalc package.  What advantage would be gained by putting them in their own repo?

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @GoFroggyRun

**Comment by zrisher** [comment]
>Yes, I believe that is the role of the Stage I factors, but the key question is how are the values of those factors determined...

My impression was that initial puf data & growth factors & distributional targets -> weights, and that everything on the left are direct estimates of actual economic figures. But yes, others are way more knowledgeable than me on this.

> I was imagining that, because the cps.csv data has no privacy restrictions like the puf.csv, the cps.csv file (and any associated weights and factors files) would be an integral part of the taxcalc package. 

You're right, it makes the most sense to include it. I was thinking of a more population-agnostic model that's not really relevant right now. The below naming convention you proposed sounds good to me:

> when the new CPS-based cps.csv file is included in the tax-calculator repo (because there are not privacy concerns about the CPS data), it would be accompanied by files named something like cps-weights.csv and cps-factors.csv.

**Comment by andersonfrailey** [comment]
Sorry for the delayed response. I had family in town this weekend and didn't check my email.

`StageIFactors.csv` is determined independent of `puf.csv`. The values are determined without regard to `puf.csv` aggregate totals and the file will be the same whether you use `puf.csv` or `cps.csv`. Because of this and because it is a rather small file, I recommend leaving it as it.

Renaming the files as @martinholmer suggested to specify if they are to be used with `puf.csv` or `cps.csv` will also be helpful in avoiding confusion once `cps.csv` is up and running.

As for including `cps.csv` and `cps-weights.csv` in the tax-calculator package, I like this idea, but  keep in mind that they will package much larger.

I'm also on board with moving `WEIGHTS.csv` into the taxpuf repo because, as @zrisher and @martinholmer point out, it is only compatible with `puf.csv`. When I complete my work in #1110 the related adjustment factor file should also be kept in this repo because it will be specific to `puf.csv` and large.

cc: @MattHJensen

**Comment by martinholmer** [comment]
@andersonfrailey,  Thanks for your clear answers to the questions posed by @zrisher and me.

**Comment by martinholmer** [comment]
See pull request #1153 for a way to reduce substantially the size of the `WEIGHTS.csv` file that GitHub complains about as being too large (as described in issue #1146).  Closing issue #1146.
