### ISSUE TITLE
Testing jupyter notebooks

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1151]
The bug in our `10_min` notebook (#1150) has me thinking about how to test Jupyter notebooks. 

My first instinct was to add a test to `test_calculate.py` that does the same thing as the notebook. The problem with that approach is that whenever a contributor updates the notebook, s/he would have to remember to update the test as well. 

My second instinct was to search google, and I found this: [nbval](https://github.com/computationalmodelling/nbval). It seems to be designed for exactly the purpose we need, but it would require us adding another dependency, and one that looks somewhat immature. 

Does anyone have any experience working with `nbval` or have experience with other solutions for testing notebooks?  

cc @PeterDSteinberg @talumbau

**Comment by MattHJensen** [comment]
This actually looks like what we need: http://blog.thedataincubator.com/2016/06/testing-jupyter-notebooks/ 

Programmatic execution of the notebook and reports any errors in output.

**Comment by PeterDSteinberg** [comment]
I agree @MattHJensen that the best fix is to dump the notebooks automatically to scripts (as shown in the blog linked in comment above).  So the idea would be a test function would 
 * Automatically dump notebook(s) to a script in a temp dir
 * Run the script
 * Assert the script exits without error
 * Delete the temp dir 

@MattHJensen  - a couple questions:
 * When do we run this test, in Travis?  If so, we would need to add `Jupyter` at least to the Travis CI environment.  We probably don't want Jupyter to be installed on the dropq workers - not a terribly big deal but just extra install time.
 * Are there any assertions we should do on outputs, other than just checking the generated script can run without exception.

**Comment by MaxGhenis** [comment]
On today's call @martinholmer mentioned his work to improve documentation for new users. I suggested adding Jupyter notebooks, and he and @MattHJensen mentioned the difficulties testing them being the rationale for leaving them off. Could we reopen this issue to discuss?

I see a few possible approaches:
1. Test along the lines of https://blog.thedataincubator.com/2016/06/testing-jupyter-notebooks, as @MattHJensen [suggested](https://github.com/PSLmodels/Tax-Calculator/issues/1151#issuecomment-274495344).
2. Leave testing of the logic employed in notebooks to `*.py` tests, and just ensure that the notebook has been run since the last update. This follows [this pythonlibrary.org post](https://www.blog.pythonlibrary.org/2018/10/16/testing-jupyter-notebooks/) which says "If you want to test your code properly, you should write your code outside of Jupyter and import it into cells if you need to." From https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/tests/test_docs.py it looks like this timestamp-checking is currently the extent of recipe checking, but @martinholmer PLMK if there's more I'm missing.
3. (2) but also check that the `.ipynb` file itself hasn't changed (unless this was intended). So this could involve storing a golden set of notebooks in the testing directory to compare against.

If we can get it working I'm happy to contribute recipe notebooks, such as https://github.com/MaxGhenis/taxcalc-notebooks/blob/master/recipes/recipe00.ipynb.

**Comment by rickecon** [comment]
I think it will be very important to have Jupyter notebooks as part of every PSL model repo. I think it would be an important marketing tool that would reduce any technical barriers to entry. I think the notebooks should also be a requirement in that they combine documentation with executable code.

QuantEcon has created a way to incorporate [continuous integration testing](https://quantecon.org/news-item/code-testing-lecture-site) of Jupyter notebook code through the [Jupinx](https://github.com/QuantEcon/sphinxcontrib-jupyter) (Sphinx plus Jupyter), which is a tool that compiles and creates Jupyter notebooks from RST files. This allows Jupyter notebooks to be tracked, edited, and updated collaboratively on GitHub.

This [12/11/17 blog post](https://medium.com/quantecon-blog/introducing-jupinx-60ba9fc12f4f) introduces the Jupinx library. The Jupinx GitHub repository is [https://github.com/QuantEcon/sphinxcontrib-jupyter](https://github.com/QuantEcon/sphinxcontrib-jupyter). A recent [1/11/19 blog post](https://quantecon.org/news-item/major-update-to-build-system) shows how this Jupinx system and integration with the QuantEcon system of notebooks and lectures has continued to be developed and improved. @MaxGhenis @MattHJensen @jdebacker

**Comment by MaxGhenis** [comment]
@rickecon would you still say Jupinx is the best bet for continuous integration of documentation notebooks? The https://github.com/QuantEcon/jupinx commit history looks like it hasn't been ignored, and https://jupinx.quantecon.org looks pretty good, but not sure if there are other comparable tools.

https://www.reviewnb.com could also be used in conjunction to view changes to the Jupyter outputs.

#2412 reminded me of this.

**Comment by rickecon** [comment]
Yes. I think Jupinx is the best solution. I heard of another solution discussed on the [Python Bytes podcast](https://pythonbytes.fm/episodes/show/178/build-a-pypi-package-from-a-jupyter-notebook) called [NBDev](https://github.com/fastai/nbdev). It is produced by the [FastAI](https://www.fast.ai/) organization, which definitely has good people and cares about openness and pedagogy. However, it looks like NBDev is more focused on package and library management, making the notebook essentially a package. However, the problem that I care most about is the one of updating the notebook document using version control. Jupinx allows version control and attribution.
