### ISSUE TITLE
Update README with more installation options

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/Tax-Calculator#1370]
Discuss:
 * [ ] Installing from `dev` vs `main` package
 * [ ] Installing from `setup.py`
 * [ ] Git tagging and release system
 * [ ] How packages are built and what their version pinning is like
 * [ ] Do each of the above in the README for Tax-Calculator, webapp-public, B-Tax, OG-USA, and cross-link the README files as needed
 * [ ] Revisit the new docs created under this issue after [webapp PR 553 is merged](https://github.com/OpenSourcePolicyCenter/webapp-public/pull/553) (deploy repo refactor)

This issue is in response to discussion on #1368

**Comment by MattHJensen** [comment]
Thanks for opening this @PeterDSteinberg!

**Comment by martinholmer** [comment]
There has been no discussion of the points listed in issue #1370 since the issue was first raised three months ago.  This suggests there is not much demand for the additional installation options listed in #1370.  So, this issue is being closed.  If developers would like any of these extra features, they can raise a new issue describing what the desired new installation option is and why it would be helpful in their workflow.
