### ISSUE TITLE
Question on CTC under 5 bonus.

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1413]
From a Senate staffer:

> In the nonrefundable credits section of Tax Brain, for “Bonus child tax credit maximum for qualifying children under five,” does that topped-up credit value apply to the phase-in and phase out rates of the Child Tax Credit? Or is that a clean dollar increase to the max CTC?
>  
> Visually, would this make the schedule of CTC like this (y is credit value, x is income):
> 
> ![image006](https://user-images.githubusercontent.com/8301092/26941054-065e9422-4c4b-11e7-92db-fa874dfd9071.png)
> 
> Or like this?
> 
> ![image012](https://user-images.githubusercontent.com/8301092/26941061-0c21e738-4c4b-11e7-9715-08fb53db77f3.png)
> 

Need to double check the implementation in functions.py to answer

**Comment by MattHJensen** [comment]
My reading is that the CTC phase _out_ is applied to the CTC_c_under5_bonus, but that there is no phase _in_ for the non-refundable CTC and therefore no phase in for the CTC_c_under5_bonus. 

So the first chart is closer than the second chart, but the left side is incorrect. 

@codykallen, could you confirm?

**Comment by codykallen** [comment]
@MattHJensen said

> My reading is that the CTC phase out is applied to the CTC_c_under5_bonus

This is correct. The CTC phase out applies to the `CTC_c_under5_bonus` as well. However, since `CTC_c + CTC_c_under5_bonus > CTC_c`, the phase-out period (range of AGI) is lengthened, with the same beginning of the phase-out. That means that neither of the drawings above are correct with regard to the phase-out, since your first graph incorrectly sets the same end-of-phase-out threshold rather than using the same beginning-of-phase-out threshold. See the graph below. 

@MattHJensen also said

> There is no phase in for the non-refundable CTC and therefore no phase in for the CTC_c_under5_bonus.

This isn't really an accurate statement. The CTC is nonrefundable in name only. Although the CTC itself is nonrefundable from a legal perspective, the ACTC makes the CTC effectively partially refundable. Hence an increase in the `CTC_c_under5_bonus` increases the amount passed on to the ACTC, which then gets refunded at the given rate. 

Therefore, _there is a phase in_ for the `CTC_c_under5_bonus`. 

To return to the Senate staffer's question:

> In the nonrefundable credits section of Tax Brain, for “Bonus child tax credit maximum for qualifying children under five,” does that topped-up credit value apply to the phase-in and phase out rates of the Child Tax Credit? Or is that a clean dollar increase to the max CTC?

The topped up credit value applies to the phase-in and phase-outs of the Child Tax Credit, but this misses a nuance. The topped-up value does not affect the phase-in and phase-out rates. It lengthens the AGI intervals of the phase-ins and phase-outs. 

![image](https://user-images.githubusercontent.com/20171679/26955325-0f21ca96-4c84-11e7-8e80-45a8c86186b4.png)

I included a graph of how it actually functions, including the phase-ins and phase-outs. Note that this is done using `CTC_c_under5_bonus = 500`, whereas the Clinton proposal used a bonus of $1000, a 45% phase-in rate (compared to the current law 15%), and a refundability threshold of $0 (instead of the current law $3000).

**Comment by MattHJensen** [comment]
Thanks @codykallen, I sent a link to your comment.

**Comment by MattHJensen** [comment]
Still welcoming comments of course, but closing the issue.
