### ISSUE TITLE
Enhancement request for Calculator.read_json_param_files function

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#1443]
@brittainhard said in the conversation surrounding [webapp-public pull request 556](https://github.com/OpenSourcePolicyCenter/webapp-public/pull/556):
> I used the `read_json_param_files` function and it looks like it returns what I need. I was mistaken, and thought earlier that it was returning me a tuple containing dictionaries, rather than the one dictionary. I'll modify the code to use it.
>
> In the future, do you think you could modify the function to take python dictionaries or JSON strings, rather than having to pass a filename?

First, passing a string variable that contains the contents of a JSON parameter file (rather than the name of that JSON parameter file) makes sense, but I'm not sure if you want the JSON string to be standard or to allow comments.  Can you clarify?

Second, I don't understand what you mean by "python dictionaries" (rather than JSON file names).  The function **returns** a dictionary, so what would be the point of passing dictionaries to the function?  Can you clarify?

I'm happy to enhance the `Calculator.read_json_param_files` function, but need more information about your needs and about how the enhanced function would be used by TaxBrain.

@MattHJensen @PeterDSteinberg

**Comment by brittainhard** [comment]
@martinholmer for some context, to use `read_json_param_files` I have to save text data as a temporary file, and then pass the filename, so that the function can read and open the filename. If I were able to pass the raw JSON text, I would no longer have to deal with temporary files. The python dictionary would give me the option to pass de-serialized JSON, but this is not as important as being able to pass JSON text.

It would simplify the application much more to be able to pass text, rather than having to create a file. Passing a dictionary is unnecessary for now, since there is currently no use-case.

**Comment by martinholmer** [comment]
@brittainhard said:
> For some context, to use read_json_param_files I have to save text data as a temporary file, and then pass the filename, so that the function can read and open the filename. If I were able to pass the raw JSON text, I would no longer have to deal with temporary files. The python dictionary would give me the option to pass de-serialized JSON, but this is not as important as being able to pass JSON text.
>
> It would simplify the application much more to be able to pass text, rather than having to create a file. Passing a dictionary is unnecessary for now, since there is currently no use-case.

Thanks for the clarification.  I'll begin work on allowing "raw JSON text" as a function argument.
I'm assuming that by "raw" you mean including any of the //-comments that were in the disk file.

**Comment by martinholmer** [comment]
Merge of pull request #1445 resolves issue #1443.
