### ISSUE TITLE
Tables should use s006/100 as weights

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#145]
`s006` is stored as the `weight * 100` for the purpose of making decimals implicit. We should divide `s006` by 100 before making tables. I suggest making a new variable, e.g., `weight = s006 / 100`

**Comment by MattHJensen** [comment]
Note that this interacts with: https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/taxcalc/records.py#L57.

**Comment by MattHJensen** [comment]
Also note that the weights in WEIGHTS.csv have already been divided by 100.

**Comment by MattHJensen** [comment]
- [ ] Create a new `weight` attribute that equals `s006/100` in 2008 and equals the weight variable from O'Hare for years after 2008
- [ ] Make `s006` = the O'Hare weight * 100 for years after 2008
- [ ] Modify tables to use the 'weight' variable, not `s006`

These steps will keep us from needing to modify the `s006` variable from the puf, will keep `s006 ` consistent across years, and will ensure that we are using the right weights for our tables.

**Comment by martinholmer** [comment]
@MattHJensen discussed the `s006` weight variable read in from the `puf.csv` file in issue #145 during the February-March, 2015, period, and he suggested some changes to the Tax-Calculator code.

In the current `Records` class code, the `s006` variable is divided by 100 in every year.  So, it would seem that the correct weights are being used in Tax-Calculator. I suppose it would speed Tax-Calculator execution very slightly if the `s006` variable in the `puf.csv` file were to be already divided by 100, so that this division was not necessary in the code.  But how important is this enhancement?

Can we close issue #145?  If not, a new issue (that refers to the current code and `puf.csv` contents) needs to replace the old issue #145.

@Amy-Xu

**Comment by Amy-Xu** [comment]
Personally feel this issue not relevant anymore w/ current master of Tax-Calculator.

**Comment by MattHJensen** [comment]
Thanks @martinholmer and @Amy-Xu. Agreed that this should be closed and closing.

**Comment by martinholmer** [comment]
@Amy-Xu and @MattHJensen,  Thanks for your quick responses.
