### ISSUE TITLE
Consider doing `conda build` then `conda install --use-local` in Travis CI

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/Tax-Calculator#1474]
We had a conda packaging related meeting today where we discussed that it could be helpful to have Travis CI build conda packages for Tax-Calculator instead of just installing from source.  That way we test out that the pkg can be built with the dependencies of the recipe.  

[This line of Travis CI](https://github.com/open-source-economics/Tax-Calculator/blob/master/.travis.yml#L23) would change to 2 lines of code that do `conda build` then `conda install --use-local`.  We can discuss here as needed whether this is a good idea, then if it sounds good, I'll make reminder issues in B-Tax and OG-USA to do the same idea, referring back to this issue.

**Comment by martinholmer** [comment]
@PeterDSteinberg said:
> We had a conda packaging related meeting today where we discussed that it could be helpful to have Travis CI build conda packages for Tax-Calculator instead of just installing from source. That way we test out that the pkg can be built with the dependencies of the recipe.
>
> [This line of Travis CI](https://github.com/open-source-economics/Tax-Calculator/blob/master/.travis.yml#L23) would change to 2 lines of code that do `conda build` then `conda install --use-local`. We can discuss here as needed whether this is a good idea, then if it sounds good, I'll make reminder issues in B-Tax and OG-USA to do the same idea, referring back to this issue.

Actually, I don't remember any discussion of Travis CI during yesterday's session.

You haven't explained what improvement the above code change would provide.  Right now developers working on Tax-Calculator can build a taxcalc package with the code as it is (even if it is not committed or if it is not in a tagged release) locally and install that local package at any time using the `conda.recipe/install_local_taxcalc_package.sh` script.

As far as I can see, there is no need for additional Tax-Calculator capabilities in this area.

If you can't provide better motivation for your proposed change (what need is this going to meet?), please close this issue and concentrate on **pressing needs** like (a) revising the policybrain-builder script to be compatible with the new release process and (b) fixing all the reported bugs in TaxBrain and (c) developing better TaxBrain testing procedures.  Those are the areas where your effort would produce major benefits.

@MattHJensen @PeterDSteinberg @brittainhard @jbcrail @hdoupe

**Comment by martinholmer** [comment]
@PeterDSteinberg said when raising issue #1474 on July 12th:
> We had a conda packaging related meeting today where we discussed that it could be helpful to have Travis CI build conda packages for Tax-Calculator instead of just installing from source. That way we test out that the pkg can be built with the dependencies of the recipe.
>
> This line of Travis CI would change to 2 lines of code that do conda build then conda install --use-local. We can discuss here as needed whether this is a good idea, then if it sounds good, I'll make reminder issues in B-Tax and OG-USA to do the same idea, referring back to this issue.

After receiving no further clarification from you about the goal of these suggested changes, it occurred to me that the point of your suggestion is as follows:

Local testing and testing on GitHub use the Tax-Calculator package dependencies specified in the `environment.yml` file, while in production the taxcalc uses the package requirements specified in the `conda.recipe/meta.yaml` file.  And if these dependencies/requirements are in some way inconsistent, the testing might not detect problems using the taxcalc package.

Is that the potential problem your suggestion is meant to avoid?

If so, your suggestion would not have any effect on local testing, which could be missing problems because of inconsistencies between the `environment.yml` and `conda.recipe/meta.yaml` files.

Why not just add a Tax-Calculator test that reads the contents of those two files and fails if there are inconsistencies?  The same kind of test could also be added to the OG-USA and B-Tax repos.

**Comment by martinholmer** [comment]
It has been nearly a week since @martinholmer asked @PeterDSteinberg about whether his interpretation of the goal of #1474 was correct.  There has been no objections raised to his interpretation and a new test has been added in merged pull request #1516 that addresses Martin's interpretation of this issue.   Given that extra test and the lack of discussion, issue #1474 is being closed.
