### ISSUE TITLE
"positional indexers are out-of-bounds" error on synthetic CPS file

### ISSUE THREAD

**Issue by evtedeschi3** [open-source-economics/Tax-Calculator#1573]
I've customized the cps.csv file to have updated data to 2017. The output is based on a reweighting of s006 in a non-policy dump to 2017. The file works fine when given a name different from "cps.csv" or "puf.csv",  however in those cases, TC CLI will not automatically extrapolate / age the data to future years. I would like to be able to take my custom csv and have TC extrapolate the variables to years beyond 2017 as it normally does. I tried renaming the file to "puf.csv", but when I do this, I get a "positional indexers are out-of-bounds" error:
```

$ tc puf.csv 2026 --tables --reform fullreform7.json --dump
Traceback (most recent call last):
  File "/Users/ernietedeschi/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py", line 1715, in _get_list_axis
    return self.obj.take(key, axis=axis, convert=False)
  File "/Users/ernietedeschi/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1817, in take
    convert=True, verify=True)
  File "/Users/ernietedeschi/anaconda/lib/python3.6/site-packages/pandas/core/internals.py", line 4002, in take
    indexer = maybe_convert_indices(indexer, n)
  File "/Users/ernietedeschi/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py", line 1997, in maybe_convert_indices
    raise IndexError("indices are out-of-bounds")
IndexError: indices are out-of-bounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ernietedeschi/anaconda/bin/tc", line 11, in <module>
    sys.exit(cli_tc_main())
  File "/Users/ernietedeschi/anaconda/lib/python3.6/site-packages/taxcalc/cli/tc.py", line 126, in cli_tc_main
    exact_calculations=args.exact)
  File "/Users/ernietedeschi/anaconda/lib/python3.6/site-packages/taxcalc/taxcalcio.py", line 238, in init
    exact_calculations=exact_calculations
  File "/Users/ernietedeschi/anaconda/lib/python3.6/site-packages/taxcalc/records.py", line 154, in __init__
    self.WT = self.WT.iloc[self.index]
  File "/Users/ernietedeschi/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py", line 1328, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/Users/ernietedeschi/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py", line 1738, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "/Users/ernietedeschi/anaconda/lib/python3.6/site-packages/pandas/core/indexing.py", line 1718, in _get_list_axis
    raise IndexError("positional indexers are out-of-bounds")
IndexError: positional indexers are out-of-bounds

```

Meanwhile, I also tried renaming the file to "cps.csv" but I suspect TC just pulls the cps.csv version from its package.

**Comment by evtedeschi3** [comment]
As an update: I compressed and moved my csv file to the package folder and ran the commands as "cps.csv". TC now says it's extrapolating but notes that I "loaded data for 2014" even though the entire file is set for 2017.

**Comment by martinholmer** [comment]
@evtedeschi3 said in issue #1573:
> I've customized the `cps.csv` file to have updated data to 2017. The output is based on a reweighting of s006 in a non-policy dump to 2017. The file works fine when given a name different from `cps.csv` or `puf.csv`, however in those cases, TC CLI will not automatically extrapolate / age the data to future years.  I would like to be able to take my custom csv and have TC extrapolate the variables to years beyond 2017 as it normally does.

I'd like to help you be able to achieve your analytical goal, but I need to understand better what sort of analysis you want to conduct.  As best I can tell you're undertaking a pretty advanced analysis and `tc` is not helping you.  Perhaps there is another way to work with `tc` that will allow you to conduct your analysis or maybe `tc` needs to be enhanced, I can't tell until I understand more.

Your first two sentences above suggest that you did something like `tc cps.csv 2017 --dump` to get a large CSV file in which variables are extrapolated to their 2017 values and the weights are the standard 2017 CPS sample weights.  Right?  If so, lets call that file `custom17.csv`.  You may have noticed that if you do `tc custom17.csv 2017` that you get the exact same output as generated by `tc cps.csv 2017 --dump`.

Then you somehow changed the weights in the `custom17.csv` file, right?  That's where I need to understand more about what you want to do.  Why do you want to change the weights of the individuals in the cps.cvs sample?  What data are you using to change the 2017 weights?

P.S.  The `tc` CLI to Tax-Calculator is designed to do extrapolation (or "aging") in only two special cases: when the input file is `puf.csv` and when it is `cps.csv`.  All other input files are used as is.  This is because `tc` has the data necessary to do the extrapolate only for `puf.csv` and `cps.csv`.

**Comment by evtedeschi3** [comment]
Thanks for the help Martin. There's a simple question to start and then some context.

The simple question is: if the tc CLI encounters a "cps.csv" file with all 2017 (FLPDYR) data, does it actually extrapolate using its 2017 assumptions as a base even though the CLI returns that "You loaded data for 2014"? Or is it in fact treating the data as 2014 data and extrapolating from there?

Now for the context, let me back up and explain my motivation and steps.

In a sentence, my goal here is to rework the cps.csv file to be closer to the PUF. I noticed that the cps.csv file yields very different results than the web-based interface, which I assume uses the PUF (but correct me if I'm wrong). Not just different policy effects, either, but apparently even just different baseline counts & aggregates.

So my goal is to reweight the cps.csv file in a way that might yield results in tc CLI closer to the PUF. If that worked, next idea was to target other published distributional summaries such as TPC's or Treasury's.

You're right that I simply started with `tc cps.csv 2017 --dump` . I then took the resulting file and ran it through an iterative reweighting loop that targeted the current law diagnostic tables for 2017 from the web interface. In this case, the code gradually adjusts s006 so that the aggregate filer count as well as the aggregate AGI, income tax, payroll tax, itemized deductions, and personal exemptions match the table, both overall and by income bin.

To be clear, the only variable I'm changing in all of this is s006.

Ideally, I'd create a base reweighted file for, say, 2017 (or an earlier year if that makes more sense given what I'm trying to do), and then for future years tc CLI's extrapolation would (hopefully) remain close-ish to the web-based interface.

**Comment by martinholmer** [comment]
@evtedeschi3,  Thanks for your explanation.  There are many differences between the `puf.csv` sample/variables and the `cps.csv` sample/variables, so I'm not sure how successful it will be to just change the weights.  But I see what you're doing now.

There is no way to do this once in 2017 and the "extrapolate" to all subsequent years because `tc` does not have the extrapolation information needed for the custom 2017 file.

Why not do the following for each year you want to analyze?  I'll explain assuming that analysis year is 2020, but any year up to 2026 will work.  Use TaxBrain (which is using the `puf.csv` data) to simulate no-reform for 2020 and note the aggregate totals you want to use in your calibration work.  Then do `tc cps.csv 2020 --dump` to get the dump file for 2020.  Then do your calibration work on that dump file using the totals you noted from  the TaxBrain run for 2020.  Then you have what I'll call `calibcps20.csv` which you can use for 2020 reform analysis like this: `tc calibcps20.csv 2020 --reform any.json --tables --graphs`.

This is a little tedious because you have to do the calibration for each year that you want to analyze a reform. 
Doing the calibration for each year of interest is logically equivalent to customized extrapolation.

Of course, there is a another option be that costs money (but save in time): buy a IRS-SOI PUF license for the year we are using in our `puf.csv` and we'll be able to share our `puf.csv` with you.  Others using Tax-Calculator have done this, so its not an unreasonable option to consider.

**Comment by martinholmer** [comment]
@evtedeschi3 asked:
> The simple question is:  if the `tc` CLI encounters a `cps.csv` file with all 2017 (FLPDYR) data, does it actually extrapolate using its 2017 assumptions as a base even though the CLI returns that "You loaded data for 2014"?  Or is it in fact treating the data as 2014 data and extrapolating from there?

Neither.  Entering `cps.csv` as the INPUT argument to `tc` automatically reads the 2014 `cps.csv` data (and associated weights and extrapolation factors) out of the `taxcalc` conda package.  So, it completely ignores any file you named `cps.csv`.

**Comment by evtedeschi3** [comment]
**@martinholmer** said:
> Neither. Entering cps.csv as the INPUT argument to tc automatically reads the 2014 cps.csv data (and associated weights and extrapolation factors) out of the taxcalc conda package. So, it completely ignores any file you named cps.csv.

I went into the local taxcalc conda package folder, backed up the default cps.csv.gz, and replaced it with my custom file. Ran tc after backup & deletion but before I moved my custom file to make sure I was working with the right folder: got a file-not-found error so figured I had identified the right one.

**Comment by martinholmer** [comment]
@evtedeschi3 said:
> I went into the local taxcalc conda package folder, backed up the default cps.csv.gz, and replaced it with my custom file. Ran tc after backup & deletion but before I moved my custom file to make sure I was working with the right folder: got a file-not-found error so figured I had identified the right one.

Have you cloned the Tax-Calculator repository? 
What do you mean by the "taxcalc conda package folder"?   What directory is that in the repository?

**Comment by evtedeschi3** [comment]
**martinholmer** asked:
> What do you mean by the "taxcalc conda package folder"? What directory is that in the repository?

../anaconda/lib/python3.6/site-packages/taxcalc

**Comment by hdoupe** [comment]
@evtedeschi3 the `taxcalc` conda package is very convenient when you are using the package as is.  However, since you are making modifications to the package, you may find it easier to clone the Tax-Calculator github repository and work directly on that.  You can check out our [contributor guide](http://taxcalc.readthedocs.io/en/latest/contributor_guide.html) to help you get started.

**Comment by evtedeschi3** [comment]
Thanks **@hdoupe **. Yes, when I arrive at a satisfactory solution that's exactly what I plan to do. Right now I'm just tinkering.

**Comment by martinholmer** [comment]
@evtedeschi3 said that after doing `conda install -c ospc taxcalc`, he
> went into [~/anaconda/lib/python3.6/site-packages/taxcalc directory], backed up the default cps.csv.gz, and replaced it with my custom file. Ran `tc` after backup & deletion but before I moved my custom file to make sure I was working with the right folder: got a file-not-found error so figured I had identified the right one.

When I install the taxcalc package and go to that directory, I see (in part):
```
  -rw-rw-r--    2 mrh  staff  22697312 Sep 21 13:17 cps.csv.gz
  -rw-rw-r--    2 mrh  staff   8292835 Sep 21 13:17 cps_weights.csv.gz
```
Notice that the weights for each `cps.csv` sample individual for each year are in the `cps_weights.csv.gz` file, **not** in the `cps.csv.gz` file.

If you wanted to put your customized weights for 2017 and all the other subsequent years into the `cps_weights.csv.gz` file, then **maybe** your approach would work.  But you're playing with fire operating at such a low level, which is why you're getting burned.

What's that matter with my earlier suggestion about how to solve your problem?
Your haven't commented on the viability of that suggestion.

The low-level operations you're trying in the ~/anaconda/lib/python3.6/site-packages/taxcalc directory are not recommended in the [Using Tax-Calculator documentation](http://open-source-economics.github.io/Tax-Calculator/) and none of the Tax-Calculator developers have every tried such a thing.

**Comment by evtedeschi3** [comment]
**@martinholmer** said: 
> If you wanted to put your customized weights for 2017 and all the other subsequent years into the cps_weights.csv.gz file, then maybe your approach would work. But you're playing with fire operating at such a low level, which is why you're getting burned.

Good information. Your warning is appreciated but a lot of this exercise for me is just comprehending the nitty gritty mechanics of how tc works. 

> What's that matter with my earlier suggestion about how to solve your problem?

I forgot to mention that I've been trying that in the background for a day now with different years. In fact what prompted my original question was the lack of indication from tc CLI that it was extrapolating to future years. I couldn't judge the viability of that strategy before since I didn't have the additional helpful information you've provided here.

**Comment by martinholmer** [comment]
@evtedeschi3 said:
>> If you wanted to put your customized weights for 2017 and all the other subsequent years into the cps_weights.csv.gz file, then maybe your approach would work. But you're playing with fire operating at such a low level, which is why you're getting burned.
>
> Good information. Your warning is appreciated but a lot of this exercise for me is just comprehending the nitty gritty mechanics of how tc works.
>
>> What's that matter with my earlier suggestion about how to solve your problem?
>
> I forgot to mention that I've been trying that in the background for a day now with different years. In fact what prompted my original question was the lack of indication from tc CLI that it was extrapolating to future years. I couldn't judge the viability of that strategy before since I didn't have the additional helpful information you've provided here.

OK.  So, now you understand that `tc` generally does not extrapolate (or "age") input data except in two special cases (when input is `puf.csv` or `cps.csv`).

I think we'd all be interested in hearing from you about how your high-level multiple-year weight-calibration work turns out.

**Comment by evtedeschi3** [comment]
**@martinholmer** said:
> I think we'd all be interested in hearing from you about how your high-level multiple-year weight-calibration work turns out.

I'd certainly be happy to share my impressions. I'm cautiously pessimistic at this point as I think that even targeting five aggregates by income bin is solvable in too many ways to necessarily mimic the PUF in policy analysis, but will dig in.

Oh, and we're looking into purchasing a copy of the PUF anyway so this all may turn out to be a fun but ultimately moot exercise in the end.

**Comment by martinholmer** [comment]
@evtedeschi3 said:
> Oh, and we're looking into purchasing a copy of the PUF anyway so this all may turn out to be a fun but ultimately moot exercise in the end.

In order for us to share our current `puf.csv` file, you would new to buy the 2009 IRS-SOI PUF file.
Sometime in the coming weeks or months, we might switch to a more recent PUF file.
@andersonfrailey can you say something about the timing and what the new PUF year would be?

**Comment by martinholmer** [comment]
@evtedeschi3 said (my emphasis):
> I'm cautiously pessimistic at this point as I think that even targeting five aggregates by income bin is **solvable in too many ways** to necessarily mimic the PUF in policy analysis, but will dig in.

Yes, it is not clear how exactly to adjust the weights.  Plus many of the reasons for different tax results have nothing to do with weights, but are related to missing income variables, top-coded income variables, and very few, if any, very rich people in the `cps.csv` file.

**Comment by rickecon** [comment]
A suggestion for re-weighting CPS variables to match income targets.

1. Choose `N` income targets you want to match.
2. Group the CPS observations to correspond (roughly, if not exactly) into `N` bins corresponding to the bins of the income targets you chose.
3. Estimate `N` CPS bin weights that make the CPS income averages match the `N` income targets as closely as possible (minimize a sum of squared deviations, L^2 norm).
4. Re-weight each of the CPS weights in each bin by the constant factor that makes the implied aggregate CPS bin weight equal to the estimated bin weight from step (3).

**Comment by evtedeschi3** [comment]
Yes **@rickecon** that's the basic approach I've been using, although looping through just those steps doesn't converge. So I've added steps that target above- or below-mean filers for reweight depending on the over/under shoot at each step.

**Comment by martinholmer** [comment]
@evtedeschi3,  You are right that the CPS results using the Tax-Calculator CLI `tc` locally on your computer are not always a good match with the PUF results generated on the TaxBrain website.  You had mentioned the possibility of getting a PUF license from IRS-SOI so that you could get results on your computer that were closer that those generated by TaxBrain.

There is another way to get the same kind of results without spending the money to get an IRS-SOI data license.  You can upload the JSON reform files (and optionally JSON assumption files) that you would normally use on your computer with `tc` to TaxBrain where it will use the PUF data to simulate your reform.

If this sounds interesting, you can read more about the upload procedure in the [Using Tax-Calculator](http://open-source-economics.github.io/Tax-Calculator/) documentation (searching for the phase "Upload Files to TaxBrain") or go directly to the [TaxBrain file-upload page](http://www.ospc.org/taxbrain/file/).  Let us know if you have any questions.

**Comment by martinholmer** [comment]
@evtedeschi3,  I'm going to close issue #1573 (that you raised about problems with the synthetic CPS file you created), but we hope you keep working with Tax-Calculator and TaxBrain.  If you have any questions, please raise a new issue.  And if you have any suggestions about improvements, please let us know about them.
