### ISSUE TITLE
Cool charts to add to Tax-Calculator

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1592]
Looking for chart ideas and contributors to build the charts into Tax-Calculator. These charts will be available to Tax-Calculator users and would be possibilities for adding to PolicyBrain. 

If you are interested in contributing a visualization to Tax-Calculator, look through the comments on this issue for ideas. 

If you have an idea for a cool chart or feedback (including itty bitty details) on other posted charts, please leave a comment on this issue. 

- [ ] DOCUMENTATION on how to add charts. Where to look in the code base for examples. What technology is recommended. What citation should be included by default. Etc. 
- [ ] [Distribution of tax units by tax bracket and filing status.](https://github.com/open-source-economics/Tax-Calculator/issues/1592#issuecomment-337728251) (NYT)
- [ ] [Percent change in after-tax income.](https://github.com/open-source-economics/Tax-Calculator/issues/1592#issuecomment-337728778) (TPC)
- [ ]
...

**Comment by MattHJensen** [comment]
![image](https://user-images.githubusercontent.com/8301092/31742804-dc224a7a-b426-11e7-8fc6-4485bfcc0c3b.png)

**Comment by MattHJensen** [comment]
![image](https://user-images.githubusercontent.com/8301092/31742904-367766f4-b427-11e7-844d-12503232ec78.png)

**Comment by MattHJensen** [comment]
Change in after tax income by income group. Bonus points for allowing stacked provisions, like [this example](https://www.nytimes.com/interactive/2017/10/17/upshot/tax-reform-winners-losers-child-tax-credit.html) from Ernie Tedeschi in the NY Times using PolicyBrain output. (The NYT version is a cool looping gif) 

![image](https://user-images.githubusercontent.com/8301092/31746440-7243af36-b435-11e7-9882-e24794811bd6.png)

**Comment by martinholmer** [comment]
@MattHJensen said in issue #1592:
> Looking for chart ideas and contributors to build the charts into Tax-Calculator. These charts will be available to Tax-Calculator users and would be possibilities for adding to PolicyBrain.

@MattHJensen then shows a recent example from the *New York Times*:

![screen shot 2017-10-19 at 12 38 48 pm](https://user-images.githubusercontent.com/12170745/31785710-10d1d18e-b4d4-11e7-8858-d2187875dde8.png)

Seems like many of the charts people are interested in constructing show the population by income decile, but with detail for the top decile.  A common approach breaks the top decile into three subgroups: the top percentile (the 0.99-1.00 quantile range), the next four percentiles (the 0.95-0.99 quantile range) and the bottom five percentiles (the 0.90-0.95 quantile range).

The Tax Policy Center tables typically show detail for the top income decile.

Do we want to add top-decile detail to the distribution and difference tables that use income deciles?
If so, we have a choice about how to do that:
Do we want to show the top decile as a group (like now) and then add the three top-decile subgroups?
Or do we want to **replace** the top decile with the three subgroups?

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @hdoupe @GoFroggyRun @codykallen

**Comment by rickecon** [comment]
@hayleefay You should look at this issue and see if you want to contribute anything.

**Comment by feenberg** [comment]
On Thu, 19 Oct 2017, Martin Holmer wrote:

> 
> @MattHJensen said in issue #1592:
>
>       Looking for chart ideas and contributors to build the charts
>       into Tax-Calculator. These charts will be available to
>       Tax-Calculator users and would be possibilities for adding to
>       PolicyBrain.
> 
> @MattHJensen then shows a recent example from the New York Times:
> 
> screen shot 2017-10-19 at 12 38 48 pm
> 
> Seems like many of the charts people are interested in constructing show the
> population by income decile, but with detail for the top decile. A common
> approach breaks the top decile into three subgroups: the top percentile (the
> 0.99-1.00 quantile range), the next four percentiles (the 0.95-0.99 quantile
> range) and the bottom five percentiles (the 0.90-0.95 quantile range).
> 
> The Tax Policy Center tables typically show detail for the top income
> decile.
> 
> Do we want to add top-decile detail to the distribution and difference
> tables that use income deciles?
> If so, we have a choice about how to do that:
> Do we want to show the top decile as a group (like now) and then add the
> three top-decile subgroups?
> Or do we want to replace the top decile with the three subgroups?

I also see a lot of charts with top 1%, then the next 9% but following TPC 
is probably the best thing to do in this case.

dan

**Comment by MattHJensen** [comment]
> Do we want to add top-decile detail to the distribution and difference tables that use decile bins?
> If so, we have a choice about how to do that:
> Do we want to show the top decile as a group (like now) and then add the three top-decile subgroups?
> Or do we want to replace the top decile with the three subgroups?
> 

I suppose the problem replacing the top decile with three sub groups is that it makes the impact on the the top income group, visually, three times as important as every other group. I suppose you could argue that adding the three broken out groups to the top decile could make it four times more important visually, but there the breakout could be differentiated by color or spacing to mitigate that. I don't have any suggestions about this for now, but it is something that I find somewhat concerning and will be thinking about.

**Comment by MattHJensen** [comment]
I mentioned this issue on Twitter:

> One concern of mine is giving the top decile three times as much visual heft as other deciles due to the breakdown into 90-95, 95-99, top 1.

Ernie Tedeschi replied:

> A valid concern. One way to do it would be to make the Top 1% 1/10 as wide a bar as the full deciles. But that can make it very thin... /1 
> ..so in that case you'd want to make sure to use a high contrast color scheme (dark bars against a light background).

**Comment by martinholmer** [comment]
@MattHJensen said:
> I mentioned this issue on Twitter:
>
>> One concern of mine is giving the top decile three times as much visual heft as other deciles due to the breakdown into 90-95, 95-99, top 1.
>
> Ernie Tedeschi @evtedeschi3 replied:
>
>> A valid concern. One way to do it would be to make the Top 1% 1/10 as wide a bar as the full deciles. But that can make it very thin.

I'm surprised about this whole line of commentary.  If this is so important, why did the *New York Times* publish a [horizontal bar chart](https://github.com/open-source-economics/Tax-Calculator/issues/1592#issuecomment-337728778) in which the "Top 1%" bar, the "95-99" bar and the "90-95" bar all have the same width as the other nine decile bars?

If you take this line of thinking to its logical conclusion, then the width of the vertical bars in [this graph](https://github.com/open-source-economics/Tax-Calculator/issues/1592#issuecomment-337728778) should be different because the number tax units with each filing status is different.  Is that what we want?

Maybe we should have thought about this more before suggesting that people start developing graphs.

Maybe a bar chart is not the best type of chart to be using with these kinds of data.

@feenberg @Amy-Xu @andersonfrailey @hdoupe @GoFroggyRun @codykallen @hayleefay

**Comment by MattHJensen** [comment]
> I'm surprised about this whole line of commentary. If this is so important, why did the New York Times publish a horizontal bar chart in which the "Top 1%" bar, the "95-99" bar and the "90-95" bar all have the same width as the other nine decile bars?

I imagine the NYT did not place high importance on this. Perhaps they didn't think of it. I certainly don't think it is a necessary feature, so perhaps they didn't either. 

> If you take this line of thinking to its logical conclusion, then the width of the vertical bars in this graph should be different because the number tax units with each filing status is different. Is that what we want?

I think it is less important in that case since the majority of the bars are not a unit that implies sameness (like deciles), but it could be a cool feature. 

> Maybe we should have thought about this more before suggesting that people start developing graphs.

I either disagree with or don't understand this sentiment / development philosophy. On a feature like this that doesn't have significant downstream dependencies, my view is that we should aim for incremental progress. As I've expressed, I think #1606 is great. I haven't advocated for not merging that while we have a discussion of this design issue.

> Maybe a bar chart is not the best type of chart to be using with these kinds of data.

That's not my takeaway. Some users will appreciate a bar chart, some users will appreciate a percentiles line chart, some users will appreciate tabular data...

**Comment by MattHJensen** [comment]
Ernie said:

> One way to do it would be to make the Top 1% 1/10 as wide a bar as the full deciles. But that can make it very thin... /

Another approach would be to include the top 10% decile and then create some subtle visual separation between the bars for the 10 deciles and the bars for 90-95, 90-99, and top 1. They could be separated by a dotted line, say, or could be a different color, or both.

**Comment by evtedeschi3** [comment]
@martinholmer 
> I'm surprised about this whole line of commentary. If this is so important, why did the New York Times publish a horizontal bar chart in which the "Top 1%" bar, the "95-99" bar and the "90-95" bar all have the same width as the other nine decile bars?

They didn't distinguish most likely because that's how I submitted my rough draft graphics to them initially.  Since my piece was geared towards a wider audience, I didn't want lay people to get bogged down or confused over the width of different bars or any other visual distinction. It's a genuine trade-off and I had to make a choice. There's no "correct" way to balance rigor with accessibility; it should depend on the goals of the specific project. I made my Twitter suggestions under the assumption that you all had already decided internally to add some sort of distinction to the percentile estimates, which is a perfectly defensible choice. 

@MattHJensen 
> Another approach would be to include the top 10% decile and then create some subtle visual separation between the bars for the 10 deciles and the bars for 90-95, 90-99, and top 1. They could be separated by a dotted line, say, or could be a different color, or both.

What I've seen CBO do is turn the final decile--or in their case, quintile--into a stacked bar that spins off the Top 1%. You can see an example [here](https://www.cbo.gov/publication/51361).

**Comment by martinholmer** [comment]
@MattHJensen said on October 18, 2017:
> Looking for chart ideas and contributors to build the charts into Tax-Calculator. These charts will be available to Tax-Calculator users and would be possibilities for adding to PolicyBrain.
>
> If you are interested in contributing a visualization to Tax-Calculator, look through the comments on this issue for ideas.

Over the past two and a half months, many "cool charts" have been built to visualize Tax-Calculator results.
Most of these interactive charts appear to have been created using the [D3.js library](https://d3js.org/).  Before anybody thinks about creating new charts to visualize Tax-Calculator results, I think they should think carefully about whether the `bokeh` package is the best graphing tool for the job.

**Comment by andersonfrailey** [comment]
If there's interest, I recreated the chart in the New York Times article [Tax Bill Calculator: Will Your Taxes Go Up or Down?](https://www.nytimes.com/interactive/2017/12/17/upshot/tax-calculator.html). It looks like this:

![image](https://user-images.githubusercontent.com/20684675/34535509-1882f30c-f090-11e7-8431-8b81d9fcabeb.png)
The only difference is those receiving tax cuts are on the left side of the dividing line, rather than the right. I could also change it so that instead of the change in tax liability being on the x-axis, we use change in after tax income.

I can put together a PR to add this chart relatively quickly because I already have the code worked out.

With regards to @martinholmer's comment that we should consider whether Bokeh is the right package, in this instance I believe that it would work just as well as any other graphing package. Partially because I already have it written for Bokeh, but also because I (or someone else) could go back and replicate the hover tool that gives details about the tax unit as you hover over a dot at a later date, which in my opinion is a pretty cool feature.

**Comment by rickecon** [comment]
I like this a lot, @andersonfrailey. It is slightly misleading to show cuts in levels by income. My recommendation would be average (effective) tax rate changes in percentage points on the x-axis by income percentile on the y-axis or by income level on the y-axis.

**Comment by andersonfrailey** [comment]
Thanks for the feedback, @rickecon. I was just playing with this a little and there were a number of units who started with an effective tax rate of 0 then saw it change with the reform. How would you suggest dealing with those cases if working with percent changes?

**Comment by feenberg** [comment]
On Thu, 4 Jan 2018, andersonfrailey wrote:

> 
> Thanks for the feedback, @rickecon. I was just playing with this a little and there
> were a number of units who started with an effective tax rate of 0 then saw it change
> with the reform. How would you suggest dealing with those cases if working with
> percent changes?

You can calculate the percentage change in the average tax without running 
in to this problem, which is the result of taking the average of the 
percentage change. Notice the difference whether the division occurs 
before or after the aggregation. I don't think there is any other 
solution.

dan

**Comment by martinholmer** [comment]
The last comment in issue #1592 was made on January 4, about seven months ago.
Are there any reasons to keep issue #1592 open any longer?

@MattHJensen @feenberg @andersonfrailey @rickecon

**Comment by MattHJensen** [comment]
I am fine closing this issue (hopefully without any implicit discouragement to @andersonfrailey for continuing his work on the tornado, just with the view that the next step is probably a PR if he wants to pursue it.)
