### ISSUE TITLE
Why are index.htmx and make.py in taxcalc/docs?

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1633]
@martinholmer said:

> The command python make.py reads the ./taxcalc/docs/index.htmx skeleton file and
writes the fleshed-out ./docs/index.html file, which is the one that needs to be updated in a pull request.

This is the workflow that I followed to update `tax-calculator/docs/index.html`:

from `tax-calculator/taxcalc/docs`
 `python make.html` 
`cp ./index.html ../../docs`
`rm ./index.html`

- Is there a reason we don't keep `index.htmx` and `make.py` in tax-calculator/docs rather than tax-calculator/taxcalc/docs since the output of `make.py` is supposed to go in `tax-calculator/docs` not `tax-calculator/taxcalc/docs`?

- Also, is there a reason that we don't test that the `index.htmx` section headers conform to the `current_law_policy.json` section headers? 

If the answers are just that no one has gotten around to it -- which is completely reasonable -- I'll open separate issues.

**Comment by martinholmer** [comment]
@MattHJensen said:
> This is the workflow that I followed to update `tax-calculator/docs/index.html`:
>```
> cd tax-calculator/taxcalc/docs
> python make.py
> cp ./index.html ../../docs
> rm ./index.html
>```
That would work, except that the `rm ./index.html` statement didn't do what you thought it would do because that file had already been incorrectly added to the repo in merged PR #1620.  (You would have needed to do `git rm index.html`.)

Once the `tax-calculator/taxcalc/docs/index.html` file is removed from the repo, the above should work, although replacing the `cp` with `mv` eliminates the need for the final `rm` and so involves slightly less typing.

**Comment by martinholmer** [comment]
@MattHJensen asked:
> Is there a reason we don't keep `index.htmx` and `make.py` in `tax-calculator/docs` rather than `tax-calculator/taxcalc/docs` since the output of `make.py` is supposed to go in `tax-calculator/docs` not `tax-calculator/taxcalc/docs`?

When originally setting this up it appeared that only the files that would be part of the publicly viewable documentation were supposed to go in the `tax-calculator/docs` directory.  Since the skeleton `index.htmx` file and the `make.py` script did not fit that description, I put them in the `tax-calculator/taxcalc/docs` directory.

We could move them to the `tax-calculator/docs` directory if we are sure they wouldn't be viewable.

Or we could change the `make.py` script to write `index.html` directly to the `tax-calculator/docs` directory.  My memory of why that wasn't done originally, is that the original development was easier that way.

**Comment by martinholmer** [comment]
Issue #1633 has been resolved by pull requests #1649 and #1659.
