### ISSUE TITLE
Question about TCJA_Nov3 on 3 kid joint filers

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1638]
A user is looking at a simple, joint filing taxpayer under current law and TCJA_Nov3.json. 

![image](https://user-images.githubusercontent.com/8301092/32632252-e5b3a6e6-c570-11e7-899f-b571e0af461b.png)

He asks why there is a bump in this chart around the $50,000 dollar mark.  

![image](https://user-images.githubusercontent.com/8301092/32632168-99de4fa0-c570-11e7-9987-32eacf188398.png)

**Comment by codykallen** [comment]
It's hard to be sure just from the graph, but a first guess would be that it's due to the increase in the lowest rate from 10% to 12%.

**Comment by MattHJensen** [comment]
You're right. I should look at the diagnostic table.

**Comment by MattHJensen** [comment]
This turns out to be a combination between the 12% rate and the reduced refundable portion of the CTC in 2018. If I set _II_rt_1 to 0.10,  _CTC_c to $1600, and _DependentCredit_Child_c to $0, as opposed to 0.12, $1100, and $500, then the greatest liability increase over current law is $3.94. (Haven't figured that out yet, but it is small.) 

Closing this issue, although I will follow up if I figure out the $4. Also, if anyone sees anything wrong with the explanation above, please let me know.

**Comment by codykallen** [comment]
@MattHJensen, the CTC refundability is not reduced. In 2018, the refundable portion increases from $1000 to $1100. The nonrefundable portion also appears, but that is in no small part an offset to the loss of the personal exemption.

**Comment by MattHJensen** [comment]
You're right @codykallen reopening.

**Comment by martinholmer** [comment]
My analysis of the $50,000 family in issue #1638, shows that of all the reform provisions in `TCJA_House.json` only a few affect the family's 2018 income tax liability: (A) the increase in the bottom-bracket tax rate, (B) the increase in the standard deduction and elimination of person exemptions, and (C) the changes in the child tax credit (CTC).  None of the other reform provisions have any effect on this family's income tax liability.
```
----------------------------------------------------------
Reform provision   Income tax liability    Change from clp
----------------------------------------------------------
NONE (ie, clp)                 -1369.14             ------
----------------------------------------------------------
(A) ONLY                       -1042.97            +326.17
(B) ONLY                        -400.00            +969.14
(C) ONLY                       -1669.14            -300.00
----------------------------------------------------------
(A)+(B)+(C) TOGETHER            -180.00           +1189.14
----------------------------------------------------------
```
Notice the the sum of the changes cause by the three sets of reform provisions is +995.31, which is less that the +1189.14 change caused by the combination of the three sets of reform provisions.  This difference is caused by the interaction of the reform provisions, primarily the increase in liability caused by the (B) reform provisions (higher standard deduction but no exemptions) being magnified by the (A) reform provision (higher tax rate).

Does this analysis make sense?

I'm not sure why the user who contacted @MattHJensen was puzzled about this.  There have been plenty of newspaper accounts of the tax-raising effects of increasing the bottom tax rate and eliminating personal exemptions, particularly for large families with modest incomes.  That's exact'y the cases the user was asking about.

@feenberg @Amy-Xu @andersonfrailey @hdoupe @codykallen @evtedeschi3

**Comment by MattHJensen** [comment]
@martinholmer, thanks for the followup. I will pass on the takeaway. Closing.
