### ISSUE TITLE
Question on _STD_Dep in TCJA reform

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1643]
The [parameter documentation](http://open-source-economics.github.io/Tax-Calculator/index.html#pol) says of `_STD_Dep`:

> Notes: This parameter should not be decreased because current data have no itemized expenses for non-itemizers.

It also says that it's currently set to 1050.0 as of 2017.

Yet the [TCJA reform](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/TCJA_Nov3.json#L91) reduces it to 500.

Is this OK?

**Comment by codykallen** [comment]
@MaxGhenis, 
The concern when reducing the standard deduction is that doing so would cause more filers to itemize their deductions, but we do not have data on itemized deductions for those who do not itemize. Thus the warning.

However, if one is also limiting itemized deductions, it should not be unreasonable to reduce the standard deduction by a small amount. Especially since the current standard deduction for dependents is already much lower than for other filers.

**Comment by MattHJensen** [comment]
This might also be worth noting in the reform file -- that the warnings can be safely ignored,

**Comment by MaxGhenis** [comment]
@codykallen thanks for clarifying, makes sense.

**Comment by martinholmer** [comment]
@codykallen,  What do you think about this suggestion by @MattHJensen ?

@MattHJensen said a week ago in issue #1643:
> This might also be worth noting in the reform file -- that the warnings can be safely ignored,

**Comment by codykallen** [comment]
> This might also be worth noting in the reform file -- that the warnings can be safely ignored,

Is there a good place in a reform json to note that?

**Comment by martinholmer** [comment]
@codykallen asked in issue #1643:
> Is there a good place in a reform json to note that?

Both the TCJA reform files contain a line like this:
```
// - 3: _STD, _STD_Dep, _STD_Aged
```
Why not explain the lowering of `_STD_Dep` is not a problem at the end of that line or on the next line before 4?

**Comment by martinholmer** [comment]
Issue #1643 has been resolved by pull request #1763.
