### ISSUE TITLE
Updating growdiff

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/Tax-Calculator#1670]
Is there a way to change the growth path in the reform using Tax-Calculator, without using a json file? There used to be a simple `calc.growth.update_economic_growth(growth_dict)` capability, but this replaced by the current growfactors and growdiff code, and I'm not sure what the current version of this function is. 

I want to be able to pass lots of different alternative growth scenarios to different growth factors with different growdiff numbers for each year. This is extremely onerous to do in a json, and I can update the numbers much more quickly in a notebook. 

@MattHJensen @andersonfrailey @Amy-Xu @martinholmer @GoFroggyRun

**Comment by hdoupe** [comment]
I'm not very familiar with this part of Tax-Calculator.  However, I looked through the history of this function.  It looks like the key moments are:

1. [TC version 0.7.0](https://github.com/open-source-economics/Tax-Calculator/blob/0.7.0/taxcalc/growth.py#L63) -- TC still has `growth.update_economic_growth()`
2. [TC version 0.7.7](https://github.com/open-source-economics/Tax-Calculator/blob/0.7.7/taxcalc/growth.py#L70) -- `update_economic_growth` is renamed to `update_growth` in PR #1083 
3. [TC version 0.7.8](https://github.com/open-source-economics/Tax-Calculator/blob/0.7.8/taxcalc/growdiff.py#L59) -- In PR #1194, `growth.py` renamed to `growdiff.py`, `update_growth` is renamed to `update_growdiff`, and `update_growdiff` logic is changed to the logic that we have today

@codykallen Does the current [`growdiff.update_growdiff()`](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/growdiff.py#L61) meet your needs?

**Comment by codykallen** [comment]
@hdoupe, the command `calc.growdiff.update_growdiff()` produces an attribute error:
"'Calculator' object has no attribute 'growdiff'". How can I access the `growdiff.update_growth()` command and apply it to the calculator object?

**Comment by hdoupe** [comment]
There's an example that you can follow in [`tbi_utils.calculate()`](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/tbi/tbi_utils.py#L88).  You do something along these lines:

```
    # specify growdiff_baseline and growdiff_response
    growdiff_baseline = Growdiff()
    growdiff_response = Growdiff()
    growdiff_base_assumps = user_mods['growdiff_baseline']
    growdiff_resp_assumps = user_mods['growdiff_response']
    growdiff_baseline.update_growdiff(growdiff_base_assumps)
    growdiff_response.update_growdiff(growdiff_resp_assumps)

    # create pre-reform and post-reform Growfactors instances
    growfactors_pre = Growfactors()
    growdiff_baseline.apply_to(growfactors_pre)
    growfactors_post = Growfactors()
    growdiff_baseline.apply_to(growfactors_post)
    growdiff_response.apply_to(growfactors_post)

    recs1 = Records(data=copy.deepcopy(sample),
                        gfactors=growfactors_pre)
    
    policy1 = Policy(gfactors=growfactors_pre)
    calc1 = Calculator(policy=policy1, records=recs1, consumption=consump)


    recs2 = Records.cps_constructor(data=copy.deepcopy(sample),
                                        gfactors=growfactors_post)
    policy2 = Policy(gfactors=growfactors_post)
    policy_reform = user_mods['policy']
    policy2.implement_reform(policy_reform)
    calc2 = Calculator(policy=policy2, records=recs2,
                       consumption=consump, behavior=behv)

**Comment by hdoupe** [comment]
If you want to do a bunch of runs with different `Growdiff` objects, this may be a little cumbersome.

@martinholmer is there a better way to do this?

**Comment by martinholmer** [comment]
@codykallen,  You don't have to use JSON files at all with the Growdiff class (just like you don't have to use JSON to define a reform).   The code for the Growdiff update_growdiff  method is below.  Look at the tests to see how to use a Growdiff object to change assumptions.
```
    def update_growdiff(self, revisions):
        """
        Update growdiff default values using specified revisions, which is
        a dictionary containing one or more year:modification dictionaries.
        For example: {2014: {'_AWAGE': [0.01]}}.
        """
        precall_current_year = self.current_year
        self.set_default_vals()
        revision_years = sorted(list(revisions.keys()))
        for year in revision_years:
            self.set_year(year)
            self._update({year: revisions[year]})
        self.set_year(precall_current_year)
```

**Comment by codykallen** [comment]
@martinholmer, the tests show how to create GrowDiff objects and how to apply these to GrowFactors objects. Are there any examples to apply such changes to existing Calculator objects?

**Comment by martinholmer** [comment]
@codykallen asked:
> How can I access the growdiff.update_growth() command and apply it to the calculator object?
The Growdiff class does not have an `update_growth` method.  Look at the Tax-Calculator tests for examples of how to use the Growdiff class.

**Comment by martinholmer** [comment]
@codykallen asked:
> Are there any examples to apply such changes to existing Calculator objects?

No because that wouldn't make any sense.  Growfactors are an attribute of the Records class.
Here's the process:
1. specify a Growdiff object that has the differences between your assumptions and default assumptions
2. apply that growdiff object to a Growfactors object
3. use that Growfactors object (instead of the default one) when instantiating a Records object
4. use that Records object to specify a Calculator object

Or, instead of step 1 and step 2, you could write an `my_alternative_growfactor.json` file and pass its filename into the Growfactors constructor, if that would be easier.

Here's the signature of the Records class constructor:
```
    def __init__(self,
                 data='puf.csv',
                 exact_calculations=False,
                 gfactors=Growfactors(),
                 weights=PUF_WEIGHTS_FILENAME,
                 adjust_ratios=PUF_RATIOS_FILENAME,
                 start_year=PUFCSV_YEAR):
```

**Comment by codykallen** [comment]
@martinholmer, thanks for the specific instructions. Those appear to have worked.

**Comment by martinholmer** [comment]
@codykallen said in issue #1670:
> thanks for the specific instructions. Those appear to have worked.

Good.  This logic is a little round-about but it is necessary if someday we have macro growth model results feeding back to the micro model to affect earnings, property income, inflation, etc.

Closing #1670 now.  If there are other questions, please raise another issue.

**Comment by martinholmer** [comment]
@codykallen said in issue #1670 that he wanted to analyze many `alternative growth scenarios` but didn't say whether or not the `alternative growth scenarios` involved different rates of price inflation and/or different rates of wage growth.  I suggested a [set of instructions](https://github.com/open-source-economics/Tax-Calculator/issues/1670#issuecomment-345056296) that work correctly **only** if the `alternative growth scenarios` do not change the default values of the rates of price inflation or the rates of wage growth.

In the more general case, there is an additional step: the Policy class needs to be instantiated by passing it a Growfactor object that contains non-default values for the rates of price inflation or wage growth.  So, the more general instructions should read as follows (with the changes in bold):

1. specify a Growdiff object that has the differences between your assumptions and default assumptions
2. apply that growdiff object to a Growfactors object
3. use that Growfactors object (instead of the default one) when instantiating a Records object **and a Policy object**
4. use **those Policy and Records objects** to specify a Calculator object
