### ISSUE TITLE
AssertionError at Behavior.response when using new TCJA reform files

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1682]
The code from the training notebook breaks when using the three new TCJA reform files in the [reforms folder](https://github.com/open-source-economics/Tax-Calculator/tree/master/taxcalc/reforms). It works correctly when using a TCJA reform file from ~a week ago, as well as the `SampleReform.json` used by the notebook. I just updated taxcalc.

Specifically, the line

```
calc_response = Behavior.response(calc, calc_x)
```
yields an error ending with this:

> /usr/local/google/home/mghenis/miniconda2/lib/python2.7/site-packages/taxcalc/calculate.pyc in calc_all(self, zero_out_calc_vars)
    142         """
    143         # conducts static analysis of Calculator object for current_year
--> 144         assert self.records.current_year == self.policy.current_year
    145         self._calc_one_year(zero_out_calc_vars)
    146         BenefitSurtax(self)

> AssertionError: 

See [this notebook](https://github.com/MaxGhenis/taxcalc-notebooks/blob/master/taxcalc%20issues%20with%20latest%20TCJA%20reform%20files.ipynb) for all the cases.

This occurs both with the behavioral parameters @MattHJensen sent via email (which are used in the notebook), and the `SampleBehavior.json` used in the training notebook.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> The code from the training notebook breaks when using the three new TCJA reform files ...

Can you show us here the "code from the training notebook"?

There is only [one notebook](https://github.com/open-source-economics/Tax-Calculator/blob/master/read-the-docs/notebooks/10_Minutes_to_Tax-Calculator.ipynb) in the repository.  But it does not use the Behavior class, so I'm confused about which "training notebook" you're talking about.

You should probably look at the discussion in #1603 and #1604 about why we removed the old behavior notebook.  Maybe you have that obsolete notebook on your local computer.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> The code from the training notebook breaks when using the three new TCJA reform files ...
>  See this [notebook](https://github.com/MaxGhenis/taxcalc-notebooks/blob/master/taxcalc%20issues%20with%20latest%20TCJA%20reform%20files.ipynb) for all the cases.

I think you test function code is out-of-date since #1603 and #1604.  Here is a better way to write the test:
```
$ cat test.py
from taxcalc import *

def old_test(reform_path):
    # Initiate baseline calculator
    recs = Records.cps_constructor()
    calc = Calculator(records=recs, policy=Policy())
    # Advance and calculate.
    calc.advance_to_year(2018)
    calc.calc_all()
    # Initiate calculator to apply reforms to
    recs_x = Records.cps_constructor()
    calc_x = Calculator(records=recs_x, policy=Policy())
    reform = calc_x.read_json_param_objects(reform_path, 'test_Behavior.json')
    calc_x.policy.implement_reform(reform['policy'])
    calc_x.consumption.update_consumption(reform['consumption'])
    calc_x.advance_to_year(2018)
    calc_x.behavior.update_behavior(reform['behavior'])
    calc_response = Behavior.response(calc, calc_x)

def new_test(reform_path):
    # Initiate baseline calculator
    recs = Records.cps_constructor()
    calc = Calculator(records=recs, policy=Policy())
    # Advance and calculate.
    calc.advance_to_year(2018)
    calc.calc_all()
    # Initiate calculator to apply reforms to
    reform = Calculator.read_json_param_objects(reform_path,
                                                'test_Behavior.json')
    pol = Policy()
    pol.implement_reform(reform['policy'])
    con = Consumption()
    con.update_consumption(reform['consumption'])
    beh = Behavior()
    beh.update_behavior(reform['behavior'])
    calc_x = Calculator(records=recs, policy=pol,
                        consumption=con, behavior=beh)
    calc_x.advance_to_year(2018)
    calc_response = Behavior.response(calc, calc_x)

print "Starting new_test ..."
new_test('TCJA_House.json')
print "new_test finished without any error"
print "Starting old_test ..."
old_test('TCJA_House.json')
print "old_test finished without any error"
```
Here is what I get when I execute this script:
```
$  python test.py
Starting new_test ...
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2014.
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2014.
new_test finished without any error
Starting old_test ...
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2014.
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2014.
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    old_test('TCJA_House.json')
  File "test.py", line 18, in old_test
    calc_response = Behavior.response(calc, calc_x)
  File "/Users/mrh/anaconda2/lib/python2.7/site-packages/taxcalc/behavior.py", line 283, in response
    calc_y_behv.calc_all()
  File "/Users/mrh/anaconda2/lib/python2.7/site-packages/taxcalc/calculate.py", line 144, in calc_all
    assert self.records.current_year == self.policy.current_year
AssertionError
```
I didn't have `JCT_Behavior.json`, so I used this:
```
$ cat test_Behavior.json
{
    "consumption": {},
    "behavior": {"_BE_sub": {"2018": [0.3]}},
    "growdiff_baseline": {},
    "growdiff_response": {}
}
```
So, you can see that I reproduced your old test failure and showed how to rewrite the test function to conduct the analysis you want.

Sorry about the confusion, but I am not in the loop about "training notebooks".
Did you get something from Tax-Calculator developers that hasn't been corrected to work with taxcalc 0.13.2?

**Comment by MaxGhenis** [comment]
Thanks! This is the training notebook @MattHJensen sent me, created by @andersonfrailey: http://nbviewer.jupyter.org/github/andersonfrailey/Notebook-Uploads/blob/master/Training%20Doc.ipynb

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #1682:
> This is the training notebook @MattHJensen sent me, created by @andersonfrailey: http://nbviewer.jupyter.org/github/andersonfrailey/Notebook-Uploads/blob/master/Training%20Doc.ipynb

I've never seen that Python notebook and it is not part of the Tax-Calculator repository.

Programming style is a very personal thing, but in my view this "training notebook" is suggesting a programming style that is risky.  I guess that's why you've been having problems in #1682 and #1683 when following the "training notebook" style.   Here are a couple of style rules I'd suggest to reduce the chance of having problems when doing Python programming with the taxcalc package:

1.  Fully specify Consumption, Behavior, Records, and Policy objects **before** passing them to the Calculator class constructor.

2. After initializing a Calculator object, manipulate it using only Calculator class methods.

Following these two rules means avoiding the manipulation of a Calculator object's private internal objects (like `calc.records`, `calc.policy`, `calc.behavior`, or `calc.consumption`).

If you look back at the new test method I suggested in #1682, you'll see that it followed those two rules, while the old test method (that generated the AssertionError) did not follow those two rules.

And the problems you're having in #1683 appear to be caused by the same thing: not following these two rules.  I'll comment on that in more detail in #1683.

**Comment by MaxGhenis** [comment]
Thanks, this makes sense, and I'm glad to use the more OOP style you suggest.

Is [10_Minutes_to_Tax-Calculator.ipynb](https://github.com/open-source-economics/Tax-Calculator/blob/master/read-the-docs/notebooks/10_Minutes_to_Tax-Calculator.ipynb) the only official training-esque notebook then, or general usage documentation? Anderson's was helpful for using the CPS file and seeing the graphing functions in action.

**Comment by martinholmer** [comment]
@MaxGhenis said three weeks ago in issue #1682:
> Thanks, this makes sense, and I'm glad to use the more OOP style you suggest.
>
> Is `10_Minutes_to_Tax-Calculator.ipynb` the only official training-esque notebook then, or general usage documentation?  Anderson's was helpful for using the CPS file and seeing the graphing functions in action.

Since the discussion in #1682, Tax-Calculator has been revised to support a more object-oriented programming (OOP) style and we are just about ready to add the first edition of a *Cookbook of Tested Recipes for Python Programming with Tax-Calculator*, as you can see in pull request #1740.  Since your experience and questions in #1682 were the prime motivation for developing the Cookbook, we would appreciate any feedback you can give us on what's missing, what's unclear, etc.  If you have time to do that in the next week, just submit your comments to pull request #1740.  If we publish the first edition before you get a chance to review the PR, then just raise a new issue with your suggestions about how to improve the Cookbook.
