### ISSUE TITLE
Should the TCJA reforms set cpi_offset before 2018 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1687]
Based on the results in #1685 showing that cpi_offset does not affect results in the year that it is implemented but only the year after, I said:

> Notice how the cpi_offset reform doesn't change results in the year it is implemented. In the TCJA reform files, do you think we should implement it in 2016?

@evtedeschi3 said:

> Do you mean 2017 (so that it first takes effect in 2018)?

I said:
> I was looking at this: https://waysandmeansforms.house.gov/uploadedfiles/bill_text.pdf
> ![image](https://user-images.githubusercontent.com/8301092/33001913-f4d58fca-cd7e-11e7-96e9-5ccc0ee2e8dd.png)

@codykallen @GoFroggyRun @evtedeschi3 @martinholmer

**Comment by codykallen** [comment]
@MattHJensen, if we implement the cpi offset based on 2016 (as in the law), we would need to include a note or warning in the JSON that the chained CPI indexing is based on 2016, but did not affect revenues until 2018.

**Comment by martinholmer** [comment]
Perhaps this conversation could benefit from a comment about who CPI indexing works in Tax-Calculator.
What is described below is how policy parameter indexing has worked from the very beginning of the project.
Consider this code fragment from a test added just last week to the `test_policy.py` file:
```
    # check exact _II_em values for 2023, which are
    # equal to 2022 values indexed by 2022 inflation rates
    unchained_cpi = pol_bare.inflation_rates()[2022 - syr]
    assert pem_bare[2023 - syr] == round(pem * (1 + unchained_cpi), 2)
    chained_cpi = unchained_cpi + offset
    assert pem_with[2023 - syr] == round(pem * (1 + chained_cpi), 2)
```
So, when representing the TCJA bill, the key question is what is the first tax year in which the policy parameters will have been indexed by chained CPI.  If the answer is 2018, then `_cpi_offset` should become non-zero in 2017.
(I don't see how it could be 2017 because IRS has most of the forms of 2017 already prepared.)

@MattHJensen @codykallen @evtedeschi3

**Comment by martinholmer** [comment]
In the conversation about issue #1687, @martinholmer said:
> So, when representing the TCJA bill, the key question is what is the first tax year in which the policy parameters will have been indexed by chained CPI. If the answer is 2018, then _cpi_offset should become non-zero in 2017.

So, I guess given the recent changes in the TCJA reform files, the answer is that the reform is structured so 2018 tax policy parameters will be the first ones to be indexed using chained CPI.   

So, it would seem this issue has been resolved and needs to be closed.
