### ISSUE TITLE
Improve description of _PT_wages_active_income parameter 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#1692]
In #1686, I said:

> In my work on #1614, I found that _PT_wages_active_income does not affect results, even in the presence of a reduced _PT_rt7 compared to _II_rt7. The tests in this PR confirm that finding.
> 
> @codykallen, could you suggest how I can 'activate' the _PT_wages_active_income parameter so that switching it from false to true has an effect on results?

I believe this is a bug, so I am opening an issue and adding a bug label.

**Comment by MattHJensen** [comment]
As can be seen in https://github.com/open-source-economics/Tax-Calculator/pull/1686/commits/b28203b0d1801ac22c635c1c9bbe45d3cc4646cf, _PT_wages_active_income is activated in the presence of both a lower `_PT` rate schedule _and_ a reduction in `_PT_EligibleRate_active`. 

The relevant snippet in `functions.py` is copied below. The necessity of a `_PT_EligibleRate_active` to be less than 1 in order to activate `_PT_wages_active_income` can be seen by comparing the first and last line. 

    pt_active_gross = e00900 + e26270
    if (pt_active_gross > 0) and PT_wages_active_income:
        pt_active_gross = pt_active_gross + e00200
    pt_active = PT_EligibleRate_active * pt_active_gross
    pt_active = min(pt_active, e00900 + e26270)

**Comment by MattHJensen** [comment]
I believe the documentation for the PT_wages_active_income should be updated to reflect that wages will only be included in (positive) active business income when the amount of active business income eligible for lower PT rates is constrained. 

Alternatively, the `PT_wages_active_income` logic in functions.py should be updated to make this no longer the case. 

Does this all seem right to you, @codykallen?

**Comment by codykallen** [comment]
Here is a description for how we determine what income is eligible for the PT rates instead of the II rates. 

1. Determine what amount of passive business income is eligible. 
- Passive business income is defined as `e02000 - e26270`. 
- Under the Ryan-Brady plan (and the Tax-Calculator defaults), the eligible share of passive business income is zero. Under the House version of the TCJA, this is 1. 

2. For active business income, determine the base to which the eligibility rate will be applied. 
- In the Tax-Calculator defaults and the Ryan-Brady plan, this base is `e00900 + e26270`. 
- In the House TCJA, this is `e00900 + e26270 + e00200` if `e00900 + e26270 > 0` and zero otherwise. This is the first portion of the implementation of the rules associated with the `PT_wages_active_income` parameter. 

3. Apply the eligibility rate to determine what portion of the active business income base is eligible for the PT rates. 
- In the House TCJA, this eligibility rate is 30% (generally, with some additional rules that cannot be modeled). However, their rules include the caveat that the amount of active business income taxed on the PT schedule may not exceed active business income. 

As an example, if a filer has `e00900 = 0`, `e26270 = 100`, and `e00200 = 900`, the active business income base is 1000, but the amount of income actually eligible for the PT rates is only 100 instead of `1000 * 0.3 = 300`. 

Because `PT_wages_active_income` is intended to model the rules in the House TCJA, this parameter should only have an effect if the PT rates differ from the II rates and the eligibility rate `PT_EligibleRate_active < 1`.

**Comment by martinholmer** [comment]
@MattHJensen and @codykallen:
Has issue #1692 been resolved?  There has been no discussion for two weeks.

**Comment by codykallen** [comment]
@MattHJensen, is there anything you think should be changed? Or is this OK to close?

**Comment by martinholmer** [comment]
No more discussion during the eleven days since it was asked if there were any outstanding issues, so closing.
