### ISSUE TITLE
TaxBrain errors when uploading TCJA_Senate_120117.json

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1736]
Upon uploading [TCJA_Senate_120117.json](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/TCJA_Senate_120117.json) to TaxBrain [here](http://www.ospc.org/taxbrain/file/), I get a lot of errors:

> Some fields have errors. Values outside of suggested ranges will be accepted if they only cause warnings and are submitted again from this page.
× WARNING: value 0.6 > max value 0.5 for 2018
× WARNING: value 0.6 > max value 0.5 for 2019

And so on - there are 20-30 lines of errors like that.

I tried with a couple different behavior files, which work when passing an old TCJA_Senate.json reform file.

I was able to use TCJA_Senate_120117.json in the Python API without errors.

**Comment by martinholmer** [comment]
@MaxGhenis reported in issue #1736 many confusing warning messages when uploading the new `TCJA_Senate_120117.json` reform file to TaxBrain.  Here is what the beginning of the warnings looks like:

![screen shot 2017-12-08 at 9 27 24 pm](https://user-images.githubusercontent.com/12170745/33791894-b6fd8d6e-dc61-11e7-8929-7e5d9cd23b74.png)

When using the `tc` CLI to Tax-Calculator 0.13.2 on my local computer, I get this:
```
iMac2:OSPC mrh$ tc cps.csv 2018 --reform tax-calculator/taxcalc/reforms/TCJA_Senate_120117.json 
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2018.
PARAMETER VALUE WARNING(S):   (read documentation)
WARNING: 2018 _ID_Charity_crt_all value 0.6 > max value 0.5
WARNING: 2019 _ID_Charity_crt_all value 0.6 > max value 0.5
WARNING: 2020 _ID_Charity_crt_all value 0.6 > max value 0.5
WARNING: 2021 _ID_Charity_crt_all value 0.6 > max value 0.5
WARNING: 2022 _ID_Charity_crt_all value 0.6 > max value 0.5
WARNING: 2023 _ID_Charity_crt_all value 0.6 > max value 0.5
WARNING: 2024 _ID_Charity_crt_all value 0.6 > max value 0.5
WARNING: 2025 _ID_Charity_crt_all value 0.6 > max value 0.5
WARNING: 2018 _ID_Medical_frt value 0.075 < min value 0.1
WARNING: 2018 _ID_crt value 1.0 > max value 0.8
WARNING: 2019 _ID_crt value 1.0 > max value 0.8
WARNING: 2020 _ID_crt value 1.0 > max value 0.8
WARNING: 2021 _ID_crt value 1.0 > max value 0.8
WARNING: 2022 _ID_crt value 1.0 > max value 0.8
WARNING: 2023 _ID_crt value 1.0 > max value 0.8
WARNING: 2024 _ID_crt value 1.0 > max value 0.8
WARNING: 2025 _ID_crt value 1.0 > max value 0.8
WARNING: 2026 _STD_0 value 7655.0 < min value 7725.68
WARNING: 2026 _STD_1 value 15311.0 < min value 15551.32
WARNING: 2026 _STD_2 value 7655.0 < min value 7725.68
WARNING: 2026 _STD_3 value 11272.0 < min value 11422.83
WARNING: 2026 _STD_4 value 15311.0 < min value 15551.32
WARNING: 2027 _STD_0 value 7819.58 < min value 7913.5
WARNING: 2027 _STD_1 value 15640.19 < min value 15926.95
WARNING: 2027 _STD_2 value 7819.58 < min value 7913.5
WARNING: 2027 _STD_3 value 11514.35 < min value 11699.38
WARNING: 2027 _STD_4 value 15640.19 < min value 15926.95
CONTINUING WITH CALCULATIONS...

iMac2:OSPC mrh$ ls -l cps-18-TCJA_Senate_120117-#*
-rw-r--r--  1 mrh  staff     27971 Dec  8 21:31 cps-18-TCJA_Senate_120117-#-doc.text
-rw-r--r--  1 mrh  staff  17735794 Dec  8 21:31 cps-18-TCJA_Senate_120117-#.csv
```
So, there are couple of things going on here.

1. Some of the TCJA reform parameter values are outside what we used to think of as a "normal range", but the fact that the bill passed the Senate shows we need to revise our thinking about what a "normal range" is.  But these are just warnings, not errors.  Perhaps they should be rendered in yellow rather than red.

2. The warning messages on TaxBrain are so garbled that they are uninformative, and while it does say this, it is not clear enough that these are just warnings (not errors) and that clicking on the "Show Me the Results" button a second time will submit the run for execution.   I'm pretty sure that the TaxBrain developers were working this week on these problems with the TaxBrain file upload page.  Hopefully the next version of TaxBrain will be more clear.  Meanwhile, see if clicking a second time on the "Show Me the Results" button produces results for the reform.

**Comment by hdoupe** [comment]
@martinholmer said
>  Meanwhile, see if clicking a second time on the "Show Me the Results" button produces results for the reform.

@MaxGhenis This should work if there are only warning messages.  However, until OpenSourcePolicyCenter/PolicyBrain#762 is merged, you will have to re-upload your reform file.  The fix in 762 is already on the [test app](http://ospc-taxes7.herokuapp.com/taxbrain/) if you would like to test it out.  I would appreciate any feedback that you may have regarding the fix.

**Comment by martinholmer** [comment]
Close for the reasons given in #1738 in [this comment](https://github.com/open-source-economics/Tax-Calculator/issues/1738#issuecomment-350604698).
