### ISSUE TITLE
District of Columbia is missing in list of States

### ISSUE THREAD

**Issue by juliecrump** [open-source-economics/Tax-Calculator#1754]
The calculator is not usable for residents of the **District of Columbia** because DC is not an option in the dropdown list of states. 

http://www.cnn.com/2017/12/13/politics/calculate-americans-taxes-senate-reform-bill/index.html

**Comment by MattHJensen** [comment]
@juliecrump, thanks for your interest in Tax-Calculator. 

I presume CNN did not include D.C. because of a low number of tax filing units in D.C. and therefore sparse representation in the dataset that they used, especially when breaking things out the analysis such fine cells. 

This isn't really a constraint with Tax-Calculator, as Tax-Calculator would work just fine for someone with sufficient data on D.C. tax filing units. (See how to input data at the Tax-Calculator [user guide](http://open-source-economics.github.io/Tax-Calculator/).)

Building such a dataset is currently outside of the scope of the Tax-Calculator project (and also probably the [TaxData project](https://github.com/open-source-economics/taxdata), where a common input file for Tax-Calculator is developed). But if you have such a file or are interested in building one or figuring out how to access one (perhaps administrative data from the IRS or DC revenue service), please keep us all up to date! You can also contact me via email at matt.jensen@aei.org if you would like to talk more about this privately.

**Comment by MattHJensen** [comment]
Closing this issue as it is outside of the scope of Tax-Calculator. See response above.

**Comment by juliecrump** [comment]
@MattHJensen as it turns out, within the last few hours someone added District of Columbia to the dropdown! Check it out: http://www.cnn.com/2017/12/13/politics/calculate-americans-taxes-senate-reform-bill/index.html
