### ISSUE TITLE
Error when changing EITC age parameters

### ISSUE THREAD

**Issue by siervicul** [open-source-economics/Tax-Calculator#1809]
I'm using the TaxBrain interface, and when changing the minimum age from the default of 25 to 21, I get the error:

`ERROR: _EITC_MinEligAge value 21.0 is not integer for 2017 `

Even when I change it back to 25 to try to clear the error message, the error becomes:

`ERROR: _EITC_MinEligAge value 25.0 is not integer for 2017 `

**Comment by martinholmer** [comment]
@siervicul,  Thanks for the bug report in Tax-Calculator issue #1809.

I've move your bug report to the PolicyBrain repository as [issue 795](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/795) so that TaxBrain developers are aware of the problem you are encountering.

Given that the problem you report appears to be a TaxBrain problem, I'm going to close Tax-Calculator issue #1809.  Thanks again for the bug report.
