### ISSUE TITLE
Mislabeled variables in TaxBrain

### ISSUE THREAD

**Issue by james-r21** [open-source-economics/Tax-Calculator#1881]
Hi Tax-Calculator team,

It appears that variables are mislabeled on the distribution tables in current build of TaxBrain. For example, it is currently showing 98 billion itemizers, and it looks like the "AMT" column actually shows AGI.

Thanks!

**Comment by martinholmer** [comment]
@james-r21 said:
> It appears that variables are mislabeled on the distribution tables in current build of TaxBrain. For example, it is currently showing 98 billion itemizers, and it looks like the "AMT" column actually shows AGI.

Thanks for the bug report.  Yes, we are aware of that problem.  That bug was fixed in Tax-Calculator release 0.15.0 in pull request #1834.  You still see that problem in TaxBrain because the current version of TaxBrain is using Tax-Calculator release 0.14.2 as you can see below:

![screen shot 2018-02-15 at 11 37 07 am](https://user-images.githubusercontent.com/12170745/36268552-bfe6f3e8-1244-11e8-8204-1bfdcf2fd6cf.png)

We hope to have a new version of TaxBrain that incorporates this bug fix soon.

**Comment by hdoupe** [comment]
Thanks for the bug report @james-r21. The Tax-Calculator fix in 0.15.0 will be pushed to PolicyBrain as soon as OpenSourcePolicyCenter/PolicyBrain#822 is merged. The forthcoming release will contain major changes, and we will need all the reviewing help that we can get. If you are interested in helping out, then please look out for the pre-release announcement.

**Comment by martinholmer** [comment]
The Tax-Calculator bug reported in issue #1881 should be fixed in the current version of PolicyBrain (1.4.2), which is running Tax-Calculator 0.15.2.
