### ISSUE TITLE
Functions to calculate after-tax cash income

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1887]
With after-tax income now including benefits, it'd be helpful to be able to quantify after-tax cash income. This could be a useful comparison for UBI reforms, for example, in addition to comparing raw benefit value and utility.

I'm guessing this is already being considered given https://github.com/open-source-economics/taxdata/issues/148 but putting here for tracking.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> With after-tax income now including benefits, it'd be helpful to be able to quantify after-tax cash income. This could be a useful comparison for UBI reforms, for example, in addition to comparing raw benefit value and utility.

The C-TAM project --- as you have seen in your [comment on taxdata issue 148](https://github.com/open-source-economics/taxdata/issues/148#issuecomment-366392568) --- are a ways away from being able to provide us the accurate cash vs in-kind benefit breakdowns.  Meanwhile, you can make your own assumptions using the Consumption class `_BEN_*_value` parameters.  So, for example, to exclude all SNAP benefits from after-tax expanded income (because they are non-cash benefits), simply set `_BEN_snap_value` to zero.

**Comment by martinholmer** [comment]
No discussion of issue #1887 for the past two weeks.
