### ISSUE TITLE
Why is e00400 included in eitc_agi?

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1904]
`eitc_agi` is [defined as](https://github.com/open-source-economics/Tax-Calculator/blob/5b20973bbfe4834420a71f892976ec3555c3b52d/taxcalc/functions.py#L1158) `c00100 + e00400`, where `c00100` is AGI and `e00400` is "tax-exempt interest income" from 1040 line 8b, according to the [documentation](http://open-source-economics.github.io/Tax-Calculator/).

Is something off here? The [2017 EIC publication](https://www.irs.gov/pub/irs-pdf/p596.pdf) refers to 8b as combat pay, which aligns with the [2016 1040EZ](https://www.irs.gov/pub/irs-prior/i1040ez--2016.pdf), and there it seems like it should be counted for EITC. But the [2017 1040](https://www.irs.gov/pub/irs-pdf/i1040gi.pdf) refers to 8b as tax-exempt interest income.

The [`EITC` function](https://github.com/open-source-economics/Tax-Calculator/blob/5b20973bbfe4834420a71f892976ec3555c3b52d/taxcalc/functions.py#L1150) also includes `e00400` in `invinc`, so I wonder if this field is being used for two different things?

The above refers to tax units with `EITC_indiv = False`. For others, which use [`earned_p` and `earned_s`](https://github.com/open-source-economics/Tax-Calculator/blob/5b20973bbfe4834420a71f892976ec3555c3b52d/taxcalc/functions.py#L123), `e00400` does not appear to be part of the equation.

**Comment by martinholmer** [comment]
@MaxGhenis asked in issue #1904:
> `eitc_agi` is defined as c00100 + e00400, where c00100 is AGI and e00400 is "tax-exempt interest income" from 1040 line 8b, according to the documentation.
>
> Is something off here? The 2017 EIC publication refers to 8b as combat pay, which aligns with the 2016 1040EZ, and there it seems like it should be counted for EITC. But the 2017 1040 refers to 8b as tax-exempt interest income.

When you say "the 2017 EIC publication refers to 8b as combat pay", where exactly in that 41 page publication does it "refer to 8b as combat pay"?

**Comment by MaxGhenis** [comment]
> When you say "the 2017 EIC publication refers to 8b as combat pay", where exactly in that 41 page publication does it "refer to 8b as combat pay"?

@martinholmer You can search for "8b", where the first two instances refer to interest and the following four refer to combat pay. Specifically, the bottom of page 7:

> If you are using your 2016 earned income to figure your 2017 EIC and you elected to include nontaxable combat pay, be sure to use 2016 nontaxable combat pay and enter that amount on line 66b of Form 1040, line 42b of Form 1040A, or line 8b of Form 1040EZ.

; on page 19:

> If you are using your 2016 earned income to figure your 2017 EIC and you elected to include nontaxable combat pay, be sure to use 2016 nontaxable combat pay and enter that amount on line 66b of Form 1040, line 42b of Form 1040A, or line 8b of Form 1040EZ.

; and page 20:

> If you received nontaxable combat pay and are electing to include it in your earned income for the EIC, enter the amount on line 66b (Form 1040), line 42b (Form 1040A), or line 8b (Form 1040EZ). For details, see Nontaxable combat pay in this chapter.

Page 18 also seems to be referring to combat pay here:

> Otherwise, figure your earned income by using the worksheet in Step 5 of the Form 1040 instructions for lines 66a and 66b or the Form 1040A instructions for lines 42a and 42b, or the worksheet in Step 2 of the Form 1040EZ instructions for lines 8a and 8b.

**Comment by martinholmer** [comment]
@MaxGhenis, Thanks for the citations in the EIC instructions.

So, is the following correct?
- Form 1040 line 8b is nontaxable interest income (which we have in the Tax-Calculator `puf.csv` and `cps.csv.gz` input file).
-  Form 1040EZ line 8b is combat pay (which is a variable we do not have in those two input files).

If my understanding is correct, I don't see any problem.
Am I missing something or is my understanding of the Forms incorrect?

**Comment by MaxGhenis** [comment]
That seems right, but should nontaxable interest income be counted as part of `eitc_agi`? The EIC documentation suggests not.

I brought up combat pay in wondering whether the 8b's got mixed up in including `e00400` in `eitc_agi`.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> should nontaxable interest income be counted as part of `eitc_agi`? The EIC documentation suggests not.

Maybe there is a bug in the EITC logic.  Can you point me to the place in the "EIC documentation" that suggests nontaxable interest income should not be part of `eitc_agi`?

**Comment by MaxGhenis** [comment]
From page 7:

> Earned income includes all of the following types of income.
> 1. Wages, salaries, tips, and other taxable employee pay. Employee pay is earned income only if it is taxable. Nontaxable employee pay, such as certain dependent care benefits and adoption benefits, isn't earned income. But there is an exception for nontaxable combat pay, which you can choose to include in earned income, as explained later in this chapter.
> 2. Net earnings from self-employment.
> 3. Gross income received as a statutory employee.

[This IRS page on EITC](https://www.irs.gov/credits-deductions/individuals/earned-income-tax-credit/earned-income) also includes "Interest and dividends" under "Examples of Income that are *Not* Earned Income."

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #1904:
> From page 7:
>
>> Earned income includes all of the following types of income.
>>
>> 1. Wages, salaries, tips, and other taxable employee pay. Employee pay is earned income only if it is taxable. Nontaxable employee pay, such as certain dependent care benefits and adoption benefits, isn't earned income. But there is an exception for nontaxable combat pay, which you can choose to include in earned income, as explained later in this chapter.
>> 2. Net earnings from self-employment.
>> 3. Gross income received as a statutory employee.
>>
>> This IRS page on EITC also includes "Interest and dividends" under "Examples of Income that are Not Earned Income."

@MaxGhenis, thanks for the detailed citation from the IRS EIC instructions.  I think I understand your confusion.  Believe it or not, the IRS and the US tax code uses what some might view as Marxist terminology when referring to different types of income.  Labor income is referred to a "earned income", while capital (or property) income is referred to as "unearned income".  This may be surprising to you.  But if you understand the terms in that way, does the above citation make more sense?  

Nontaxable interest income would (using this terminology) never be included in "earned income" because it is not labor income but rather capital income.  That is why interest and dividends are (in IRS publications) "Examples of Income that are Not Earned Income."

**Comment by MaxGhenis** [comment]
Understood. I'm referring to "earned income" because that seems to be the
determinant of EITC, i.e. dictates where on the phase-in/out curve a tax
unit is, which looks to be defined in tc as `eitc_agi`. These documents
suggest that nontaxable interest income should not be counted as part of
EITC income. Do you see information stating it should be?

**Comment by martinholmer** [comment]
@MaxGhenis, the code that computes the EITC amount is as follows:
```
def EITCamount(phasein_rate, earnings, max_amount,
               phaseout_start, eitc_agi, phaseout_rate):
    """
    Return EITC amount given specified parameters
    """
    eitc = min(phasein_rate * earnings, max_amount)
    if earnings > phaseout_start or eitc_agi > phaseout_start:
        eitcx = max(0., (max_amount - phaseout_rate *
                         max(0., max(earnings, eitc_agi) - phaseout_start)))
        eitc = min(eitc, eitcx)
    return eitc
```
As you can see, the larger of `earnings` and `eitc_agi` is used to phase out the maximum EITC amount.
This is not easy to check against against IRS forms because IRS provides filers with a massive EIC table rather than having them compute the amount using a formula.

However, we have checked hundreds of thousands of randomly generated filing units to be sure that the tax results (including the EITC amount) generated by Tax-Calculator is the same as generated by [NBER's Internet TAXSIM](http://users.nber.org/~taxsim/taxsim9/).  See [this document](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/validation/README.md) for validation details.

Now there is always the possibility that both Tax-Calculator and TAXSIM contain the same bug.

If you think there is a bug, please provide a simple filing unit that can be processed by the `tc` command-line tool and show that the EITC amount generated by `tc` is more than a few dollars different from what you get filling out the IRS forms for that tax year.  This is the same bug-reporting process that has been used by TAXSIM for decades.  This is the kind of information we need to fix a bug; we need to be able to generate the incorrect tax results in a concrete case.

Meanwhile, I'm going to close this issue.  You can file your bug report in a new issue.

**Comment by MaxGhenis** [comment]
OK but `eitc_agi` is still used and includes `e00400` per the `EITC()` function. As you said there is no combat pay data, this means that nontaxable interest income is included. All EITC documents refer to nontaxable interest income only in the context of the interest threshold (currently $3,450).

Before verifying against taxsim, can someone answer the question posed in the title of this issue? I don't understand why the code is written as it is, and don't see documentation explaining it. It seems like a bug to me unless there's another document that mentions this differently or the data is defined differently.
