### ISSUE TITLE
nu18 increases unrealistically quickly over time (CPS)

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1927]
Tax-Calculator's projections for `nu18` (and `n24`, CTC-eligible children) are significantly faster than historical growth and Census projections for children under 18. See [this notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/nu18_n24_acs.ipynb) using CPS data. 

For example, tc's 2018 `nu18` estimate is 82.0M vs. 73.8M from Census. By 2025 the difference increases to 15M (90.1M vs 75.0M).

![download 9](https://user-images.githubusercontent.com/6076111/37580081-1ef046fa-2aff-11e8-9507-5ec83f6b2727.png)

I reported the higher initial level in https://github.com/open-source-economics/taxdata/issues/171.

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for the data analysis with respect to child counts in the CPS data that you reported in Tax-Calculator issue #1927.  As @andersonfrailey said in [this taxdata 171 comment](https://github.com/open-source-economics/taxdata/issues/171#issuecomment-374241747), these discrepancies are most likely caused by the methods used to generate the CPS weights.  So, I'm going to move the analysis you present here to taxdata issue 171, so your valuable analysis is all in one place.

**Comment by MaxGhenis** [comment]
To confirm then, the high growth rates also result from weights, and not the aging process? tc also projects significantly higher total population growth than the Census does:

![download 10](https://user-images.githubusercontent.com/6076111/37676076-254a9d1c-2c34-11e8-88ed-5f4f6dbc8df2.png)


That's from [this notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/pop_proj_tc_vs_census.ipynb) which plots all population totals that can be compared to Census. The difference is least significant for `n21`, but all groups grow faster than Census. Without knowing how the aging process works (is there documentation on that?), it doesn't seem like this would be explained solely by weights.
