### ISSUE TITLE
Total value of 2018 Child Tax Credit differs between CPS, PUF, and other sources

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1929]
This issue summarizes discrepancies between total values of the Child Tax Credit between the CPS, PUF, and other sources. In https://github.com/open-source-economics/taxdata/issues/157, @andersonfrailey said he has ideas on improving `n24` in the CPS which should help, so this just provides some context using tax year 2018:
* Using CPS data and Tax-Calculator ([notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/ctc/ctc_ubi.ipynb)), the estimated spend is $123.6B. This is the difference in after-tax income between a 2018 baseline and a reform that sets `_CTC_c` and `_DependentCredit_Child_c` to zero.
* Using PUF via TaxBrain to set the same parameters to zero (https://www.ospc.org/taxbrain/32874/), the total spend is $112.4B.
* Combining external reports suggests it could be about $120B: [this 2017 TPC report](http://www.taxpolicycenter.org/publications/refundable-credits-earned-income-tax-credit-and-child-tax-credit/full) estimated $52B, and [JCT estimated](https://www.jct.gov/publications.html?func=startdown&id=5053) that TCJA's non-SSN-related reforms would cost $68B starting in 2019 (the 2018 estimate of $29B does not capture the refundable portions). TaxBrain estimates only $0.3B difference between 2018 and 2019, so between these two it's likely $120B within a rounding error.

Based on this I think the CPS data is too high. The simplest explanation is that `n24` currently includes 17-year-olds when it should not (https://github.com/open-source-economics/taxdata/issues/164).

I'm also curious whether there might be an explanation for the $8B difference between TaxBrain PUF and TPC+JCT, or if there's another external benchmark (or if it's considered a reasonable tolerance).

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #1929:
> Using PUF via TaxBrain to set the same parameters to zero (https://www.ospc.org/taxbrain/32874/), the total spend is $112.4B.

I've tried to replicate this on my local computer using the tip of the master branch and the most up-to-date version of the `puf.csv` input file.  At the bottom, I show the Python script that generates the following:
```
$ ls -l puf.csv
-rw-r--r--@ 1 mrh  staff  54718219 Mar 19 13:45 puf.csv

$ python ctc-repeal.py
2018_CLP_itax_rev($B)= 1548.99
2018_CLP_ctc($B)= 86.33
2018_REF_itax_rev($B)= 1662.83
2018_REF_ctc($B)= 0.00
```
We would expect these results to be somewhat different from those generated by TaxBrain because TaxBrain results are "fuzzed" in order to safeguard the privacy of the individuals included in the IRS-SOI PUF.
The difference in total income tax revenue ($113.84 billion) is about what TaxBrain says ($112.4 billion).

But the total child tax credits (non-refundable plus refundable) is noticeably less at $86.33 billion.
Why? Probably because repealing the CTC allows taxpayers to use other nonrefundable credits that were crowded out by the CTC.

As to external comparisons, this is a very difficult issue because other groups are using different input data, analyzing different years, and computing different statistics.  For example, the TPC document you mention uses pre-TCJA as the baseline, while your TaxBrain estimates use TCJA as the baseline.  Given all the difficulties in making these kinds of cross-model comparisons, I'd say 114 is reasonably close to 120.  That's a five percent difference.

@MattHJensen

**Comment by martinholmer** [comment]
Here is the Python script that generated the results in [this comment](https://github.com/open-source-economics/Tax-Calculator/issues/1929#issuecomment-374318724):
```
from __future__ import print_function  # necessary only if using Python 2.7
from taxcalc import *

# using restricted puf.csv input data without any TaxBrain fuzzing of results
recs = Records()

# specify Calculator object for static analysis of current-law policy
pol = Policy()
calc1 = Calculator(policy=pol, records=recs, verbose=False)

cyr = 2018

# calculate aggregate current-law income tax liabilities for cyr
calc1.advance_to_year(cyr)
calc1.calc_all()
itax_rev1 = calc1.weighted_total('iitax')
ctc1 = calc1.weighted_total('c07220') + calc1.weighted_total('c11070')

# specify Calculator object for static analysis of reform policy
ctc_repeal = {
    cyr: {
        '_CTC_c': [0],
        '_DependentCredit_Child_c': [0]
    }
}
pol.implement_reform(ctc_repeal)
if pol.reform_errors:  # check for reform error messages
    print(pol.reform_errors)
    exit(1)
calc2 = Calculator(policy=pol, records=recs, verbose=False)

# calculate reform income tax liabilities for cyr
calc2.advance_to_year(cyr)
calc2.calc_all()
itax_rev2 = calc2.weighted_total('iitax')
ctc2 = calc2.weighted_total('c07220') + calc2.weighted_total('c11070')

# print total income tax revenue and CTC estimates for cyr
# (estimates in billons of dollars rounded to nearest hundredth of a billion)
print('{}_CLP_itax_rev($B)= {:.2f}'.format(cyr, itax_rev1 * 1e-9))
print('{}_CLP_ctc($B)= {:.2f}'.format(cyr, ctc1 * 1e-9))
print('{}_REF_itax_rev($B)= {:.2f}'.format(cyr, itax_rev2 * 1e-9))
print('{}_REF_ctc($B)= {:.2f}'.format(cyr, ctc2 * 1e-9))
```

**Comment by MaxGhenis** [comment]
Thanks @martinholmer, I didn't know about the fuzzing and it makes sense that these external comparisons might not be quite right because of different baselines.

The $124B CPS estimate exceeds the $114B PUF by 8.6%. This could be mostly explained by the inclusion of 17yos, but would you mind sharing the total `n24` in the PUF for 2018 to confirm? I'm mostly wanting to check the average CTC per `n24`, which the CPS currently has around $1,450.

**Comment by martinholmer** [comment]
@MaxGhenis asked:
> would you mind sharing the total `n24` in the PUF for 2018 to confirm? I'm mostly wanting to check the average CTC per `n24`, which the CPS currently has around $1,450

Here's the results:
```
$ cat ctc-n24.py
import taxcalc as tc
print 'Tax-Calculator version {}'.format(tc.__version__)
recs = tc.Records()  # use restricted puf.csv without any fuzzing of results
pol = tc.Policy()
calc = tc.Calculator(policy=pol, records=recs, verbose=False)
calc.advance_to_year(2018)
calc.calc_all()
ctc = calc.weighted_total('c07220') + calc.weighted_total('c11070')
print '2018 CTC ($b) = {:.3f}'.format(ctc * 1e-9)
n24 = calc.weighted_total('n24')
print '2018 n24 (#m) = {:.3f}'.format(n24 * 1e-6)

$ python ctc-n24.py 
Tax-Calculator version 0.17.0
2018 CTC ($b) = 86.331
2018 n24 (#m) = 70.250
```
So, the ratio is $1,229 when using PUF data.

But when I replace this line in the script:
```
recs = tc.Records()  # use restricted puf.csv without any fuzzing of results
```
with this line:
```
recs = tc.Records.cps_constructor()
```
I get these results:
```
iMac2:tax-calculator-data mrh$ python ctc-n24.py 
Tax-Calculator version 0.17.0
2018 CTC ($b) = 91.073
2018 n24 (#m) = 84.997
```
So, the ratio is $1,071 when using CPS data.

How did you get the $1,450 result?

**Comment by MaxGhenis** [comment]
$1,450 is the total change of $123B (not just the value of the credit
itself, since I want to account for the crowding-out you described) divided
by 85M total n24.

Using this approach, the average based on PUF would be $114B / 70M =
$1,600, 10% higher. Could this be the result of different coverage of low
earners who get partial amounts (i.e. CPS giving these more weight relative
to PUF)? Which dataset's result seems more likely?

**Comment by martinholmer** [comment]
@MaxGhenis said in #1929:
> $1,450 is the total change of $123.6B (not just the value of the credit itself, since I want to account for the crowding-out you described) divided by 85M total n24.
>
> Using this approach, the average based on PUF would be $114B / 70M = $1,600, 10% higher. 
>
> Could this be the result of different coverage of low earners who get partial amounts (i.e. CPS giving these more weight relative to PUF)? Which dataset's result seems more likely?

I have no idea.  If you really want to investigate this, here is what I'd suggest you do:

1. Download for 2015 the "All Returns:  Tax Liability, Tax Credits, and Tax Payments" table available from IRS-SOI on this [page](https://www.irs.gov/statistics/soi-tax-stats-individual-statistical-tables-by-size-of-adjusted-gross-income).

2. Use Tax-Calculator with CPS input data to estimate the number of filing units receiving a child tax credit and the dollar aggregate amount of the credit for 2015.

3. Compare the two sets of statistics.

Remember that with refundable credits, the basic estimate from Tax-Calculator is the amount of the refundable credit for which each filing unit is eligible.  Often the actual number who have no tax liability, but file in order to receive a refundable credit, is less.   This is so significant with the EITC, for example, that some people have tried to estimate EITC take-up probability functions and use them in their simulation model to get more realistic results.  Tax-Calculator does not have any refundable credit take-up probability functions; it just estimates the number who are eligible (including some that are eligible for a very small refundable credit and have no income tax liability).

**Comment by MaxGhenis** [comment]
Thanks @martinholmer, I'll look through the 2015 CPS data and compare to the [All Returns: Tax Liability, Tax Credits, and Tax Payments](https://docs.google.com/spreadsheets/d/1s8Z9E-n_eojbeXvEmCPCaSH7zZ4Nnsk-7VZeAGJjvFs/edit?usp=sharing) table.

Regarding take-up: [this report](http://www.csd.ca.gov/Portals/0/Documents/Reports/Updated%20Left%20on%20the%20Table%20Report.pdf) found that 20% of the EITC value was left on the table in California in 2012. I'm not aware of a similar analysis for CTC.

Also copying this info @codykallen shared via email:

> The CTC crowds out a handful of [nonrefundable credits](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/functions.py#L1488), namely the residential energy credit, general business credits (for owners of pass-through businesses), the prior year minimum tax credit, and “other” credits. Technically, it also could crowd out the Sch R credit, but that is only for the elderly and disabled (who presumably don’t claim the CTC).

I'll look into this as well. But if CTC is crowding out other credits, wouldn't we expect the total difference to be *smaller* than the value of the credits themselves? We observe the opposite.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> **I'll look into this as well.**  But if CTC is crowding out other credits, wouldn't we expect the total difference to be smaller than the value of the credits themselves? We observe the opposite.

Perhaps I'm all wrong about why the change in tax income tax liability is larger than the change in CTC when the CTC is repealed.  When your look into this matter, I suggest you deepen our understanding by using the `tc` tool to look at a few simple filling units of your own construction to see how much their CTC and income tax liability changes when the CTC is repealed.  That's the most direct way to figure out what kind of interaction(s) are causing the difference.  If you can't find the explanation, then maybe you've found a bug in Tax-Calculator.  We all look forward to your findings.

**Comment by martinholmer** [comment]
@MaxGhenis said in a comment on issue #1929:
> Also copying this info @codykallen shared via email:
>
>> The CTC crowds out a handful of nonrefundable credits, namely the residential energy credit, general business credits (for owners of pass-through businesses), the prior year minimum tax credit, and “other” credits. Technically, it also could crowd out the Sch R credit, but that is only for the elderly and disabled (who presumably don’t claim the CTC).
>
> I'll look into this as well. But if CTC is crowding out other credits, wouldn't we expect the total difference to be smaller than the value of the credits themselves? We observe the opposite.

Yes, @codykallen is correct, if under 2018 current law the CTC "crowds out" other nonrefundable credits, then a reform that repeals the CTC would "free up" other nonrefundable credits that are stacked after the CTC, and that would mean that the change in income tax liability would be less (not more) than the change in the CTC.

My earlier comments in issue #1929 were based on the mistaken impression that you were repealing the CTC (as the title of #1919 implies).  In reality you are repealing the CTC **and** the child dependent credit that became part of current-law policy in 2018.  My earlier tabulations failed to add in the change in the child dependent credit.  After correcting that mistake, the change in income tax liability is almost identical to change in the two credits, the Child Tax Credit (nonrefundable plus refundable) and the child-portion of the new dependent credit.  However, I did find three filing units in the `cps.csv` input file that experience an income tax liability change that is less than the change in the combined credits.  In all three cases, the discrepancy is caused by a "freeing up" of the Schedule R credit.  When I checked one of those three cases (`RECID=208975`), it looks like a seventy-five year-old grandparent taking care of three grandchildren, all of whom are under 17 years old.  In that case, under 2018 current law the CTC and child dependent credit "crowds out" the nonrefundable Schedule R credit and under the credit-repeal reform the small Schedule R credit is "freed up".   More details below.

Here are the results of the script shown at the bottom of this comment:
```
$ python noCTC.py
2018 CDTC1 ($b) = 132.138
2018 ITAX1 ($b) = 1129.231
2018 CDTC2 ($b) = 8.534
2018 ITAX2 ($b) = 1252.835
DIFFERNCES: recid, chgt chgc
169851 1741.87 1797.94
   diff,chgr= -56.07 -56.07
208975 2379.73 2440.23
   diff,chgr= -60.50 -60.50
358996 1720.56 1759.51
   diff,chgr= -38.94 -38.94
```
So, the change in income tax liability is $123.604 billion
and the change in the combined credits is $123.604 billion.
They are equal when rounded to the nearest million dollars because there are only three out of over 400,000 cases of non-equality and the three differences are small (less than one hundred dollars).
```
Here is the `noCTC.py` script:
```
from taxcalc import *
recs = Records.cps_constructor()  # use cps.csv input data
cyr = 2018

# static analysis of current-law policy
pol = Policy()
calc1 = Calculator(policy=pol, records=recs, verbose=False)
calc1.advance_to_year(cyr)
calc1.calc_all()
ctc1 = calc1.weighted_total('c07220') + calc1.weighted_total('c11070')
ctc1 += calc1.weighted_total('dep_credit')
itx1 = calc1.weighted_total('iitax')
print '{} CDTC1 ($b) = {:.3f}'.format(cyr, ctc1 * 1e-9)
print '{} ITAX1 ($b) = {:.3f}'.format(cyr, itx1 * 1e-9)

# static analysis of CTC repeal
ctc_repeal = {
    cyr: {
        '_CTC_c': [0],
        '_DependentCredit_Child_c': [0]
    }
}
pol.implement_reform(ctc_repeal)
if pol.reform_errors:
    print(pol.reform_errors)
    exit(1)
calc2 = Calculator(policy=pol, records=recs, verbose=False)
calc2.advance_to_year(cyr)
calc2.calc_all()
ctc2 = calc2.weighted_total('c07220') + calc2.weighted_total('c11070')
ctc2 += calc2.weighted_total('dep_credit')
itx2 = calc2.weighted_total('iitax')
print '{} CDTC2 ($b) = {:.3f}'.format(cyr, ctc2 * 1e-9)
print '{} ITAX2 ($b) = {:.3f}'.format(cyr, itx2 * 1e-9)

# ensure change in credits is same as change in tax liability for each funit
recid = calc1.array('RECID')
chgt = calc2.array('iitax') - calc1.array('iitax')
tc1 = calc1.array('c07220') + calc1.array('c11070') + calc1.array('dep_credit')
tc2 = calc2.array('c07220') + calc2.array('c11070') + calc2.array('dep_credit')
chgc = -(tc2 - tc1)
diff = chgt - chgc
chgr = calc1.array('c07200') - calc2.array('c07200')
eps = 0.01
if not np.allclose(chgt, chgc, atol=eps, rtol=0.0):
    print 'DIFFERNCES: recid, chgt chgc'
    for idx in range(len(chgt)):
        if diff[idx] > eps or diff[idx] < -eps:
            print '{} {:.2f} {:.2f}'.format(recid[idx], chgt[idx], chgc[idx])
            print '  diff,chgr= {:.2f} {:.2f}'.format(diff[idx], chgr[idx])
```

**Comment by MaxGhenis** [comment]
Thanks for looking into this @martinholmer! Sorry I didn't catch the dependent credit issue earlier, I've been associating the new child dependent credit with the CTC since people commonly say the CTC maxes out at $2,000, which IIUC includes this piece. I think the JCT also associates them in their budgetary impact analysis, though they also consider the non-child dependent credit which I'm excluding:

> Modification of child tax credit: $2,000 not indexed; refundable up to $1,400 indexed down to nearest $100 base year 2018; $2,500 refundability threshold not indexed; $500 other dependents not indexed; phase outs $200K/$400K not indexed

I compared the 2015 taxcalc CTCs with SOI ([notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/ctc_2015.ipynb)), and the overall totals match almost exactly: $53.0B vs $53.7B in SOI. taxcalc overestimates the normal CTC by 19% and underestimates the ACTC by 22%. The CTC overestimation is pretty constant across AGI groups, and the ACTC underestimation is focused on returns with <$40K AGI. Here's an overall distribution by AGI group, with the notebook having more:
![download 2](https://user-images.githubusercontent.com/6076111/37868870-20d098d8-2f6b-11e8-9bba-d4e6f6ad6734.png)

The largest overall discrepancy is among returns with AGI between $10K and $20K (~30%).

**Comment by martinholmer** [comment]
@MaxGhenis,  Where does issue #1929 stand?  There has been no discussion in almost two weeks.

**Comment by MaxGhenis** [comment]
I'd like to revisit the analysis after https://github.com/open-source-economics/taxdata/pull/172 (which fixes `n24`) is merged and released.

The 20%+ differences in some metrics and splits seems a bit concerning to me, but I realize this is getting into small slices. Would a longer-term solution be to add CTC targets?

Would it be worth someone running my [SOI comparison notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/ctc_2015.ipynb) using PUF?

**Comment by MaxGhenis** [comment]
Also the 2018 total is now $117.1B, vs. $113.8B in PUF (per @martinholmer's [comment](https://github.com/open-source-economics/Tax-Calculator/issues/1929#issuecomment-374318724)) and somewhere around $120B from external sources. That all seems fine to me at a high level, but the differences by income group and between the CTC and ACTC seems like it could justify additional targets.

**Comment by MattHJensen** [comment]
Would it make sense to close this issue and open a "help wanted" issue in TaxData to request the additional targeting? 

There are downsides to additional targeting, though. It could reduce our ability to hit pre-existing or future targets. Worse, it could throw off something important that isn't being targeted and that we aren't paying attention to. I do not currently have a recommendation for how we can balance these concerns in this specific case or in general.

**Comment by martinholmer** [comment]
@MattHJensen asked about issue #1929:
> Would it make sense to close this issue [#1929] and open a "help wanted" issue in TaxData to request the additional targeting?

I don't think that would be the best idea.  I think there are still significant issues about how to do the tabulations.   I've done some work of my own (which has been delayed by other taxdata development) that I am planning to add to this issue #1929.   In short, I'm not totally convinced that the child credit results are "off" so much that we need to change the taxdata weighting algorithms.

**Comment by martinholmer** [comment]
Issue #1929 discusses Tax-Calculator estimates from March-April for the child tax credit and compares them to SOI tabulations.  Now that Tax-Calculator 0.20.3 is using improved PUF and CPS data, I have looked at the tests to see how Tax-Calculator is doing in comparison to SOI tabulations for 2015 for the two largest credits: the EITC and the combined or full child tax credit (FCTC).  The table below shows information (expressed in billions of 2015 dollars) extracted from four test results files: `puf_agg_expect.txt`, `cps_agg_expect.txt`, `cmpi_puf_expect.txt`, and `cmpi_cps_expect.txt`.

||2015 PUF|2015 CPS|
|:------|----:|----:|
|itax before credits|1622.5|1313.1|
|all credits                |   171.6|    95.4|
|EITC                         |    66.4|    49.2|
|FCTC                       |    52.6|    45.5|

How do the EITC and FCTC estimates compare with the SOI tabulations for 2015?
* The PUF estimate for the EITC is 3% below the SOI amount and the FCTC is 2% below the SOI amount.
* The CPS estimate for the EITC is 28% below the SOI amount and the FCTC is 15% below the SOI amount.

So, in conclusion, the PUF estimates for the two largest income tax credits are reasonably close to the SOI tabulated amount for 2015, and the estimates by AGI category in the `cmpi_puf_expect.txt` file are not too far away from the SOI tabulated amounts.  However, the CPS estimates are well below the SOI tabulated amounts.  

So, the problem of underestimating income tax credits seems to be particular to the CPS input data.

It would be useful to continue this conversation in the taxdata repository, if people using the CPS data as input to Tax-Calculator are concerned about these credit underestimates.  Can it be that the CPS sample has relatively too few low-income filing units?  Whatever the cause of these CPS tax credit underestimates, they are data problems, not Tax-Calculator logic problems.  Given that, this Tax-Calculator issue is being closed.
