### ISSUE TITLE
How to repeal the entire Child Tax Credit, including its refundable component?

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#2022]
Continuing the discussion from https://github.com/open-source-economics/Tax-Calculator/issues/1938. Setting `_CTC_c=0` still leaves some tax units with positive values of `c11070` ("Child tax credit (refunded) from Form 8812"). This remains the case when setting `_ACTC_rt` and `_ACTC_Income_thd` to 0 (together and separately, and with `_CTC_c=0`).

What reform parameters are needed to repeal all parts of the CTC?

**Comment by martinholmer** [comment]
@MaxGhenis said in issue @2022:
> Continuing the discussion from #1938, setting  `_CTC_c` to zero still leaves some tax units with positive values of c11070 ("Child tax credit (refunded) from Form 8812"). This remains the case when setting `_ACTC_rt` and `_ACTC_Income_thd` to zero (together and separately, and with `_CTC_c`=0).

You haven't shown the work you did to reach this conclusion and I cannot replicate your results.

@MaxGhenis concluded by asking this question:
> What reform parameters are needed to repeal all parts of the CTC?

Here is the reform I used to make the sum of `c07220` (the nonrefundable CTC) and `c11070` (the refundable ACTC) equal to zero for all the filing units in the CPS input data file:
```
iMac:~ mrh$ tc --version
Tax-Calculator 0.20.1

iMac:~ mrh$ cat zerofctc.json 
// specify a 2018 reform that zeros out CTC (c07220) and ACTC (c11070)
{
    "policy": {
        "_CTC_c": {"2018": [0]}
    }
}

iMac:~ mrh$ tc cps.csv 2018 --dump --reform zerofctc.json 
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2018.
WARNING: Tax-Calculator packages for Python 2.7 will
         no longer be provided beginning in 2019
         because Pandas is stopping development for 2.7
SOLUTION: upgrade to Python 3.6 now

iMac:~ mrh$ ./work/OSPC/Tax-Calculator/csv_vars.sh cps-18-#-zerofctc-#.csv | grep -e c07220 -e c11070
31 c07220
42 c11070

iMac:~ mrh$ awk -F, 'BEGIN{n=0}NR>1&&($31+$42)>0{n++}END{print n}' cps-18-#-zerofctc-#.csv 
0
```
So, when I set the `_CTC_c` parameter to zero, nobody gets a positive CTC or a positive ACTC.

@MaxGhenis, I have no idea what you're doing (because you elected to be secretive about it), so I can't speculate on why you are confused about this.

**Comment by MaxGhenis** [comment]
Sorry, I mixed up my 2017-law and repeal reforms after pivoting my data in the [notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/ctc_2017_vs_repeal.ipynb) from the other issue. My mistake, thanks for checking it.
