### ISSUE TITLE
About changes to taxcalc/utils.py on tbi-outputs branch

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#2042]
@hdoupe, I notice that you're adding much needed descriptions of the output tables created in the `taxcalc/tbi/` code: the `RESULTS_TABLE_LABELS` and `RESULTS_TABLE_TAGS` dictionaries.

I have two questions about these changes:

1.  What does `_TAGS` refer to?  When I look at the contents, it seems as if something like `_INFO` would be a more meaningful name.  How would you describe in words the contents of this dictionary?

2.  Why are these two new dictionaries being added to `taxcalc/utils.py`?   They don't seem to be used anywhere but in the `taxcalc/tbi/` code, so why not put them there?

@lucassz

**Comment by lucassz** [comment]
I'm glad to be able to clarify this. I'll start by saying that there is nothing new about this content; it was present in TaxBrain in one form or another, but we think it would be more consistent to have it in Tax-Calculator.

1. The tags refer to characteristics of the table that can be filtered on from a list of options.
For instance, [the table selected by default](https://user-images.githubusercontent.com/4793515/43721372-954f3386-9960-11e8-81df-7c3574b07175.png) in the current version of TaxBrain would be tagged as a 'difference' table, one displaying 'combined' tax and income 'bins'. I don't know if 'tags' is the clearest way to describe this; would you prefer 'toggles'?

2. I don't think there would be an issue putting them in `tbi`, I think they were added to `utils.py` because that's where the other constants used by `tbi` were stored.

**Comment by hdoupe** [comment]
@martinholmer we haven't opened up a PR for this work yet because it's been somewhat exploratory in nature. Now, we are getting a better idea of what we think the API and output structure should look like. So, I think it's time to open a PR to get feedback and allow others to review. Per off-github discussion, @lucassz told me that he will be opening a Tax-Calculator WIP PR with these changes shortly.

**Comment by martinholmer** [comment]
@lucassz said:
> The tags refer to characteristics of the table that can be filtered on from a list of options.
For instance, [the table selected by default](https://user-images.githubusercontent.com/4793515/43721372-954f3386-9960-11e8-81df-7c3574b07175.png) in the current version of TaxBrain would be tagged as a 'difference' table, one displaying 'combined' tax and income 'bins'. I don't know if 'tags' is the clearest way to describe this; would you prefer 'toggles'?

Thanks for the explanation of the information in the `RESULTS_TABLE_TAGS` dictionary, but I still don't get where the term `_TAGS` comes from.  At a minimum you should preface the dictionary with a comment that describes its contents the way you explained them above.  The contents of the dictionary sounds like miscellaneous information about each table, so `_INFO` sounds more appropriate to me.  But that title says nothing about what information is included and why its useful.  So, no matter how you name the dictionary you need to add the comment.

@hdoupe

**Comment by martinholmer** [comment]
@hdoupe and @lucassz,  Now that I look more carefully at the contents of the `RESULTS_TABLE_LABELS` dictionary, it seems as if these are no row or column labels, but actually table TITLES, right?   If so, why not name the dictionary `RESULTS_TABLE_TITLES`?

**Comment by martinholmer** [comment]
@lucassz said:
> I don't think there would be an issue putting them in tbi, I think they were added to `utils.py` because that's where the other constants used by tbi were stored.

Yes, but those constants are used elsewhere in Tax-Calculator or by users writing Python scripts that import the taxcalc package (or at lease that is the intention).  But as far as I can see, the two new dictionaries are intended for `tbi` use only, right?  If there are any other table constants in `utils.py` that are used **only** by `tbi` code, then they should also be moved to an appropriate location in the `taxcalc/tbi` directory.

@hdoupe

**Comment by lucassz** [comment]
Thanks a lot for the feedback, @martinholmer. Should we close this issue and continue the discussion in the PR?

**Comment by martinholmer** [comment]
Closing issue #2042 now that pull request #2043 is open.
