### ISSUE TITLE
What is the best way to specify the start year?

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#207]
Currently each separate parameter in params.json has a start year. We also have a default value of 2013 in the Parameters constructor. Perhaps the correct thing to do is just have one `start_year` value in `params.json` and populate `Parameters._start_year` from that.

Also, we could have `calculator` factory function take a `start_year` and make sure that the Records and Parameters objects are incremented to that year if needed (or raise an exception if they are already too far in the future)

**Comment by MattHJensen** [comment]
I am :+1: on both paragraphs.

**Comment by martinholmer** [comment]
@talumbau and @MattHJensen had a brief conversation during April 2015 in issue #207 about setting the Tax-Calculator start_year.

Is this really a live issue?  It would seem as if in all the changes since April 2015 have settled the question about how best to specify the start_year.  If so, shouldn't issue #207 be closed?  If not, shouldn't a new issue (that reflects the current logic of Tax-Calculator) replace the old issue #207?

**Comment by talumbau** [comment]
Yep, this issue is stale. Closing.

**Comment by martinholmer** [comment]
@talumbau said:
> Yep, this issue is stale. Closing.

Thanks for the help.
