### ISSUE TITLE
Idea: pandas-oriented taxcalc interface

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#2072]
For complex analysis, I've found it necessary to extract `Calculator` results as a `DataFrame`, and then running analysis in `pandas`. This spurred me to draft a [**design document for a pandas-oriented Tax-Calculator interface**](https://docs.google.com/document/d/1x3wNOeuk3dXkqRI5waBDLNOojMcnXAdfNEJmwZfUb_s) a few months ago, to save steps for people who would use this analysis workflow.

More recently I've implemented some of these ideas in a [`taxcalc_helpers` package](https://github.com/MaxGhenis/taxcalc_helpers/blob/master/taxcalc_helpers/utils.py), e.g. the [`calc_df` function](https://github.com/MaxGhenis/taxcalc_helpers/blob/master/taxcalc_helpers/utils.py#L159) which produces a `DataFrame` with calculated metrics for each record given optional `Records`, `Policy`, and reform parameters (running `Calculate` and other `taxcalc` methods behind the scenes). Given this `DataFrame` result, other functions like [`add_weighted_quantiles`](https://github.com/MaxGhenis/taxcalc_helpers/blob/master/taxcalc_helpers/utils.py#L86) add percentiles and other quantiles for each record based on the provided metric, [`cash_income`](https://github.com/MaxGhenis/taxcalc_helpers/blob/master/taxcalc_helpers/utils.py#L207) calculates the estimated income after taxes and cash transfers for each record, etc. While initially built for complex analysis, I've now found this easier for all analysis.

The general idea is to leverage the centrality of `pandas` in data analysis while focusing the taxcalc interface on functions that generate useful `DataFrame`s. The design doc lists how some of the functions could work, compares this procedural design over OOP, and lists other expected benefits like ability to separate data aggregation from visualization.

Implementing this would be substantial, in either switching the interface or maintaining a second interface, but maybe there are elements that are useful without major changes. And if you disagree with the premise I can continue working on `taxcalc_helpers`.

I was thinking of developing this more before sharing with you all for feedback, but given the interface-polishing push following @andersonfrailey and @martinholmer's trip to India, it seemed like a good time to see what you think.

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for your ideas in comment #2072.  I think it is quite sensible for each Python user to develop a set of Python functions (in your case in the `taxcalc_helpers` package) that encapsulate Tax-Calculator code and return a post-calculation Pandas DataFrame for data analysis and/or visualization.  This is a very nice way to **use** the taxcalc package.  But it is very personal because each Python user of the taxcalc package is likely to be interested in using different kinds of input data (other than the CPS data, which is what `taxcalc_helpers` always uses) and different kinds of economic assumptions (which are absent from `taxcalc_helpers`) and different kinds of output variables (like marginal tax rates, which cannot be computed by the current version of `taxcalc_helpers`).  I'm not saying you should add all this; after all your analysis does not need all that.  I'm just saying that, one set of taxcalc-helper functions is not going to be suitable for all users.  Or, if it is, it will have become so complicated that it will cease to have much appeal to Python users of `taxcalc`.

So, by all means, keep developing your personal `taxcalc_helpers` capability to support your analysis needs.

On a completely different note, I was confused by your [design document](https://docs.google.com/document/d/1x3wNOeuk3dXkqRI5waBDLNOojMcnXAdfNEJmwZfUb_s).  Maybe I read that document wrong, but in it you seem to be suggesting the the Tax-Calculator itself should be converted from an object-oriented design that reads JSON parameter input into a functional design that reads CSV parameter input.  If I misunderstood what you're suggesting, then you can ignore the rest of this comment.

The object-oriented design of Tax-Calculator was settled on long before I got involved in the project.  As was the decision to make the classes data-driven by reading details from the JSON file associated with the class code.  (So, for example, the Policy class logic is in `policy.py` and its current-law data is in `policy_current_law.json`.)  The object-oriented design and JSON class data seem to work just fine.  At this stage of project development, it would take an enormous amount of work to implement the conversion you're suggesting.  I'm not sure it would work (particularly trying to shoehorn the JSON data into a CSV file) and I'm not sure what the benefits of the conversion would be.  But I'm pretty sure that the (time) cost of the conversion would be enormous.  So, I have a hard time envisioning this conversion as a task whose benefits would exceed its costs.

@MattHJensen @andersonfrailey @hdoupe

**Comment by MaxGhenis** [comment]
@martinholmer you read the design doc correctly: it proposes a pandas-oriented interface for taxcalc itself, as either a substitute or parallel to the current OOP interface. I recognize the substantial effort that this would involve, but I hope it can spur discussion over what the ideal interface would be if taxcalc were starting from scratch. Software projects often shoot to replace code every few years to clean out cruft and avoid status-quo bias.

As I said in the top-level comment, I'm happy to continue working on taxcalc_helpers, but I don't agree that each Python user should develop their own sets of functions; if operations are common shouldn't they be in the project? I'd be curious if the group you worked with in India is more familiar with pandas, for example. Perhaps some aspects of the design doc or taxcalc_helpers package could be incorporated based on general user feedback, of which this would be one small part.

Regarding JSON and CSVs, this is a small part of the proposal. The larger theme is for calculation functions to return `DataFrame`s, at which point using them as input could also be sensible but less important. I don't think there's any piece of the current taxcalc library that could be ported over in this way; for example, taxcalc_helpers also supports passing the PUF, and adding MTRs as columns to tax-unit-level results seems relatively straightforward.

**Comment by martinholmer** [comment]
@MaxGhenis said in Tax-Calculator issue #2072:
> As I said in the top-level comment, I'm happy to continue working on [my] `taxcalc_helpers` [functions], but I don't agree that each Python user should develop their own sets of functions; if operations are common shouldn't they be in the project? 

What's an example of a "common operation" that in your view should be incorporated into the Tax-Calculator source code?

**Comment by MaxGhenis** [comment]
I can't speak for others, but common operations in my workflow now include the functions I mentioned in https://github.com/open-source-economics/Tax-Calculator/issues/2072#issue-367264533, e.g.:
* `calc_df()` to simplify the multi-step `taxcalc` process, and add calculated metrics like `expanded_income_b` (`expanded_income * s006 / 1e9`), which can then be aggregated.
* `add_weighted_quantiles` to add different quantiles of features like `expanded_income` to the DataFrame.

In general, I suspect using the result of `Calculator.to_dataframe()` will be common among users versed in `pandas`, so adding functions to deal with it directly rather than through the `Calculator` object will be natural to these users.

**Comment by martinholmer** [comment]
@MaxGhenis said in Tax-Calculator issue #2072:
> I can't speak for others, but common operations in my workflow now include the functions I mentioned in [this 2072 comment](https://github.com/open-source-economics/Tax-Calculator/issues/2072#issue-367264533), e.g.:
>
> `calc_df()` to simplify the multi-step taxcalc process, and add calculated metrics like `expanded_income_b= (expanded_income * s006 / 1e9)`, which can then be aggregated.

Thanks for your suggestion.  After looking at your `calc_df()`, I can see why you want it to facilitate your own work which has a particular focus.  I just don't think it makes sense to add these kind of high-level functions to the Tax-Calculator repository.  Other users are focusing on other issues.

**Comment by MaxGhenis** [comment]
What's particular about my focus? My understanding is that cutting after-tax income by expanded income decile is pretty common (there's already functionality to do this, but lacks options in `calc_df`), and similarly cutting by quintile or percentile would be too (this isn't available in taxcalc today).

In any case I'll keep working on the separate package then, and post updates here.
