### ISSUE TITLE
remove _fixup variables

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#257]
The _fixup variables that control some logic in functions.py have been used in the past for debugging taxsim, but we have not used them on this project. Therefore I propose we remove them and remove any code that is conditioned on _fixup >=1.

**Comment by MattHJensen** [comment]
@martinholmer, I know you've thought about the _fixup variables recently. Do you believe removing them is still a good idea? (In which case I'll leave this issue open?)

**Comment by feenberg** [comment]
Because of the increase in blurring, there may be an increasingly good 
argument for something like fixup. I am inclined to think it shouldn't be 
a flag in the calculator, but rather we should create a variable in the 
data "sum of blurring and rounding errors" for AGI, Taxable Income, AMTI 
and Other Taxes. Then these would be routinely added when taxes were 
calculated, as though they were real data. That would increase the 
accuracy considerably.

While working with the PUF data to compare taxcalc.sas and taxsim9.for I 
find that there are lots of "impossible" records. That is, negative AGI 
but positive regular tax, etc, due to excessive blurring.

dan

**Comment by martinholmer** [comment]
Matt said:
> Martin, I know you've thought about the `_fixup` variables recently.  Do you believe removing them is still a good idea?  (In which case I'll leave this issue open?)

I just looked at all the `.py` files in the Tax-Calculator repository and didn't find any instances of `_fixup`.  Is the variable you and Dan are talking about named something else?

@MattHJensen @feenberg

**Comment by MattHJensen** [comment]
> I just looked at all the .py files in the Tax-Calculator repository and didn't find any instances of _fixup. Is the variable you and Dan are talking about named something else?

The `_fixup` variables must have been removed without me registering it. Closing this issue.
