### ISSUE TITLE
Make Records and Parameters objects immutable wrt Calculator objects

### ISSUE THREAD

**Issue by mmessick** [open-source-economics/Tax-Calculator#304]
Right now, when we assign two calculators the same records or parameters object, they do not create their own copies, but simply point to the original. This could end up causing errors when trying to manipulate parameters and records in the future when using multiple calculators.

Not really a priority, but something we should definitely be aware of.

**Comment by martinholmer** [comment]
Issue #304 has been (partially) resolved by merging pull request #843 into the master branch.  The resolution of this issue was to warn users against reusing Policy and Records objects in different Calculator objects in the docstring for the Calculator constructor.

The original issue --- no deepcopy of the Policy and Records objects passed to the Calculator constructor --- remains and is a potential pitfall for a new user who does not read the documentation of the Calculator constructor.

**Comment by zrisher** [comment]
In my opinion, there's more work we could do to truly resolve this issue. I think it would be useful to 

> Make Records and Parameters objects immutable wrt Calculator objects

or really w.r.t. anything that's reading from them for a few reasons:

* From a modeling perspective, it feels strange that the `Parameter` objects store the state in which some other object (the `Calculator`) is referencing them. Conceptually, a new user would think of a `Policy` set or `Growth` scheme as independent of the objects using them. This is why we need to document the requirement as implemented above - it's a little counter-intuitive.
* Copying the objects takes extra lines of code.
* If the parameter objects didn't mutate when being read, you could safely run multiple calculations concurrently sharing some parameters. The savings here would normally be very small, but when running thousands of calculations (e.g. the webapp) it may be more measurable.

I understand the parameter state (for parameters other than Records) was implemented to save calculation time and make referencing particular values simpler, but I believe that could be accomplished in other ways (e.g. calculating values for each year on "finalization". storing reference year in the calculator). This would be more complex for Records objects, since they are affected by tax liability calculation results.

In any case, I know that this suggestion would require significant refactoring efforts for a comparably low benefit. I'm not suggesting this should be a priority or even attempted soon - merely that it is an existing issue in my estimation that might be worth approaching at some point in the future.

@martinholmer @talumbau Feel free to correct my undoubtedly limited understanding of the way these are used.

**Comment by martinholmer** [comment]
@zrisher has recently made substantive comments on issue #304, so this issue is being re-opened to facilitate a continuing discussion.

**Comment by martinholmer** [comment]
Issue #304 has been resolved by pull requests #1582 and #1588.
