### ISSUE TITLE
notify user if source and conda install are conflicting

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#313]
from TJ: 

> I think there might be some way to say "these tests are failing with package taxcalc installed at path blah blah". If we could do that, then the user would see that he has the installed package and not the current source code he is working with.

**Comment by zrisher** [comment]
To clarify, the above quote refers to a user running taxcalc's tests. We would like taxcalc's test package to notify a running user of the path where it found the taxcalc package.

**Comment by martinholmer** [comment]
Given that hours of several team members were recently wasted because issue #313 has not been resolved, I'm wondering whether this enhancement should be given a higher priority that it seems to have now.  

I'd be happy to prepare a pull request but have no idea how to implement T.J.'s idea:
> I think there might be some way to say "these tests are failing with package taxcalc installed at path blah blah".  If we could do that, then the user would see that he has the installed package and not the current source code he is working with.

How does `py.test` know whether or not its using the taxcalc conda package or the taxcalc source code?

@MattHJensen @zrisher @PeterDSteinberg

**Comment by martinholmer** [comment]
@martinholmer asked on 14-Apr-2017:
> Given that hours of several team members were recently wasted because issue #313 has not been resolved, I'm wondering whether this enhancement should be given a higher priority that it seems to have now.
>
> I'd be happy to prepare a pull request but have no idea how to implement T.J.'s idea:
>
>> I think there might be some way to say "these tests are failing with package taxcalc installed at path blah blah". If we could do that, then the user would see that he has the installed package and not the current source code he is working with.
>
> How does py.test know whether or not its using the taxcalc conda package or the taxcalc source code?

I guess nobody knows how to do this, so I'm closing Tax-Calculator issue #313.
