### ISSUE TITLE
Distribute the Corporate Income Tax

### ISSUE THREAD

**Issue by mmessick** [open-source-economics/Tax-Calculator#315]
A proposal to distribute the corporate income tax to individuals in our tax microsimulation.

Summary of proposal:
- In the absence of this corporate income tax, both capital owners and wage earners would receive higher incomes; therefore, the Tax-Calculator imputes how much of the tax is borne by individuals, adding this to each individual’s expanded income measure.
- The OSPC allows a user to specify amount of burden allocated to normal and supernormal returns and then the user may allocate, separately, how the burden for normal and supernormal can be shifted to labor. 
- OSPC assumes that these percentages are achieved in the long run and that the long run is completed at the end of the ten-year budget window.

Documents referenced:
- [OTA](http://www.treasury.gov/resource-center/tax-policy/tax-analysis/Documents/OTA-T2012-05-Distributing-the-Corporate-Income-Tax-Methodology-May-2012.pdf)
- [TPC](http://www.taxpolicycenter.org/UploadedPDF/412651-Tax-Model-Corporate-Tax-Incidence.pdf)
- [JCT](https://www.jct.gov/publications.html?func=showdown&id=4528)
- [CBO](http://www.cbo.gov/sites/default/files/cbofiles/attachments/43373-AverageTaxRates_screen.pdf)

Discussed:
- issue #223
- PR #316 (full proposal can be found in this pr)
- PR #286  (implementation can be found in this pr)

**Comment by mmessick** [comment]
full documentation can be found in [this file](https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/docs/proposed_features/DistributingCorpIncTax.rst) in the master branch of this repo

**Comment by feenberg** [comment]
On Thu, 16 Jul 2015, mmessick wrote:

> 
> A proposal to distribute the corporate income tax to individuals in our tax
> microsimulation.
> 
> Summary of proposal:
>
>  *  In the absence of this corporate income tax, both capital owners and
>     wage earners would receive higher incomes; therefore, the Tax-Calculator
>     imputes how much of the tax is borne by individuals, adding this to each
>     individual’s expanded income measure.
>  *  The OSPC allows a user to specify amount of burden allocated to normal
>     and supernormal returns and then the user may allocate, separately, how
>     the burden for normal and supernormal can be shifted to labor.

Could you say more about how the normal and supernormal returns are 
identified in the PUF data?

dan feenberg

**Comment by mmessick** [comment]
normal returns identified by:
- dividends * .4 + net_capgains * .4 + self_employed_and_pt * .4 + bonds
- which converted to puf variables is:
    
    e00600 * .4 + (e23250 + e22250 + e23660) * .4 + (e09400 + e02000) * .4 + (e00400 + e00300)

supernormal returns identified by:
- dividends * .6 + net_capgains * .6
- which converted to puf variables is:

    e00600 * .6 + (e23250 + e22250 + e23660) * .6


Most of this was derived from TCP and JCT. I left out what I could not find in PUF, but those limitations are discussed in [this file](https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/docs/proposed_features/DistributingCorpIncTax.rst)

**Comment by yuying27** [comment]
I look through the post [here](https://github.com/open-source-economics/Tax-Calculator/blob/master/read-the-docs/proposed_features/DistributingCorpIncTax.rst). Rather than dividing 2.2 and 1.2. I think we should consider a different weighted average for above formula. Each components for normal or supernormal should multiply its aggregated value over aggregated normal or supernormal returns. This is because we need to consider the amount of each component. If dividends*.4 account for 80% of total normal return, it should be treated different from dividends*.4 account for 30%.
For example, the normal returns could be

(personal shares dividends * .4) * (aggregated dividends/aggregated normal returns) + 
(personal shares net_capgains * .4) * (aggregated net_capgains/aggregated normal returns) + 
(personal shares self_employed_and_pt * .4) * (aggregated self_employed_and_pt/aggregated normal returns) + 
(personal shares bonds * 1) * (aggregated bonds/aggregated normal returns)

where personal shares dividends is the dividends received over aggregated dividends, so the formula could be simplified:

(dividends amount * .4) /aggregated normal returns + 
(net_capgains amount* .4) /aggregated normal returns + 
(self_employed_and_pt amount* .4)/aggregated normal returns + 
(bonds amount* 1) /aggregated normal returns

= (dividends amount * .4 + net_capgains amount* .4  + self_employed_and_pt amount* .4 + bonds amount) /aggregated normal returns

where the aggregated normal returns = aggregated dividends amount * .4 + aggregated net_capgains amount* .4  + aggregated self_employed_and_pt amount* .4 + aggregated bonds

**Comment by martinholmer** [comment]
@yuying27 said in issue #315:
> I look through the post [here](https://github.com/open-source-economics/Tax-Calculator/blob/master/read-the-docs/proposed_features/DistributingCorpIncTax.rst). Rather than dividing 2.2 and 1.2.

I don't understand what you mean by `2.2` and `1.2`.  Can you explain what you mean?

**Comment by yuying27** [comment]
In the 3rd and 4th paragraph, Messick mentions the value is further divided into 1.2 (for supernormal) and 2.2 (for normal). My understanding of the 1.2 is a sum of 0.6 and 0.6, while 2.2 is a sum of 0.4, 0.4, 0.4 and 1.

**Comment by martinholmer** [comment]
@yuying27 said:
> @martinholmer In the 3rd and 4th paragraph, Messick mentions the value is further divided by 1.2 (for supernormal) and 2.2 (for normal). My understanding of the 1.2 is a sum of 0.6 and 0.6, while 2.2 is a sum of 0.4, 0.4, 0.4 and 1.

Oh, you mean:
> I look through the post here. Rather than dividing **BY** 2.2 and 1.2.

OK.

**Comment by yuying27** [comment]
@mmessick 

> Oh, you mean:
>>  I look through the post here. Rather than dividing BY 2.2 and 1.2.

Exactly, I updated my words to make it clearer.

**Comment by martinholmer** [comment]
This discussion is continued in issue #1515, and so, this two-year-old issue is being closed.
