### ISSUE TITLE
store meta data on "allowable values" in params.json for field validation in TaxBrain

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#331]
We should implement some javascript field validation for TaxBrain. E.g., you should not be able to decrease the standard deduction in TaxBrain. If you try to do so, you should get a description of why you can not.  (If the standard deduction falls, then more taxpayers would want to itemize, but we have not yet imputed itemized deductions to standard deduction filers so this switching will not occur accurately in our model; see #230). 

In order to implement field validation, I believe we need to have a means for specifying which values are allowed (and thereby which values are disallowed) for each parameter. `Params.json` is probably the best place to store this meta data. 

Therefore, I propose adding two new attributes to `params.json`. 

1. A string that specifies allowable ranges for the parameters. We will need to accommodate 
    * 'absolute' ranges, perhaps like, `"x >= 0"` 
    * 'relative' ranges, perhaps `"+"` for "can only be increased" or `"-"` (can only be decreased). 
    * combination of 'absolute' ranges and 'relative' ranges, perhaps `"+; 200 <  x <= 10000"` for, can only be increased, and must fall between 200 and 10,000, including 10,000 but not 200.  
2. A string that describes why the range outside of the allowed range is disallowed. 

Note:
1. Someone could make an argument that the param validation itself should occur in taxcalc; I tend to disagree since taxcalc should eventually be *mostly* data agnostic, and the param validation depends heavily on what data are used. That said, we will have default data, and having some meta-data in params.json that corresponds to the default data doesn't seem too crazy.
2. Maybe we should specify disallowed ranges instead of allowed ranges. 

Looking for feedback on the general idea as well as the very simple proposal for implementing this. Relevant to both the webapp and taxcalc, so copying a big group here. cc @martinholmer, @Amy-Xu, @amfarrell, @mistakevin, @talumbau, @zrisher, @feenberg

**Comment by Amy-Xu** [comment]
It seems like a good idea adding more attributes in params.json. In terms of implementation, I have a few concerns/questions.

1. How do you suggest adding ranges for parameters that depend on filing status/number of children? More universally, are we going to add the ranges for all the years available? If so, how to do that in a simple way?

2. What are the cases where one parameter has a allowed range but inside the range, it can only be increased/decreased? I thought for the Itemized/standard deduction case, the users cannot reduce standard deduction, but if they increase standard deduction, they certainly can decrease it to the previous level. 

3. If for now setting aside the issue of specifying ranges for multiple years, 'absolute' ranges, seem to me, will work in all cases. I would suggest a format of (a, b], where a is lower bound, b is upper bound, '(' is border exclusive, and ']' is border inclusive. This format is probably easier for machines to read, and easy to control the style as well. For the standard deduction case, the range would be lower bound at current law, inclusive, and upper bound  at infinity (sounds so good....:P).

**Comment by feenberg** [comment]
On Fri, 31 Jul 2015, Matt Jensen wrote:

> 
> We should implement some javascript field validation for TaxBrain. E.g., you
> should not be able to decrease the standard deduction in TaxBrain. If you
> try to do so, you should get a description of why you can not. (If the
> standard deduction falls, then more taxpayers would want to itemize, but we
> have not yet imputed itemized deductions to standard deduction filers so
> this switching will not occur accurately in our model).
> 
> In order to implement this, I believe we need to have a means for specifying
> which values are allowed (and thereby which values are disallowed) for each
> parameter. Params.json is probably the best place to store this meta data.
> 
> Therefore, I propose adding two new attributes to params.json.
>
>  1. A string that specifies allowable ranges for the parameters. We will
>     need to accommodate
>      +  'absolute' ranges, perhaps like, "x >= 0"
>      +  'relative' ranges, perhaps "+" for "can only be increased" or "-"
>         (can only be decreased).
>      +  combination of 'absolute' ranges and 'relative' ranges, perhaps "+;
>         200 < x <= 10000" for, can only be increased, and must fall between
>         200 and 10,000, including 10,000 but not 200.
>  2. A string that describes why the range outside of the allowed range is
>     disallowed.
> 
> Note:
> 1. Someone could make an argument that the param validation itself should
> occur in taxcalc; I tend to disagree since taxcalc should eventually be
> mostly data agnostic, and the param validation depends heavily on what data
> are used. That said, we will have default data, and having some meta-data in
> params.json that corresponds to the default data doesn't seem too crazy.
> 2. Maybe we should specify disallowed ranges instead of allowed ranges.
> 
> Looking for feedback on the general idea as well as the very simple proposal
> for implementing this. Relevant to both the webapp and taxcalc, so copying a
> big group here. cc @martinholmer, @Amy-Xu, @amfarrell, @mistakevin,
> @talumbau, @zrisher, @feenberg, @talumbau


I am not so sure that beyond the restriction on the standard deduction 
there are many more parameters that need to be restricted. You might think 
that of course the bracket rates must be positive and less than 100%, but 
why not a negative bracket - didn't Milton Friedman propose that? And 
there are some people in France that would like to test 110%. I wouldn't 
require haircuts to be positive, either. I have seen serious proposals 
that some deductions be at greater than 100%. So I don't think we should 
impose a lot of "reasonableness" restrictions. However, I do think we can 
require bracket thresholds to be monotonicly increasing. Probably there 
are a few others.

dan
617-863-0343

**Comment by zrisher** [comment]
I think there are two types of erroneous data cases we're really looking at here:

1. data that doesn't make sense for tax calculation
2. data that would cause the calculator to exhibit unexpected behavior

As @feenberg mentions above, the controls for case 1 should probably be fairly sparse and very carefully chosen. They also seem lower priority to me.

Case 2 is what originally motivated @MattHJensen to open this issue, and I believe it's the better place to initially concentrate. 

**Case 2 should be validated internally at least**
Matt, you mention that you don't believe the validation itself should be done by the tax calculator itself. In case 1 I would totally agree with you. In case 2, however, I think it makes the most sense to have this logic live primarily within the calculator. Those familiar with the inner workings of the calculator will always have a better understanding of what data will cause unexpected consequences, why it does, how important this restriction is to fix, and when circumstances will change. If a data restriction doesn't make sense from a pure modeling perspective, but instead exists due to the way it's implemented, I think it should live directly in the tax calculator, which should return errors and corresponding messages when such problems occur with passed parameters. You can include warnings about these conditions in params.json as well, of course.

**Validation info should be represented in JSON in its simplest form**
I think `{min: 200, max: 10000}` is *significantly* more usable by consumers of the API than `{valid_range: '200 < x <= 10000'}`. The former requires simple key matching and is easier to extend without breaking existing usage. The latter requires string parsing based on a predetermined format. It's not really native JSON, it's serialized data in JSON, which will need to be deserialized to use.

I believe the easiest way to figure out exactly how this should be expressed is to come up with a list of all the cases you really need to cover.

Just my 2 cents.

**Comment by MattHJensen** [comment]
> 2) data that would cause the calculator to exhibit unexpected behavior

@zrisher, thanks very much for reminding me of this second class of validation. 

To add some more background for others, this 'second case' would protect users who just flat out use the calculator incorrectly, for instance, they try to set a param value by entering `"1100"` instead of `1100`, or perhaps even `1,100` instead of `1100.` (note that the second case might be particularly difficult to protect given our method of accepting multi-year reforms). 

@zrisher said
> I believe the easiest way to figure out exactly how this should be expressed is to come up with a list of all the cases you really need to cover.

Especially given the feedback of @feenberg and @amy-xu, this seems like a very good way to proceed. @amy-xu and I can make a list early next week (particularly paying attention to subtleties that Amy pointed out) and then post it for the rest of your review. 

We will probably start with a more-thorough treatment of the 1st case (stuff that doesn't make sense given the limitations of the default tax data) since a) the credibility of the tax computation and not just usability depends on them, b) if we make any design changes to the calculator in the near future, then the requirements for case 2 might change.

**Comment by feenberg** [comment]
On Sat, 1 Aug 2015, Matt Jensen wrote:

>
>       2) data that would cause the calculator to exhibit unexpected behavior
> 
> @zrisher, thanks very much for reminding me of this second class of validation.
> 
> To add some more background for others, this 'second case' would protect users who
> just flat out use the calculator incorrectly, for instance, they try to set a param
> value by entering "1100" instead of 1100, or perhaps even 1,100 instead of 1100. (note
> that the second case might be particularly difficult to protect given our method of
> accepting multi-year reforms).

I don't suppose there is any reliable way to detect 1,100 intended as one 
number, but what message would the Python I/O conversion routine deliver 
for "1100"? Would it make sense to the user? Do we pipe standard error 
back to the user at all? I suggest we do so, as otherwise the error will 
be hidden in a log somewhere, or lost forever.

I still wonder what the list of parameter restrictions will look like. So 
far I can only think of:

  1) The standard deduction must not be decreased.
  2) Bracket thresholds must be non-negative and monotonically
     non-decreasing.
  3) Tuition, child-care and other dollar limits must be non-negative.

In my own work I generally use 1e20 for "infinity" (which is often 
necessary when a limit isn't desired). I suppose you could use "inf" or 
"max" but that is less intuitive.

I would oppose setting "reasonable" maximum values for things.

dan

**Comment by zrisher** [comment]
> users who just flat out use the calculator incorrectly, for instance, they try to set a param value by entering "1100" instead of 1100, or perhaps even 1,100 instead of 1100.

&

> I don't suppose there is any reliable way to detect 1,100 intended as one
number, but what message would the Python I/O conversion routine deliver
for "1100"? Would it make sense to the user?

We could parse string values in input arrays if they're used instead of integers as an added convenience. I.e. we expect something like `[7150, 7250, 7400]` for `_AMT_Child_em`, but if they send `["7150", "7250", "7400"]` or even `["7,150", "7250", "7,400"]` it's still usable. Just requires an extra parsing step. That would save you some communication time in the long run but clearly isn't a high priority feature. In general I shoot for making externally-available interfaces as dead-simple and intelligent as possible, because users will make eventually make every usage error you can think of. : )

**Comment by talumbau** [comment]
cc @mistakevin , mostly as an FYI

**Comment by Amy-Xu** [comment]
The simple JSON form of validation proposed by @zrisher makes a lot sense to me. To cover all the cases we need, we can have just two keys, min and max, but allow more options of values than only numbers. So far I think four options would be enough to cover all scenarios suggested by @feenberg. As we do not have any scenarios involving cross-year validation, it should be done year by year if our users defined a multiple year plan.

- default (current law value): under this option, user-defined parameter will be compared with current law value (the default value in webapp). If we set the min field as 'default', it means this parameter cannot be smaller than current law value. This option covers all the parameters that cannot be either increased or decreased. For example, the validation for standard deduction would be {min: default, max: null}.

- parameter variable: under this option, user-defined parameter will be compared with another parameter's value in the same year. For example, the second individual income tax bracket should be higher than the first bracket and lower than the third bracket. It can have the form of {min: II_brk1, max: II_brk3}. As long as we make the min of the first bracket at zero, then all brackets are sure to be non-negative.

- number: at the moment I assume border inclusive should be fine. Have not come across a case where inclusive border might generate problems.

- empty/null: this means we do not need to specify anything for this parameter on this key. If the max is null, then it mean this parameter can be increased to infinity. If min is null, then it can be decreased to negative infinity.

If this notation system works, I can add this node to every parameter we have in params.json. But not quiet sure how easy it is to implement the default & param variable options @talumbau. Or whether this indeed cover all possible scenarios in tax calculation @feenberg. Would love to hear feedback/suggestions/thoughts from everyone. :)

**Comment by talumbau** [comment]
It seems well defined to me. If the desire is to do the validation in Javascript (i.e. validate before the user clicks "submit"), it might be difficult to do before the end of September due to resourcing issues (unless @zrisher is free). If it is acceptable to validate on the back end (so, user clicks "submit", gets an error page saying what they did wrong, they hit the 'back' button to fix things) this work can go more quickly.

**Comment by feenberg** [comment]
On Tue, 15 Sep 2015, Amy Xu wrote:

> 
> The simple JSON form of validation proposed by @zrisher makes a lot sense to me. To
> cover all the cases we need, we can have just two keys, min and max, but allow more
> options of values than only numbers. So far I think four options would be enough to
> cover all scenarios suggested by @feenberg. As we do not have any scenarios involving
> cross-year validation, it should be done year by year if our users defined a multiple
> year plan.
>
>  * 
>
>     default (current law value): under this option, user-defined parameter will be
>     compared with current law value (the default value in webapp). If we set the min
>     field as 'default', it means this parameter cannot be smaller than current law
>     value. This option covers all the parameters that cannot be either increased or
>     decreased. For example, the validation for standard deduction would be {min:
>     default, max: null}.
>
>  * 
>
>     parameter variable: under this option, user-defined parameter will be compared
>     with another parameter's value in the same year. For example, the second
>     individual income tax bracket should be higher than the first bracket and lower
>     than the third bracket. It can have the form of {min: II_brk1, max: II_brk3}. As
>     long as we make the min of the first bracket at zero, then all brackets are sure
>     to be non-negative.
>

There is no economic reason that brackets must be monotonic and 
non-negative. Negative income taxes are well known, and Joe Stiglitz has a 
paper "proving" that the top rate should always be lower than the previous 
rate.

In general, I think we should avoid placing constraints on the parameters, 
unless it is very necessary. The cases I identified were cases where the 
PUF data was lacking the ability to simulate certain parameter changes. So 
the validation should not be part of the calculator, but should be 
optional in some way.


>  * 
>
>     number: at the moment I assume border inclusive should be fine. Have not come
>     across a case where inclusive border might generate problems.
>

Is this a reference to "open" or "closed" ranges? Otherwise I don't 
understand.

>  * 
>
>     empty/null: this means we do not need to specify anything for this parameter on
>     this key. If the max is null, then it mean this parameter can be increased to
>     infinity. If min is null, then it can be decreased to negative infinity.
> 
> If this notation system works, I can add this node to every parameter we have in
> params.json. But not quiet sure how easy it is to implement the default & param
> variable options @talumbau. Or whether this indeed cover all possible scenarios in tax
> calculation @feenberg. Would love to hear feedback/suggestions/thoughts from everyone.
> :)
> 
> —

I wonder if it is necessary to implement this for every parameter. I only 
identified a handful of cases where we needed to do anything at all - did 
I miss many? I was thinking we would add some HTML 5 to validate those 
fields and let the other fields be whatever the user wanted.

A question. What is the proposed response of the system to improper 
parameters? A pop-up? An error page returned?

dan

**Comment by feenberg** [comment]
On Tue, 15 Sep 2015, T.J. Alumbaugh wrote:

> 
> It seems well defined to me. If the desire is to do the validation in Javascript (i.e.
> validate before the user clicks "submit"), it might be difficult to do before the end
> of September due to resourcing issues (unless @zrisher is free). If it is acceptable
> to validate on the back end (so, user clicks "submit", gets an error page saying what
> they did wrong, they hit the 'back' button to fix things) this work can go more
> quickly.

I withdraw my suggestion that we use HTML 5 constraint validation - I 
forgot about multiple year fields. But back end validation seems fine to 
me.

Again, only a few fields need validation.

dan

**Comment by MattHJensen** [comment]
@Amy-Xu, could you post a few examples of the proposed notation to this issue. (We can discuss which parameters are being bound in the follow-on pull request that you open.)

--------
>A question. What is the proposed response of the system to improper
parameters? A pop-up? An error page returned?

If @zrisher has time to implement, I was thinking a JS popup combined with disallowance from the field of the out-of-range-numbers. Alternatively we could show a warning directly underneath where we show the default after a parameter has been changed:

![image](https://cloud.githubusercontent.com/assets/8301092/9904417/94ee3162-5c4b-11e5-86e7-ded474de0740.png).

This could be accompanied with an error page if anything is out of bounds. 

Backend validation would be ok too, as long as we provide a "edit parameters" link on the error page. 

------------


> I wonder if it is necessary to implement this for every parameter. 

We could add this parameter to params.json for the parameters that are bound, and then assume every other parameter can vary from negative infinity to positive infinity. It seems more clear through to explicitly state in params.json what the allowed range of every param is. 

---------------

>In general, I think we should avoid placing constraints on the parameters,
unless it is very necessary. 

Agreed

**Comment by Amy-Xu** [comment]
Here're a few examples. First three restrictions are due to lack of data.

- Standard Deduction cannot be decreased than current law value. **{min: default, max: null}**
- Itemized Deduction cannot be increased
    - Deduction for casualty loss; floor as a percent of AGI  **{min: null, max: default}**
    - Itemized deduction phaseout AGI start (Pease provision) **{min: null, max: default}**
    - Itemized deduction phaseout rate (Pease) **{min: default, max: null}**
- Maximum foreign earned income exclusion cannot be decreased **{min: default, max: null}**
- *(Optional)* Personal income tax brackets
    - Personal income tax bracket (upper threshold) 1  **{min: 0, max: II_brk2}** or **{min: null, max: II_brk2}**
    - Personal income tax bracket (upper threshold) 2  **{min: II_brk1, max: II_brk3}**
    - Personal income tax bracket (upper threshold) 3  **{min: II_brk2, max: II_brk4}**
    - Personal income tax bracket (upper threshold) 4  **{min: II_brk3, max: II_brk5}**
    - Personal income tax bracket (upper threshold) 5  **{min: II_brk4, max: II_brk6}**
    - Personal income tax bracket (upper threshold) 6  **{min: II_brk5, max: null}**

**Comment by feenberg** [comment]
On Wed, 16 Sep 2015, Amy Xu wrote:

> 
> Here're a few examples. First three restrictions are due to lack of data.
>
>  *  Standard Deduction cannot be decreased than current law value. {min:
>     default, max: null}

yes

>  *  Itemized Deduction cannot be increased
>      +  Deduction for casualty loss; floor as a percent of AGI {min: null,
>         max: default}

Is this logic backwards? If the floor is decreased it won't affect the 
output, since the data won't be there. But it can be increased, that would 
exclude some taxpayers that we have data for.

>      +  Itemized deduction phaseout AGI start (Pease provision) {min: null,
>         max: default}

Why? I believe we have the data to calculate the amount of the phaseout 
regardless of this parameter.

>      +  Itemized deduction phaseout rate (Pease) {min: default, max: null}
>  *  Maximum foreign earned income exclusion cannot be decreased {min:
>     default, max: null}

Again, why?

>  *  (Optional) Personal income tax brackets
>      +  Personal income tax bracket (upper threshold) 1 {min: 0, max:
>         II_brk2} or {min: null, max: II_brk2}
>      +  Personal income tax bracket (upper threshold) 2 {min: II_brk1, max:
>         II_brk3}
>      +  Personal income tax bracket (upper threshold) 3 {min: II_brk2, max:
>         II_brk4}
>      +  Personal income tax bracket (upper threshold) 4 {min: II_brk3, max:
>         II_brk5}
>      +  Personal income tax bracket (upper threshold) 5 {min: II_brk4, max:
>         II_brk6}
>      +  Personal income tax bracket (upper threshold) 6 {min: II_brk5, max:
>         null}
>

Thresholds must be ascending, yes.

dan

**Comment by Amy-Xu** [comment]
@feenberg The general argument for itemized deduction is that if itemized deduction increased, more people would switch to itemized deduction. Then we won't have the data to calculate itemized deduction for the previous standard deducters.

Specifically,
- Deduction for casualty loss; floor as a percent of AGI: if someone decreased the floor rate, it means more people would be eligible to deduct their casualty loss and the amount deducted would be higher as well. These people might previously be using standard deduction and we do not have information on their casualty loss.

- Similar arguments for Itemized Deduction limitation. To get reasonable results, users can make this limitation bigger but not smaller. Users should also make more people subject to this limitation than less. If the phaseout rate increased, ceteris paribus, itemizers generally takes a smaller limitation and end up with higher total itemized deduction. If the phaseout start's increased, people would have a higher itemized deduction because previously it was limited but not limited anymore.

@MattHJensen Please correct me if I misspoke about anything.

**Comment by zrisher** [comment]
Since Amy has a PR open now, I'll discuss this there: https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/355

**Comment by MattHJensen** [comment]
This is resolved. Closing.
