### ISSUE TITLE
It should be possible to create a Parameters object from a JSON filename

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#345]
The `from_file` class method has been removed. We need a replacement. Something like this would seem OK:

```
p = Parameters(json="myparams.json")
```

**Comment by martinholmer** [comment]
T.J. (@talumbau) said on 08-Sep-2015:
> The ```from_file``` class method has been removed [from the Policy class; formerly the Parameters class]. We need a replacement. Something like this would seem OK:
> ```p = Policy(json="myparams.json")```

Actually, the removal of this capability from the Policy class was an intentional move toward a safer Policy class.  We know, from all our testing and use of Tax-Calculator, that the ```current_law_policy.json``` is sensibly structured and contains reasonable parameter values.  If we were to follow your above suggestion and allow the reading in of **any** JSON file, the Policy class would have to add an extensive set of tests of the validity of the JSON file.  I don't think that should be the responsibility of the Policy class.

Any script that wants to use an alternative to ```current_law_policy.json``` can read the JSON file and generate a policy dictionary in a single command, and then that script can check that the dictionary is sensible before passing that dictionary to the Policy class constructor.

That seems like an easy thing to do and I haven't heard any complaints about the Policy constructor since you raised this issue on September 8th last year.  Do you want to continue this discussion?  Or would it make more sense to close this issue?

**Comment by talumbau** [comment]
This has been, much to my surprise, not a sought out use case. It was assumed towards the beginning of this project that this would be a typical method of creating Policy objects. Perhaps this speaks to the friendliness of Python syntax that folks are not all that interested in hand editing JSON files and passing them around. Let's close this since the user interface seems well in hand.

**Comment by martinholmer** [comment]
@talumbau said:
> This has been, much to my surprise, not a sought out use case. It was assumed towards the beginning of this project that this would be a typical method of creating Policy objects. Perhaps this speaks to the friendliness of Python syntax that folks are not all that interested in hand editing JSON files and passing them around. Let's close this since the user interface seems well in hand.

It is very difficult to know how things will work out at the very start of a project.  In my own projects, there are all kinds of neat features that nobody uses.
