### ISSUE TITLE
taxcalc incompatible with numpy=1.10.0-py27_0

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#381]
I tried updating numpy and had to reverse. When I upgrade to 1.10.0 I get these errors;
    
    def _blowup(self, year):
        >       self.e00200 *= self.BF.AWAGE[year]
        E       TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int64') with casting  rule 'same_kind'

**Comment by talumbau** [comment]
Digging in to this. We currently rely on this behavior in numpy, valid up to v1.9.x:

```
>>> import numpy as np
>>> x = np.array([1000], dtype='int64')
>>> x *= 1.02
>>> x
array([1020])
```
This is now gone in v1.10, see the release notes on 1.9 for Compatibility Notes:

http://docs.scipy.org/doc/numpy/release.html

In our case, we are fine with this "unsafe" behavior (at least, I'm assuming we are). A couple solutions occur to me:

- change the dtype for all `e`-codes to `float64' instead of its current `int64`.

- modify `_blowup` to use the "unsafe" casting behavior we have been using so that we preserve the arithmetic here ( int type * floating point type -> floating point result -> stored into int type)

@MattHJensen, do you have a preferred solution?

**Comment by MattHJensen** [comment]
My preferred solution would be to change the dtype for all e codes to float64 instead of int64

cc @martinholmer

**Comment by talumbau** [comment]
Just got this idea from reading the numpy docs. For all operations where we currently do:
```
 a *= b
```
we could do

```
np.multiply(a, b, out=a, casting='unsafe')
```

this would preserve the aliasing (which is the reason why we do the in-place `*=` operations) and it would allow us to keep the dtypes the same. This is essentially what we were doing before (just with different syntax). One way to think about it is that in numpy v1.10, the argument `casting` was changed to `same_kind` instead of `unsafe`.

**Comment by martinholmer** [comment]
@MattHJensen and T.J. (@talumbau),
Where do we stand on Tax-Calculator issue #381 and the use of numpy ```casting='unsafe'```?

I notice that as of 14-Feb-2016 the Records class does use ```casting='unsafe'```.  Is that wise?  The numpy developers presumably selected the adjective ```unsafe``` to send a not too subtle message.

Issue #589 identified the use of ```casting='unsafe'``` in parameters_base.py as the source of a serious bug in Tax-Calculator.  Pull request #590 eliminates that bug and the use of ```casting='unsafe'``` in the parameters_base class by changing parameters from int64 to float64 numpy arrays.

That was exactly what Matt suggested for the Records class in this issue on 19-Oct-2015:
> My preferred solution would be to change the dtype for all e codes to float64 instead of int64.

In light of the recently discovered problems associated with using ```casting='unsafe'```, do we want to reconsider the issue raised in Tax-Calculator issue #381?

**Comment by talumbau** [comment]
This issue (numpy compatibility) was resolved via https://github.com/open-source-economics/Tax-Calculator/pull/444. It basically used a workaround to deal with the casting issues described above. Now that #590 is in master, I think it would make sense to remove the `times_equal` helper function introduced  in #444 and rid the code base on any lines containing `casting=unsafe`. In other words, if we know that there is no desire to handle integer types any more, then from the point of data ingest forward we should just have `float64` and no casting will be necessary.
