### ISSUE TITLE
Try dropping the up and down calculations in MTR.

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#397]
@feenberg has suggested that we explore whether we can avoid all the kinks tax schedule for the purpose of our marginal tax rate calculations by first adding a penny to income and then calculating mtr using a 1 cent finite diff. If all of the kinks are at dollar levels, this would work and we could avoid doing the 'up' and 'down' calculation and potentially save ourselves two calculator runs.

**Comment by MattHJensen** [comment]
@feenberg,

> After Ohara is through with our data - is it still intergers?

Yes, but that is because we are unintentionally truncating everything. I guess when we reverse this truncation 'the add a penny to income first' idea won't work.

**Comment by feenberg** [comment]
On Thu, 15 Oct 2015, Matt Jensen wrote:

> 
> @feenberg,
>
>       After Ohara is through with our data - is it still intergers?
> 
> Yes, but that is because we are unintentionally truncating everything. I guess when we
> reverse this truncation 'the add a penny to income first' idea won't work.

Rather instead of "won't work" we should say "won't be needed".

dan

**Comment by MattHJensen** [comment]
Ohh, I see your point. That is good news.

**Comment by martinholmer** [comment]
@MattHJensen and Dan @feenberg,

Using the master branch at 3:00pm 03-Nov-2015, I tried a few variations in mtr-calculation methods.  I dropped the finite_diff from one dollar to one dime and then to one cent.  And I tried to use just the up values of mtr when the finite_diff was one cent.  Here is what I found using simtax.py on the a13.in sample of 100,000 filing units with no itemized expenses and no childcare expenses in 2013.  (Note that
output variable 7 is marginal federal income tax rate on taxpayer earnings and output variable 9 is marginal FICA tax rate on taxpayer earnings, and the results below are summary tabulations of the **differences** between Tax-Calculator and Internet-TAXSIM percentage marginal tax rates.  If there is no summary information, it means there were no differences for that output variable between the two sets of results.)
```
ONE-DOLLAR-FINITE-DIFF + UP/DOWN-LOGIC:
TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  7    193     14    -26.33 [23437]
      #big_vardiffs_with_big_inctax_diff=               30
```
```
ONE-DIME-FINITE-DIFF + UP/DOWN-LOGIC:
TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  7    190     11    -26.33 [23437]
      #big_vardiffs_with_big_inctax_diff=               30
```
```
ONE-CENT-FINITE-DIFF + UP/DOWN-LOGIC:
TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  7    190     11    -26.33 [23437]
      #big_vardiffs_with_big_inctax_diff=               30
```
```
ONE-CENT-FINITE-DIFF + UP-ONLY-LOGIC:
TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  7     38      7      6.25 [666]
      #big_vardiffs_with_big_inctax_diff=               30
TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  9     14      0      0.90 [2158]
```
Here is one of the 14 (out of 100,000) filing units with a 0.90 percentage point difference in the marginal FICA tax rate:
```
$ awk '$1==2158' a13.in
2158 2013 0 1 0 0 200000 0 10000 0 0 0 0 0 0 0 0 0 0 0 -2000 0
```
So, what do you think we should be doing to calculate marginal tax rates?

**Comment by feenberg** [comment]
I am flattered that you consider internet taxsim the oracle, but shouldn't 
you look at the reasons for the differences? It looks like there are are 
11 to 30 differences, depending on the finite difference chosen, so it 
shouldn't be impossible to track down the reason. There may be only one or 
two. Does the sample shown have something to do with an earnings split?

dan

**Comment by martinholmer** [comment]
Dan @feenberg said:
> It looks like there are are 11 to 30 differences, depending on the finite difference chosen ...

Not quite.  Consider the first set of results:
```
ONE-DOLLAR-FINITE-DIFF + UP/DOWN-LOGIC:
TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  7    193     14    -26.33 [23437]
      #big_vardiffs_with_big_inctax_diff=               30
```
There are 193 differences with 14 of them being only a basis point difference, leaving 179 "significant" differences in the marginal income tax rate.  The 30 on the second line refers the the number of filing units with more than one basis point difference in mtr who also have a more than one cent difference in income tax liability.  More on how to read the taxdiffs output is [here](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/validation/README.md#reading-tax-difference-results) if you are interested.

So, with this background, let's look again at the final set of results:
```
ONE-CENT-FINITE-DIFF + UP-ONLY-LOGIC:
TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  7     38      7      6.25 [666]
      #big_vardiffs_with_big_inctax_diff=               30
TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  9     14      0      0.90 [2158]
```
In this case, there are 7 one-basis-point differences in marginal income tax rates, leaving just 31 "significant" mtr differences (with the largest being 6.25 percentage points).  But the current version of the Tax-Calculator is getting 30 income tax liabilities wrong (Sean is working on fixing this bug).  Perhaps when he makes the fix, the mtr differences will go away, although there is nothing in the results above proving that the mtr differences are occurring in the same filing units are the tax liability differences.  I think we should wait to see how the marginal income tax rates look after we get the Tax-Calculator so that it generates no "significant" differences in income tax liabilities. On the other hand, the 14 "significant" marginal FICA tax rate differences are a manageable number and I will investigate those tomorrow.  Stay tuned.
cc @MattHJensen and Sean (@GoFroggyRun) Wang

**Comment by martinholmer** [comment]
Yesterday, I presented these 2013 marginal tax rate results:
```
ONE-CENT-FINITE-DIFF + UP-ONLY-LOGIC:
TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  7     38      7      6.25 [666]
      #big_vardiffs_with_big_inctax_diff=               30
TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  9     14      0      0.90 [2158]
```
I investigated the 14 (out of 100,000) Tax-Calculator-versus-Internet-TAXSIM differences in the marginal FICA tax rate (output variable 9).  All 14 of these filing units had no differences in FICA tax liabilities and had no differences in income tax liabilities.  And there were no differences in the marginal income tax rates for the 14 units.  In all 14 cases, Tax-Calculator produced a marginal FICA rate of 3.80 percent while Internet TAXSIM produced a marginal FICA tax rate of 2.90 percent.  The difference seems to be attributable to Internet TAXSIM using the additional Medicare tax rate (which is 0.90 percent of taxable wages) to calculate the FICA tax liability, but not using that rate to compute the marginal FICA tax rate.

Dan @feenberg, can you verify my inference about what is happening inside Internet TAXSIM?  If my inference is correct, is there any chance of Internet TAXSIM getting fixed with regards to this issue?

I'll look at the differences in marginal income tax rates after Sean (@GoFroggyRun) Wang's pull request #438 is merged into the master branch.

cc @MattHJensen

**Comment by feenberg** [comment]
On Wed, 4 Nov 2015, Martin Holmer wrote:

> 
> Yesterday, I presented these 2013 marginal tax rate results:
> 
> ONE-CENT-FINITE-DIFF + UP-ONLY-LOGIC:
> TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  7     38      7      6.25 [666]
>       #big_vardiffs_with_big_inctax_diff=               30
> TAXDIFF:ovar,#diffs,#1cdiffs,maxdiff[id]=  9     14      0      0.90 [2158]
> 
> I investigated the 14 (out of 100,000) Tax-Calculator-versus-Internet-TAXSIM differences in
> the marginal FICA tax rate (output variable 9). All 14 of these filing units had no
> differences in FICA tax liabilities and had no differences in income tax liabilities. And
> there were no differences in the marginal income tax rates for the 14 units. In all 14 cases,
> Tax-Calculator produced a marginal FICA rate of 3.80 percent while Internet TAXSIM produced a
> marginal FICA tax rate of 2.90 percent. The difference seems to be attributable to Internet
> TAXSIM using the additional Medicare tax rate (which is 0.90 percent of taxable wages) to
> calculate the FICA tax liability, but not using that rate to compute the marginal FICA tax
> rate.
> 
> Dan @feenberg, can you verify my inference about what is happening inside Internet TAXSIM? If
> my inference is correct, is there any chance of Internet TAXSIM getting fixed with regards to
> this issue?

The marginal tax rate from internet taxsim is an analytical calculation - 
not a finite difference, and it seems we forgot to update the calculation 
for the medicare tax on earned income. We will do that, possibly as early 
as tomorrow.

Within a few days I will have an updated taxcalc.sas with many 
improvements. I am still working on a dataset for comparing taxsim and 
taxcalc. There are many small details that have little effect on the 
aggregate but do generate curious differences. I want to fix nearly all of 
those before sending the file.

dan

**Comment by martinholmer** [comment]
Dan @feenberg said:
>  The marginal tax rate from internet taxsim is an analytical calculation --- not a finite difference, and it seems we forgot to update the calculation for the medicare tax on earned income. We will do that, possibly as early as tomorrow.

Great!  Thanks, Dan @feenberg

**Comment by martinholmer** [comment]
Dan @feenberg,
Subsequent checking shows that in the a13.in sample, many filing units have a marginal FICA tax rate of 3.80 percent in Internet TAXSIM results.  There are just a few that have 2.90 percent when it seems as if they should have 3.80 percent.  Just wanted to make clear that most of the high earners have the correct marginal FICA rate in the TAXSIM results I've looked at.

Thanks again for making these changes, which will make our OSPC validation efforts much easier.

**Comment by MattHJensen** [comment]
resolved with #441. Closing.

**Comment by feenberg** [comment]
I just posted an updated fortran calculator to taxsimftp and the website. 
See if the difference goes away.

Today we noticed that the subsidy rate for the EIC for parents of 3 or 
more children for 2013+ should be .45 rather than .40. I think this 
affects the Python calculator.

dan

**Comment by martinholmer** [comment]
Dan @feenberg said:
> Today we noticed that the subsidy rate for the EIC for parents of 3 or more children for 2013+ should be .45 rather than .40. I think this affects the Python calculator.

If you mean by the EITC "subsidy rate" the ```_EITC_rt``` parameter in the Tax-Calculator, then everything is OK because that parameter has a 2013+ value for 3+ kids of 0.45 in the ```current_law_policy.json``` file.

**Comment by martinholmer** [comment]
Dan @feenberg said:
> I just posted an updated fortran calculator to taxsimftp and the website.  See if the [marginal tax rate] difference goes away.

Dan,  Thanks for the quick work on this.

**Comment by martinholmer** [comment]
Dan @feenberg said on Friday, Nov 6:
>  I just posted an updated fortran calculator to taxsimftp and the website. See if the difference goes away.

When I use as Internet TAXSIM input the 600,000 filing units we are using in validation testing (in input samples a13, a14, b13, b14, c13, c14), I get **exactly** the same results as before Friday's update.  Could it be the case that whatever you changed in TAXSIM had no effects on these 600,000 filing units?  Or did I do something wrong?  Or did the NBER website not use the new version of TAXSIM for some reason?  I'm confused because I was expecting to see slightly different TAXSIM results.

cc @MattHJensen and Sean (@GoFroggyRun) Wang

**Comment by feenberg** [comment]
On Mon, 9 Nov 2015, Martin Holmer wrote:

> 
> Dan @feenberg said on Friday, Nov 6:
>
>       I just posted an updated fortran calculator to taxsimftp and the website.
>       See if the difference goes away.
> 
> When I use as Internet TAXSIM input the 600,000 filing units we are using in
> validation testing (in input samples a13, a14, b13, b14, c13, c14), I get exactly the
> same results as before Friday's update. Could it be the case that whatever you changed
> in TAXSIM had no effects on these 600,000 filing units? Or did I do something wrong?
> Or did the NBER website not use the new version of TAXSIM for some reason? I'm
> confused because I was expecting to see slightly different TAXSIM results.

It could be there is no change. Can you send me a single 22 variable 
example where you think there is a problem?

dan
