### ISSUE TITLE
compare any two output files based on any given input files. 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#427]
I believe the following testing capability would make it much easier to test against other full-fledged calculators like fortran TAXSIM, SAS Taxcalc, or calculators from other institutions:

a) accept two data files, one of inputs, and one of outputs. We should be able to accommodate any subset of input variables and any subset of output variables. The inputs should use the same variable names that we do and the outputs should use the same output names that we do. 

b) run tax-calculator using the input data, relying on the ability to accept any set of variables described in #425. 

c) Compare tax-calculator's output to the provided output dataset. Print all differences, allowing sorting by the size of the error or the sequential place in which they appear in functions.py. Sorting by the order in which variables appear in functions.py thiis extremely useful for debugging since errors propagate throughout the calculator.  

cc @martinholmer, @Amy-Xu, @GoFroggyRun, @feenberg.

Amy and Sean, you have the most experience testing against other full-fledged calculators in your work comparing tax-calculator to taxcalc. Do you think that this proposal would be helpful? Is there anything to make it better?

**Comment by MattHJensen** [comment]
An upcoming exercise for our core developer team will be testing tax-calculator vs taxcalc using a synthetic dataset for non-puf variables. I am thinking that this feature would make that project much easier.

**Comment by GoFroggyRun** [comment]
@MattHJensen This tool would definitely be helpful in terms of expanding our validation horizons. I do have, however, some comments on part c). What you have suggested are very efficient when validating against some other calculators like ours, where the code is available . But this might not be the case for those full-fledged but somewhat black-boxed ones. And I think having a option to present the differences similar to SIMTAX might be helpful. Instead of the complete differences file, we might want to present some error statistics for each variable. Also, like what @martinholmer have done in #420 , by allowing an optional tolerant parameter to restrict the detailed output within those "extremely bad" observations, it might be more straightforward for people to notice where the issue comes from given that, when debugging in such scenario, sometimes what we care about might be just a few observations, pairing with their respective outcomes in both calculators.

**Comment by martinholmer** [comment]
@MattHJensen,  what is the status of Tax-Calculator issue #427?  You raised this issue on October 29th of last year.  Given the development of the inctax.py script and the Records class over the past several months, we now have the capability of reading into Tax-Calculator any subset of the full ```puf.csv``` file and writing out tax liabilities, intermediate values (AGI, etc.), and marginal tax rates in Internet TAXSIM output format.  And two output files in this format can be easily compared using the taxdiffs script in the taxcalc/validation directory.

Does this current capability meet the needs you were thinking about last October when you raised issue #427?  If so, you could consider closing issue #427.  If not, perhaps you could close issue #427 anyway and open a new issue describing the missing capabilities you think would be useful to add.

**Comment by MattHJensen** [comment]
@GoFroggyRun, do you think it makes sense for us to close this issue and then open another issue if, during our comps with other calculators, we learn about any new comparison features that could be helpful?

**Comment by GoFroggyRun** [comment]
@MattHJensen 
Yes. I'm quite happy with all the current validation tools we have for the moment.

**Comment by MattHJensen** [comment]
> Yes. I'm quite happy with all the current validation tools we have for the moment.

Thanks Sean. Closing.

cc @martinholmer
