### ISSUE TITLE
What version of pylint and what settings are the correct settings for this project?

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#442]
This is an issue for anyone to advocate for the version and settings of pylint that should be enforced on this code base. As a start, I would advocate that `numpy` is exempt from pylint checking because the pylint warnings for numpy encourage non-idiomatic and potentially non-forward compatible code. This is discussed here:

http://stackoverflow.com/a/27943375/1631081

**Comment by martinholmer** [comment]
@talumbau said:
> the pylint warnings for numpy encourage non-idiomatic and potentially non-forward compatible code. This is discussed here:  http://stackoverflow.com/a/27943375/1631081

I looked over this StackOverflow discussion quickly and can see that pylint has problems understanding what one discussant called "numpy's abstruse method of methods import."  But I didn't see anything about how the pylint warnings would, as you said:
> encourage non-idiomatic and potentially non-forward compatible code.

Where is that discussion?  Can you given some examples or why, for example, using
```np.core.array(...)``` (rather than ```np.array(...)```) is going to cause problems down the road.  I'm inexperienced with Python, but am interested in learning more.

**Comment by talumbau** [comment]
There is no reason why `np.core.array` should continue to exist at any point in the future. The choice of what is exposed in `numpy` is intentional and considered. `np.core` is at the whim of the developer community. 

I'm interested in the list of reasons why we should use `np.core.xxx`'. The entire community has decided to use `np.xxx`. See e.g. this documentation:

http://docs.scipy.org/doc/scipy/reference/tutorial/general.html

As well as the uses of numpy in these projects:
https://github.com/scipy/scipy/search?utf8=%E2%9C%93&q=np
https://github.com/scikit-learn/scikit-learn/search?utf8=%E2%9C%93&q=np
https://github.com/scikit-image/scikit-image/search?utf8=%E2%9C%93&q=np
https://github.com/pydata/pandas/search?utf8=%E2%9C%93&q=np

These are exemplar projects in the numerical computing stack in Python. Why would we go contrary to these conventions? I don't understand how that makes the code quality better, regardless of what pylint outputs.

**Comment by martinholmer** [comment]
At this writing, the ```conda install pylint``` command installs version 1.4.2 of pylint.  All pylint versions 1.4+ have the ability to specify the following command-line option: ```--extension-pkg-whitelist=numpy```.  All the CODING-STYLE CHECKS comments at the top of some Tax-Calculator Python files have been revised to be like this (using policy.py as an example):
```
# pylint --disable=locally-disabled --extension-pkg-whitelist=numpy policy.py
```
The use of pylint is not mandatory in this project, but it can be a helpful tool when using an interpreted language that has no compiler to find coding errors or issue warnings about questionable code.

**Comment by martinholmer** [comment]
@talumbau,  Now that all the tax-calculator/taxcalc files that a pylint compliant are --- at your suggestion --- whitelisting the numpy package, are there any remaining issues in Tax-Calculator issue #442?  If there are additional issues, please identify them so that they can be discussed and acted upon.  If there are no additional issues, you should probably close issue #442 as it dates from November 4th of last year.

**Comment by talumbau** [comment]
I think we can open new issues on specific pylint topics in the future if necessary. closing.
