### ISSUE TITLE
Current year value after implement reform

### ISSUE THREAD

**Issue by Amy-Xu** [open-source-economics/Tax-Calculator#530]
When I was working on a script comparing our results with Budget options and Tax Expenditure, I found there was a weird behavior on our calculator, not sure whether it's a bug yet. Need more fresh eyes on this issue. Would appreciate any opinions and suggestions.

What I did was 1) setting up a calculator with start_year in 2013, 2) incrementing this calculator to 2015, and 3) implementing a reform starting in 2015. The results I got from this reform were very weird. I then realized this is due to an inconsistency of current years between policy and records class.

Somehow after the reform implementation, the policy current year was set to start year, which was 2013, and the records current year stayed at 2015. Thus, the calculator resulted in running with 2013 law and 2015 data, which of course wouldn't generate any sensible numbers. 

I was able to explain to myself why this happened after I read this [implement_reform](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/policy.py#L220) function again -- current year was set to start year explicitly. But I couldn't understand why we're doing this and why this makes sense for reform implementation on current master.

I attached a short checking script and output here as well. Would very appreciate any feedback on this issue. Thanks! @martinholmer @talumbau 

<img width="1015" alt="screen shot 2016-01-19 at 12 02 49 pm" src="https://cloud.githubusercontent.com/assets/10549597/12426476/d9bbc778-bea7-11e5-9c5b-90e5104cc065.png">
<img width="437" alt="screen shot 2016-01-19 at 12 03 00 pm" src="https://cloud.githubusercontent.com/assets/10549597/12426479/dbd50556-bea7-11e5-9712-3335bfcab815.png">

**Comment by talumbau** [comment]
I had this [same concern](https://github.com/open-source-economics/Tax-Calculator/pull/343#discussion_r38340367) with the new `implement_reform`. The idiom that one now has to use is "create the Calculator and Policy object, implement the reform for the desired years (which may be different from the current year for those objects), then advance to the desired year." This seemed counterintuitive to me, but that is currently the required usage style.

**Comment by martinholmer** [comment]
@Amy-Xu said among other things:
> When I was working on a script comparing our results with Budget options and Tax Expenditure, I found there was a weird behavior on our calculator, not sure whether it's a bug yet. Need more fresh eyes on this issue. Would appreciate any opinions and suggestions.
>
> What I did was (1) setting up a calculator with start_year in 2013, (2) incrementing this calculator to 2015, and (3) implementing a reform starting in 2015. The results I got from this reform were very weird. I then realized this is due to an inconsistency of current years between policy and records class.

As you realized after reading the documentation of the ```Policy.implement_reform``` method, your Python script misused the Policy class.  You **always** implement the reform immediately after instantiating a Policy object and **before** passing the Policy object to the Calculator constructor method.

So, in your case, the following should work just fine:
```
records2 = Records(...)
policy2 = Policy(start_year=2013)
reform = {2015: { ... } }
policy2.implement_reform(reform)
behavior2 = Behavior()
calc2 = Calculator(records=records2, policy=policy2, behavior=behavior2)
calc2.increment_year()
calc2.increment_year()
...
```

Please confirm that this usage of the Policy class works as you expect.

cc @MattHJensen @talumbau @GoFroggyRun

**Comment by Amy-Xu** [comment]
@martinholmer I see. Yup that would indeed solve the problem. Let me take one step ahead and ask this: why are we setting the current year to start year in this function? The reason I'm asking is that my script would run about 30 reforms (starting from 2015) and compare the results with baseline. If increment_year needs to be done after implement_reform, I'll have to include this increment_year in the for loop and run an extra 60 times of this increment_year() in total. Even though this is not extremely time-consuming, my script, or any other usage doing similar comparison, would be a bit better off if increment_year could be done before implement_reform. Do you think there's possibly an alternative to adjust this part?

**Comment by martinholmer** [comment]
Amy said:
> @martinholmer I see. Yup that would indeed solve the problem. Let me take one step ahead and ask this: why are we setting the current year to start year in this function? The reason I'm asking is that my script would run about 30 reforms (starting from 2015) and compare the results with baseline. If increment_year needs to be done after implement_reform, I'll have to include this increment_year in the for loop and run an extra 60 times of this increment_year() in total. Even though this is not extremely time-consuming, my script, or any other usage doing similar comparison, would be a bit better off if increment_year could be done before implement_reform. Do you think there's possibly an alternative to adjust this part?

The reason the Policy.implement_reform method works the way it does is that I couldn't see how to easily handle multiple-year reforms in any other way.  This issue doesn't come up in your use case, but what if there were reforms after 2015?  We would have to move the Policy object forward to the last year of the reforms (say, 2020) in order to implement those reforms.  So, in that case, should we just leave the Policy object in 2020?  That wouldn't work in your case.  So, the decision was to implement the whole (possibly multiple-year) reform and then reset the Policy object's current year to its start year.

These changes were made many months ago because the old Policy class (which was  then called the Parameters class) did not correctly implement multiple-year reforms.  So, perhaps the current version is not intuitive to some, but at least it works correctly.  To me, the current usage idiom is intuitive because I think of a Policy object as a standalone object that represents current-law policy (as generated by the Policy constructor) or some alternative policy (as generated by the Policy constructor plus a call to the implement_reform method), all of which is done at the start when instantiating a Policy object.

Feel free to develop a pull request that passes all the pytests and somehow avoids the problems you see.

The problem you identify seems to be an efficiency issue: repeating the blowup of the records from 2009 to 2015 for each of many policy reforms.  Is that correct?  Is it possible to do these years of blowup by calling the Records.increment_year method on the Records object **before** passing that Records object to the Calculator constructor?  If that would work, then you need to blowup the Records object from 2009 to 2015 only once.  Is that correct, or am I missing something?  I admit I haven't tried this out, but you are the one worrying about the execution time of your script.  I'd be interested in knowing if my suggestion works or if it is a bad idea.

@Amy-Xu @MattHJensen @talumbau @feenberg @GoFroggyRun

**Comment by Amy-Xu** [comment]
>The problem you identify seems to be an efficiency issue: repeating the blowup of the records from 2009 to 2015 for each of many policy reforms. Is that correct? 

Not exactly. What I meant was blow up both records and policy from 2013 to 2015 repeatedly, even tho it's not accurate to use the term 'blow up' for policy. Indeed I agree -- policy should be a standalone object for current law, but it shouldn't be completely standalone in the way that if the current year of policy is not the same as records, the results won't make sense in most scenarios. 

In my current script, blowup from 09 to 13 only needs to be done once for both baseline and reform calculators when they are built, because start_year's set to 2013. But taking the reform calculator from 13 to 15 would be done repeatedly in the loop using current master version, because we need to put this part after implement_reform.

I was thinking an easy fix would be just storing the original 'current_year' of policy, doing the multi-year reform as now, and then setting policy to that original current year instead of 'start_year' at the end of implement reform. This will solve my problem, but I probably should do more testing cases than that. Do you think it will be enough if I just re-do the example in documentation of implement_reform for testing?

**Comment by MattHJensen** [comment]
> Looks awesome to me. This is what I have as a temp fix on my local machine as well. The test's great!
Thanks Martin! Merging.

Based on Amy's comment to #533, I'm closing this.
