### ISSUE TITLE
Remove the `times_equal` helper function and rid the code base of `casting=unsafe`

### ISSUE THREAD

**Issue by talumbau** [open-source-economics/Tax-Calculator#596]
See discussion on #381.

**Comment by martinholmer** [comment]
T.J. (@talumbau),
As I think more about this issue, there seem to be some variables in the Records input file (e.g., ```puf.csv```) that are best left as integers after they are read into the Records class.  The main example of this kind of variable is MARS.  I guess any move away from the current int64 dtype for Records input would require some variables to remain int64 and others (that are involved in ```times_equal``` calls) to be converted to float64 dtype.

**Comment by feenberg** [comment]
On Mon, 15 Feb 2016, Martin Holmer wrote:

> 
> T.J. (@talumbau),
> As I think more about this issue, there seem to be some variables in the Records input
> file (e.g., puf.csv) that are best left as integers after they are read into the
> Records class. The main example of this kind of variable is MARS. I guess any move
> away from the current int64 dtype for Records input would require some variables to
> remain int64 and others (that are involved in times_equal calls) to be converted to
> float64 dtype.
>

In taxsim we have always stored MARS as a real - and have not noticed any 
problems. If it  makes things easier to have everything in one type, I 
wouldn't worry about MARS. At the beginning of the program we create an 
integer out of the stored value, and use it as an array index, since 
Fortran doesn't allow real array indicies. It works fine.

dan

**Comment by martinholmer** [comment]
Issue #596 has been resolved by the merging of pull request #603 into the master branch.
