### ISSUE TITLE
orphan .rst documentation

### ISSUE THREAD

**Issue by zrisher** [open-source-economics/Tax-Calculator#693]
Currently there are three "orphan" `.rst` documentation files that aren't listed in the index / linked from anywhere else, so they'll appear in the Search tool but are otherwise unreachable. Should these be removed / updated and relinked?

* [installation.rst](https://github.com/open-source-economics/Tax-Calculator/blob/master/docs/source/installation.rst)
* [make_local_change.rst](https://github.com/open-source-economics/Tax-Calculator/blob/master/docs/source/make_local_change.rst)
* [parameter_taxonomy.rst](https://github.com/open-source-economics/Tax-Calculator/blob/master/docs/source/parameter_taxonomy.rst)

**Comment by martinholmer** [comment]
Zach,  Here are my views on the three orphan documentation files you identified:

(1) [installation.rst](https://github.com/open-source-economics/Tax-Calculator/blob/master/docs/source/installation.rst) --- remove this from repo.

(2) [make_local_change.rst](https://github.com/open-source-economics/Tax-Calculator/blob/master/docs/source/make_local_change.rst) --- remove this from repo because it is out-of-date and difficult to keep up-to-date.

(3) [parameter_taxonomy.rst](https://github.com/open-source-economics/Tax-Calculator/blob/master/docs/source/parameter_taxonomy.rst) --- rename this something like `policy_parameter_naming.rst` or `parameter_naming_scheme.rst`, edit it slightly (particularly with respect to floor/ceiling terminology and better use of min/max with an integer parameter), and point to it in the `contributor_guide.rst` file.

If you and others are in agreement, I'm willing to do the two deletes and the parameter-related edits.

@zrisher @MattHJensen @Amy-Xu @feenberg @GoFroggyRun

**Comment by zrisher** [comment]
That approach makes sense to me. The idea behind (2) is awesome, but I agree it seems very difficult to maintain unless the calculation architecture remains completely static, which seems unlikely.

**Comment by martinholmer** [comment]
Zach (@zrisher),
On further investigation, I find that even though all three `.rst` files you mention in issue #693 have an `:orphan:` line at the top of the file, only one of the three is actually an orphan: [installation.rst](https://github.com/open-source-economics/Tax-Calculator/blob/master/docs/source/installation.rst).  The `make_local_changes.rst` file is referenced in the `contributor_guide.rst` file, and the  `parameter_taxonomy.rst` file is referenced in the `make_local_changes.rst` file.

So, I have done some minor documentation editing in pull request #704 and have deleted from the repository the one real orphan file.

Do you think the changes in #704 resolve this issue #693?  If you think more needs to be done, you could close this issues and raise another one.  Or, if you thing #704 resolves this issue, you could simply close issue #693 saying that #704 resolved it.

**Comment by MattHJensen** [comment]
@martinholmer said:

>If you and others are in agreement, I'm willing to do the two deletes and the parameter-related edits.

@zrisher said:

> That approach makes sense to me. (1) is obsolete. The idea behind (2) is awesome, but I agree it would be very difficult to maintain unless the calculation architecture remains completely static, which seems unlikely.

I'm in agreement as well.

**Comment by martinholmer** [comment]
@MattHJensen and Zach @zrisher,
Please look at (merged) pull request #704 to see the latest status of the three documentation files Zach identified in issue #693; it turns out that two of the three were not orphans after all.  If either of you think the current situation needs to be improved, please offer your suggestions.  Otherwise, close this issue.

**Comment by zrisher** [comment]
> deleted `installation.rst`

Looks good!

> renamed and updated `parameter_taxonomy.rst`

Looks good!

> removed orphan tag from `make_local_change.rst`

Looks ok, although I believe our original consensus that it's "difficult to keep up-to-date" is valid. If it's currently accurate, I support leaving as-is with the understanding that we need to keep a close eye on it.

**Comment by martinholmer** [comment]
Zach (@zrisher),
Given your most recent responses to issue #693, I'm assuming that we can now close this issue.
Thanks for pointing out these problems in the `.rst` documentation files, which have been fixed (at least to some extent) in pull request #704.

@MattHJensen @Amy-Xu
