### ISSUE TITLE
Imputations are only performed if `self.current_year == Records.PUF_YEAR`

### ISSUE THREAD

**Issue by zrisher** [open-source-economics/Tax-Calculator#694]
On [`line 268 of records.py`](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/records.py#L268), when constructing a `Records` object we perform imputations only `if consider_imputations and self.current_year == Records.PUF_YEAR`. 

However, I believe imputations should always be performed regardless of current year when creating the `Records` object as long as the flag is specified in the constructor. The current logic requires users of non-standard data with a current year != Records.PUF_YEAR to manually call `_impute_variables()` after construction, regardless of if they provide the appropriate flag.

I would suggest rewriting lines 268-270 to:
```
if consider_imputations:
    self._impute_variables()

if self.current_year == Records.PUF_YEAR:         
     self._extrapolate_2009_puf()
```

But I may be overestimating the usefulness of `_impute_variables()`. Related to #688.

**Comment by martinholmer** [comment]
@zrisher said:
> I believe imputations [in Records._impute_variables()] should always be performed regardless of current year when creating the Records object as long as the flag is specified in the constructor.

Maybe I'm confused, but it seems to me the the logic in the Records._impute_variables() method is correct only if the data are from the 2009 PUF.  Am I confused?

**Comment by MattHJensen** [comment]
> Maybe I'm confused, but it seems to me that the logic in the Records._impute_variables() method is correct only if the data are from the 2009 PUF. Am I confused?

@amy-xu, could you check?

**Comment by Amy-Xu** [comment]
@martinholmer @MattHJensen just checked, I believe Zach is right, assuming any future files would have the imputation of wage for primary and secondary filers. Do you see anything particular for 09 PUF? @martinholmer

**Comment by martinholmer** [comment]
Amy said:
> Do you see anything particular [to] 2009 PUF [in the Records._impute_variables() method]?

Actually, other than the misleading introductory docstring for the Records._impute_variables() method, no there does not seem to be any hard-coded 2009 PUF information left in this method.  So, yes, Zack is correct about this in issue #694.

But I'm confused about Zach's suggested code change in issue #694; it seems to ignore issue #688.

If we implement Matt's ideas and implement #688, there will no longer be a Records._impute_variables() method.   Zach, are you saying you **need** the Records._impute_variables() method?  If so, why?

@Amy-Xu @zrisher @MattHJensen

**Comment by zrisher** [comment]
@martinholmer Whether or not a non-standard-input user has need of this imputation logic is part of my question. :smile: 

`_impute_variables()` assigns a number of variables to the record set that seemed to be used in tax calculation: `_cmbtp_itemizer`, `_cmbtp_standard`, `_txpyers`, `numextra`, `e00200p`, `e00200s`, `e00900p`, `e00900s`, `e02100p`, and `e02100s`.

Searching through the repo, `_cmbtp_itemizer`, `_cmbtp_standard`, `numextra` are only used if the input data was a puf, and `_txpyers` doesn't seem to be used at all. 

However, `e00200p`, `e00200s`, `e00900p`, `e00900s`, `e02100p`, and `e02100s` do appear to be utilized in a general case. Thus the part of `_impute_variables()` that derives these variables from the smaller input set of `MARS`, `wage_head`, and `wage_spouse` might be generally useful if you only have `wage_head` and `wage_spouse` instead of the actual split for each of those variables, or if you'd simply like to approximate.

I definitely fully support moving all data preparation that's only needed for a puf-specific case to a dedicated separate area. And I don't have an opinion yet on if the situation described above is worth supporting for a non-puf case - that's up to you guys who are much better versed in using the calculator.

**Comment by martinholmer** [comment]
Zach,

Thanks for your extended explanation in this issue #694.  I think I now understand better your concerns and questions.

My understanding of our long-term goal is to move towards a situation in which Tax-Calculator reads any input data file and sets all the variables it knows about to zero if they were not present in that input data file.  This means that anyone preparing an input data file (including the core developers who create the `puf.csv` input file and the soon to be available pure-CPS input file) have the responsibility of specifying the variables in their data file using the names Tax-Calculator expects.

I hope that statement of general principle was correct (that is, other core developers would agree) and helpful to you.  Now let me turn to some of your specific questions:

> `_impute_variables()` assigns a number of variables to the record set that seemed to be used in tax calculation: `_cmbtp_itemizer`, `_cmbtp_standard`, `_txpyers`, `numextra`, `e00200p`, `e00200s`, `e00900p`, `e00900s`, `e02100p`, and `e02100s`.
>
> Searching through the repo, `_cmbtp_itemizer`, `_cmbtp_standard`, `numextra` are only used if the input data was a puf, and `_txpyers` doesn't seem to be used at all.

`_txpyers` was local to the `Records._impute_variables()` method.  I'm preparing a pull request that eliminates `numextra` (using the new `age_head` and `age_spouse` variables instead), and therefore, eliminates `_txpyers`, which was used to compute `numextra` in the old `Records._impute_variables()` method.  Matt is in a better position to explain the significance of the `_cmbtp_itemizer` and `_cmbtp_standard` variables.  All I know is that letting them both be zero does not seem to cause any problems when the SimpleTaxIO class reads in non-puf data.

> However, e00200p, e00200s, e00900p, e00900s, e02100p, and e02100s do appear to be utilized in a general case. Thus the part of _impute_variables() that derives these variables from the smaller input set of MARS, wage_head, and wage_spouse might be generally useful if you only have wage_head and wage_spouse instead of the actual split for each of those variables, or if you'd simply like to approximate.

Soon the head/spouse income splitting logic will also be moved out of the `_impute_variables()` method into the the taxdata repository as part of the final preparation of the `puf.csv` input file.  These variables have been added because they are needed to compute FICA (payroll) taxes, which are computed per individual (not per income tax filing unit).  So, if you want Tax-Calculator to compute correct FICA taxes, then you need to prepare an input data set that splits these three income variables between the head (taxpayer) and spouse (if present).

If you haven't already looked over the SimpleTaxIO class logic, doing so will provide a concrete example of how Tax-Calculator can be made to handle non-`puf.csv` data without any calls to the `_impute_variables()` method or any calls to "blowup" methods.

If I haven't answered all your questions clearly, please try again.

@zrisher @MattHJensen @Amy-Xu @feenberg @GoFroggyRun

**Comment by feenberg** [comment]
On Thu, 21 Apr 2016, Martin Holmer wrote:

> 
> Zach,
> 
> Thanks for your extended explanation in this issue #694. I think I now understand
> better your concerns and questions.
> 
> My understanding of our long-term goal is to move towards a situation in which
> Tax-Calculator reads any input data file and sets all the variables it knows about to
> zero if they were not present in that input data file. This means that anyone
> preparing an input data file (including the core developers who create the puf.csv
> input file and the soon to be available pure-CPS input file) have the responsibility
> of specifying the variables in their data file using the names Tax-Calculator expects.
> 
> I hope that statement of general principle was correct (that is, other core developers
> would agree) and helpful to you. Now let me turn to some of your specific questions:

That is the goal.

>
>       _impute_variables() assigns a number of variables to the record set that
>       seemed to be used in tax calculation: _cmbtp_itemizer, _cmbtp_standard,
>       _txpyers, numextra, e00200p, e00200s, e00900p, e00900s, e02100p, and
>       e02100s.
>
>       Searching through the repo, _cmbtp_itemizer, _cmbtp_standard, numextra are
>       only used if the input data was a puf, and _txpyers doesn't seem to be
>       used at all.
>

In taxcalc.sas there is a flag for signaling that some additional data is 
available that is PUF specific, and modifying the computation. I haven't 
devoted much thought to how this might be eliminated, but given the 
contradiction between the PUF and and INSOLE files, it may not be trivial.

Therefore my goal may not be fully achieved with respect to the PUF.

dan

**Comment by martinholmer** [comment]
Zach,

As I said earlier today, pull request #701 reduces the scope of the `Records._impute_variables()` method, and there is discussion about moving its remaining logic to the `final_prep/puf-cps-processing.py` script in the `taxdata` repository.  Do those plans work for your project?

@zrisher @MattHJensen @feenberg @Amy-Xu @GoFroggyRun

**Comment by zrisher** [comment]
@martinholmer Works for me, thanks for that very informative response! 

And yes I'm modeling `LucaTaxIO` on `SimpleTaxIO`.

**Comment by martinholmer** [comment]
Zach (@zrisher),
Would you say that questions you had in mind when you raised issue #694 have now been resolved?
If not, what questions remain unanswered?

@MattHJensen

**Comment by zrisher** [comment]
@martinholmer Yes, 

> preparing an input data file (including the core developers who create the puf.csv input file and the soon to be available pure-CPS input file) have the responsibility of specifying the variables in their data file using the names Tax-Calculator expects.

and 

> Soon the head/spouse income splitting logic will also be moved out of the _impute_variables() method into the the taxdata repository as part of the final preparation of the puf.csv input file. These variables have been added because they are needed to compute FICA (payroll) taxes, which are computed per individual (not per income tax filing unit). So, if you want Tax-Calculator to compute correct FICA taxes, then you need to prepare an input data set that splits these three income variables between the head (taxpayer) and spouse (if present).

Answered this for me. Thank you!
