### ISSUE TITLE
Codecov reports are crazy; needs to be fixed or fired

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#766]
Here is the part of the email I got concerning PR #765, which made changes in the `behavior.py` file only:
```
Merging #765 into master will decrease coverage by 0.58%
File taxcalc/behavior.py was modified. more
Misses +2
Partials 0
Hits -2
File taxcalc/calculate.py (not in diff) was modified. more
Misses +6
Partials 0
Hits -6
```
But I didn't make any changes in `calculate.py`.  What is going on?

I don't have any problem using this tool, but the reports have been (after some recent "enhancements") nearly incomprehensible, and now completely mystifying.

Can we make this tool work correctly and produce sensible reports?  If not, why not get rid of it?

@talumbau 
and

**Comment by talumbau** [comment]
Hi @martinholmer ,

I'm about to board a plane, but by looking at the output of the tool, I believe it is saying that there are now six lines of code in calculate.py that used to be executed in our tests, that would no longer be executed. Perhaps these cases are no longer relevant? The tool is counting each line of code that is executed by the tests. So, in the report, it says that the following lines are no longer executed:

<img width="898" alt="screen shot 2016-06-01 at 5 13 31 pm" src="https://cloud.githubusercontent.com/assets/1891418/15727492/781008de-281c-11e6-9679-268954ebb351.png">

Is this correct? I don't have time to check the tool right now, but can look later. Have a look and let me know if you think the output is potentially correct or if it is still mysterious.

**Comment by martinholmer** [comment]
T.J. (@talumbau) said:
> I'm about to board a plane, but by looking at the output of the tool, I believe it is saying that there are now six lines of code in calculate.py that used to be executed in our tests, that would no longer be executed. Perhaps these cases are no longer relevant? The tool is counting each line of code that is executed by the tests. So, in the report, it says that the following [six] lines are no longer executed:
>
> screen shot of the **six lines in calculate.py**
>
> Is this correct? I don't have time to check the tool right now, but can look later. Have a look and let me know if you think the output is potentially correct or if it is still mysterious.

But why is Codecov saying this when I did not change anything in the `calculate.py` or `test_calculate.py` files?  I thought the report focused on how my proposed code changes (in the pull request) affect code coverage.  So, yes, this report is "still mysterious" to me.

**Comment by talumbau** [comment]
I am still investigating what's going on, but the general concept is as follows:

Suppose I change something in behavior.py or some other source file in `taxcalc/`, and the substance of my change is basically an `if` statement. I place the `if` statement somewhere around existing code, and I make it a condition that can never be satisfied. Thus, some lines of code in behavior.py never get called. *However*, suppose the code in behavior.py (that is no longer called) calls functions in calculate.py in such a way that no other code does. Thus, there might be some code path in `calculate.py` that is no longer called because of a change in `behavior.py`. Does that make sense?

**Comment by talumbau** [comment]
@martinholmer, all is well with #765 and the coverage report is correct. There are two things going on:

1. The big message from codecov in your PR is based on the first push, which was commit https://github.com/open-source-economics/Tax-Calculator/pull/765/commits/98fc23e31ff4c3e95721524d12b2bfa97154bb32. In this commit, it is correct that code coverage went down (for reasons I will explain in a moment). However, if you look down further in your PR, you will see an updated report from Codecov showing that test coverage goes up by 0.38%. You have to click the "show all checks" button.

2. The change occurred because in commit https://github.com/open-source-economics/Tax-Calculator/pull/765/commits/98fc23e31ff4c3e95721524d12b2bfa97154bb32 the value of `income_type_str` was always `e00200p` so some lines of code were never checked. However, in your last commit on the PR, you made some tests such that the behavior setting was `_BE_cg` in some tests, so that `income_type_str` was different, thus calling the `elif` lines of code.

so I think the report is correct and you are increasing test coverage in your PR. let me know if this does not make sense.

**Comment by talumbau** [comment]
Another way to think about what Codecov does:

Imagine that at the beginning of test execution, every line of code in Tax-Calculator is marked with an "unexecuted" flag. As each test runs, any line of code that is executed has this flag flipped to "executed". After all tests have run, Codecov adds up the executed and unexecuted lines of code for every source file in Tax-Calculator. Therefore, changes anywhere in the code or tests could have complex effects across the source code base.

**Comment by martinholmer** [comment]
T.J. (@talumbau) said:
>  All is well with #765 and the coverage report is correct. There are two things going on:
>
> The big message from codecov in your PR is based on the first push, which was commit 98fc23e. In this commit, it is correct that code coverage went down (for reasons I will explain in a moment). However, if you look down further in your PR, you will see an updated report from Codecov showing that test coverage goes up by 0.38%. You have to click the "show all checks" button.

I guess that is my main complaint about Codecov: why does it not replace, or add another summary report, when another commit is made to a pull request.  Because I don't know how to run Codecov on my local computer, I have to submit a pull request to find out if my changes have decreased code coverage.  And when it turns out I need to add extra tests, Codecov does not supply (either via email or via a new entry in the pull request conversation) a new code coverage summary report.  This is very confusing.  I appreciate your tip on how to scroll down and click on the "show all checks" button, but this all seems a little arcane.  Why not just send another email or post a new code coverage report in the pull request conversation?

> The change occurred because in commit 98fc23e the value of income_type_str was always e00200p so some lines of code were never checked. However, in your last commit on the PR, you made some tests such that the behavior setting was _BE_cg in some tests, so that income_type_str was different, thus calling the elif lines of code.

Perhaps you're correct about this; I don't have the energy to verify your analysis.  But, let's say your analysis of this particular situation is correct, then why doesn't Codecov explain what's going on, just like you explained it to me?   If it is clever enough to figure out the situation you describe, then it understands exactly why the code coverage declined.  Why doesn't it offer that explanation?  I thought to whole point of programming-support tools was to increase a programmer's productivity.  But we can see that in this case using Codecov has reduced our productivity because I was stumped about these results and you had to spend a lot of time explaining what the tool should have told me in the first place.

> So I think the report is correct and you are increasing test coverage in your PR. Let me know if this does not make sense.

Thanks for spending all this time to explain this to me.
