### ISSUE TITLE
exception handling

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#811]
A side discussion in #786 concerned exception handling. Looking back, #768/#754 touched on related issues. As a relative newcomer to Python and programming more generally, I am wondering if @zrisher, @talumbau, @martinholmer, or anyone else could provide any resources or background information that could help Tax-Calculator and other OSE  contributors think about how to handle exceptions in these projects.

**Comment by zrisher** [comment]
[PEP 8](https://www.python.org/dev/peps/pep-0008) mentions some exception handling and raising rules that are already enforced and we should of course follow:

> * When catching exceptions, mention specific exceptions whenever possible instead of using a bare except: clause. A bare except: clause will catch SystemExit and KeyboardInterrupt exceptions, making it harder to interrupt a program with Control-C, and can disguise other problems. If you want to catch all exceptions that signal program errors, use except Exception: (bare except is equivalent to except BaseException: ). A good rule of thumb is to limit use of bare 'except' clauses to two cases:
1) If the exception handler will be printing out or logging the traceback; at least the user will be aware that an error has occurred.
2) If the code needs to do some cleanup work, but then lets the exception propagate upwards with raise . try...finally can be a better way to handle this case.
> * Use exception chaining appropriately. In Python 3, "raise X from Y" should be used to indicate explicit replacement without losing the original traceback. When deliberately replacing an inner exception (using "raise X" in Python 2 or "raise X from None" in Python 3.3+), ensure that relevant details are transferred to the new exception (such as preserving the attribute name when converting KeyError to AttributeError, or embedding the text of the original exception in the new exception message).

Plus a few common-sense syntax and naming conventions excluded here for brevity.

It doesn't say much about "when should we catch/raise exceptions?" though, which is I think the primary question that has come up for this project in the past. That's probably because it's really a general programming question and not a Python style/usage one.

In my opinion, I think [this SO post](http://programmers.stackexchange.com/questions/231057/exceptions-why-throw-early-why-catch-late) sums up the best practices really well:

> In my experience, its best to throw exceptions at the point where the errors occur. You do this because it's the point where you know the most about why the exception was triggered.

> As the exception unwinds back up the layers, catching and rethrowing is a good way to add additional context to the exception. This can mean throwing a different type of exception, but include the original exception when you do this.

> Eventually the exception will reach a layer where you are able to make decisions on code flow (e.g a prompt the user for action). This is the point where you should finally handle the exception and continue normal execution.

> With practice and experience with your code base it becomes quite easy to judge when to add additional context to errors, and where it's most sensible to actually, finally handle the errors.

> Catch → Rethrow
Do this where you can usefully add more information that would save a developer having to work through all the layers to understand the problem.

> Catch → Handle
Do this where you can make final decisions on what is an appropriate, but different execution flow through the software.

> Catch → Error Return
Whilst there are situations where this is appropriate, catching exceptions and returning an error value to the caller should be considered for refactoring into a Catch → Rethrow implementation.

Based on my ordered priorities for code design decisions to maximize:
* ease of use
* ease of development
* performance

I think that jives with the decisions we came to in #786 and #754. 

I'm interested to hear other opinions!

**Comment by feenberg** [comment]
What exceptions can be raised by this software? Is this about debugging or 
do we contemplate exceptions occurring during normal use?

dan

**Comment by zrisher** [comment]
> What exceptions can be raised by this software? Is this about debugging or
do we contemplate exceptions occurring during normal use?

This project can throw lots of customized errors during normal use. I think a great example is [this line ](https://github.com/open-source-economics/Tax-Calculator/blob/0f811c9cb2f2a9be3682c57decfc5fd8d11f279e/taxcalc/records.py#L400)that checks to ensure that `MUST_READ_VARS` are available in the data passed to a `Records` object. If we didn't do this here, the user would later be presented with general missing method errors (which they would likely find confusing) since we assume these are available in later code. We catch them here because it's the earliest opportunity to ensure they are available, and we're definitely in an error condition if not.

**Comment by martinholmer** [comment]
@zrisher provides in issue #811 a good example of where Tax-Calculator raises an exception and stops running: if the variables in the `MUST_READ_VARS` set are not present in the input data file.   He provides the code that checks for that and here is the definition of the `MUST_READ_VARS` set:
```
 # specify set of all Record variables that MUST be read by Tax-Calculator:
 MUST_READ_VARS = set(['RECID', 'MARS'])
```
So, there are only two required input variables: a `RECID` variable to identify each filing unit and MARS (the filing unit type), which cannot be zero because many policy parameters are indexed by `MARS-1`.  All variables used by Tax-Calculator that are not in the input dataset are set to zero.  There is actually a unit test that confirms Tax-Calculator runs without error and produces "sensible" results when only these two variables are input.

@MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun

**Comment by feenberg** [comment]
On Fri, 29 Jul 2016, zrisher wrote:

>
>       What exceptions can be raised by this software? Is this about debugging or
>       do we contemplate exceptions occurring during normal use?
> 
> This project can throw lots of customized errors during normal use. I think a great
> example is this line that checks to ensure that MUST_READ_VARS are available in the
> data passed to a Records object. If we didn't do this here, the user would later be
> presented with general missing method errors (which they would likely find confusing)
> since we assume these are available in later code. We catch them here because it's the
> earliest opportunity to ensure they are available, and we're definitely in an error
> condition if not.

I see. It wouldn't happen on taxbrain but might happen to a user who was 
supplying their own data or modifying programs.

dan

**Comment by zrisher** [comment]
@MattHJensen @martinholmer @talumbau In the absence of additional comments, it seems we're all ok with the above recommendations for exception handling. Can we close this issue, possibly labeling it with an "FAQ" tag for future reference?

**Comment by MattHJensen** [comment]
@zrisher said: 

> Can we close this issue, possibly labeling it with an "FAQ" tag for future reference?

I like the FAQ tag idea. Done and done.

**Comment by feenberg** [comment]
On Mon, 2 Jan 2017, zrisher wrote:

> 
> @MattHJensen @martinholmer @talumbau In the absence of additional comments, it seems we're all ok with
> the above recommendations for exception handling. Can we close this issue, possibly labeling it with
> an "FAQ" tag for future reference?

  I am not sure what has been decided. The example given for a useful 
exception (missing MUST_READ_VAR) is a case where the exception is used
to shut down processing. It isn't necessary to use exceptions for cases
where processing ceases, although exceptions might be used as part of a
sohpisticated error reporting scheme.

Suppose an exception occurs during the calculation of tax liability - say
divide by zero error. Do we want to skip that taxpayer and go on to the 
next? I'd want to examine such a case individually before saying yes, 
since it seems quite likely that such an exception represented a 
correctable problem in the specification of the tax that the user would 
want to know about.

The Solaris fortran compiler continues after floating point exceptions, 
and then at the end of the run tells you that one occurred, but gives
no information about when or where. It is most frustrating to locate
the source of the problem. Abending would be much superior.

I think it unlikely we actually need to catch exceptions at all. Do people 
have in mind some particular costs or benefits of exceptions that I am not 
aware of?

dan

**Comment by zrisher** [comment]
@feenberg said:
> I am not sure what has been decided. 

My understanding of the implied consensus here is that we will follow [the guidance I posted](https://github.com/open-source-economics/Tax-Calculator/issues/811#issuecomment-236244517).

@feenberg said:
> The example given for a useful
exception (missing MUST_READ_VAR) is a case where the exception is used
to shut down processing. It isn't necessary to use exceptions for cases
where processing ceases, although exceptions might be used as part of a
sohpisticated error reporting scheme.

It's true there are other ways we could halt execution at this point, but using an exception seems to me by far the simplest and most reliable. It follows this portion of the provided guidance:

> its best to throw exceptions at the point where the errors occur. You do this because it's the point where you know the most about why the exception was triggered.

@feenberg said:
> Suppose an exception occurs during the calculation of tax liability - say
divide by zero error. Do we want to skip that taxpayer and go on to the
next? I'd want to examine such a case individually before saying yes,
since it seems quite likely that such an exception represented a
correctable problem in the specification of the tax that the user would
want to know about.

I think we all agree with you - *unexpected* exceptions encountered during tax calculation should bubble back up to the caller. If I amend `EI_PayrollTax()` in `functions.py` to purposefully cause a division by zero error: 

`sey_p = e00900p + e02100p` -> `sey_p = e00900p + e02100p + 1/0`

Then I expect to receive `ZeroDivisionError` when running `py.test taxcalc/tests/test_calculate`, which is exactly what happens.

@feenberg said:
> I think it unlikely we actually need to catch exceptions at all. Do people
have in mind some particular costs or benefits of exceptions that I am not
aware of?

Take for example these lines in `taxcalc/calculate.py`:

```
def read_json_reform_text(text_string):
        ...
        # convert JSON text into a Python dictionary
        try:
            raw_dict = json.loads(json_without_comments)
        except ValueError as valerr:
            msg = 'Policy reform text below contains invalid JSON:\n'
            msg += str(valerr) + '\n'
            msg += 'Above location of the first error may be approximate.\n'
            msg += 'The invalid JSON reform text is between the lines:\n'
            ...
            raise ValueError(msg)
```

Here, we *expect* that we may receive an exception when parsing the user-provided reforms json. Instead of allowing a generic parsing error to reach the caller, we catch the error and use our understanding of what's going on at this portion of the code to *add context* to the error message, which is then rethrown. That follows this portion of the posted guidance:

>   Catch → Rethrow
  Do this where you can usefully add more information that would save a
  developer having to work through all the layers to understand the problem.
