### ISSUE TITLE
Release 0.6.7 changes

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#863]
Please update this issue with your significant contributions as they are merged to master. 

The last PR included in 0.6.6 was #857. The notes issue for tracking release 0.6.6 was #841.

**Comment by martinholmer** [comment]
Here is my notion of "significant contributions" since the version 0.6.6:

| Contributor         | PR# | Description |
| :---------------- | :--- | :----------- |
| Sean Wang | #858 | add extra income tax brackets and rates |
| Martin Holmer | #874 | correct Net Investment Income Tax (NIIT) calculation |
| Martin Holmer | #898 | correct Schedule R credit calculation |
| Anderson Frailey | #904 | add ability to simulate Fair Share Tax reforms |
| Sean Wang | #913 | add ability to tax pass-through income at different rates |
| Martin Holmer | #914 | remove logic for expired First-Time Homebuyer Credit |
| Matt Jensen | #926 | add itemized-deduction surtax exemption policy parameter |

**Comment by MattHJensen** [comment]
Thanks @martinholmer. Here is the release: https://github.com/open-source-economics/Tax-Calculator/releases/tag/0.6.7.
