### ISSUE TITLE
personal refundable credit and non-filers

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#865]
When I add a personal refundable credit, the number of returns presented on TaxBrain does not change. http://www.ospc.org/taxbrain/5064/

I would have expected some of the non-filers -- whom we have from the CPS match -- to start to file. 

@amy-xu or @andersonfrailey, could you help me understand why this is?

**Comment by Amy-Xu** [comment]
If the table is linked to the diagnostic table in TC, then I think the total returns here is the number of everyone in the dataset who has positive AGI, which includes the non-filers from the beginning. If you sum up standard deducters and itemizers, the total 157 million is 13m aways from the 170 million in total. 

If this indeed is what's happening, it wouldn't be too surprising to see no change on total return numbers. To reflect non-filers changes, we should probably create the table with one more filter using the 'filer' variable.

**Comment by MattHJensen** [comment]
I see. Could you verify that the personal refundable credit is available to non-filers -- and thereby increases the number of filers -- by looking to see how many new filers there are w/ a new personal refundable credit and no other changes to current law? Say $1000 for every tax unit.

**Comment by Amy-Xu** [comment]
You mean keep personal exemption and standard deduction the same, and just add a refundable credit?

**Comment by MattHJensen** [comment]
That's right. Current law + refundable personal credit.

**Comment by Amy-Xu** [comment]
In 2013, a reform giving everyone $1000 refundable credit

`reform = {2013: {"_II_credit": [[1000, 1000, 1000, 1000, 1000, 1000]]}}`

increases non-filer with non-zero IIT liabilities from .85 million to 15.66 million, a net increase of 14.81 million.

Do you need the number for 2016 or all ten years on budget window?

**Comment by MattHJensen** [comment]
@Amy-Xu, thanks a lot. The discussion in this issue confirms that the personal refundable credit would bring tax filers onto the tax rolls. This is distinct from the personal refundable credit proposed by 2016 election candidate Rubio, who wanted to limit the availability of the personal refundable credit to only tax units who would otherwise file. I will open a PR adding documentation to current_law_policy.json to resolve this issue. 

This discussion also highlights that the "returns" we present on TaxBrain and in our diagnostic tables may be misleading, as it captures everyone with positive AGI rather than everyone with non-zero IIT, or alternatively, everyone with non-zero IIT + FICA. I will open another issue for discussion of an alternative.

**Comment by feenberg** [comment]
On Mon, 15 Aug 2016, Matt Jensen wrote:

> 
> When I add a personal refundable credit, the number of returns presented on TaxBrain
> does not change. http://www.ospc.org/taxbrain/5064/
> 
> I would have expected some of the non-filers -- whom we have from the CPS match -- to
> start to file.

Do we have all wage earners between 25 and 65 filing, even if they owe no 
taxes, to obtain the EIC? What about other workers that may have had wages 
withheld? So the change in # filers would be small. I recall that in the 
past there was a year when a tax credit was made available to many that 
would otherwise not file, the SOI counted those returns separately. For 
instance, the telephone tax credit for 2006.

Nevertheless, I think you are right that the number of returns should 
reflect the personal tax credit.

dan

**Comment by feenberg** [comment]
On Mon, 15 Aug 2016, Amy Xu wrote:

> 
> If the table is linked to the diagnostic table in TC, then I think the total returns
> here is the number of everyone in the dataset who has positive AGI, which includes the

That is an odd criteria. Most with negative AGI would be required to file, 
and some with positive AGI (retirees on social security) wouldn't have any 
need to file.

We could use non-zero tax liability or even addincome above filing 
threshold (which I think is person exemption plus standard deduction) if 
we wanted to do that extra work.

> non-filers from the beginning. If you sum up standard deducters and 
> itemizers, the total 157 million is 13m aways from the 170 million in 
> total.
> 
> If this indeed is what's happening, it wouldn't be too surprising to see no change on
> total return numbers. To reflect non-filers changes, we should probably create the
> table with one more filter using the 'filer' variable.
>

There might be a good case for showing positive and negative tax returns 
separately, especially since there are so many negative returns. It would 
be a way of supporting the AEI agenda without causing negative thoughts 
among progressives.

dan
