### ISSUE TITLE
Provide style guidelines in the developer docs

### ISSUE THREAD

**Issue by zrisher** [open-source-economics/Tax-Calculator#946]
I believe the developer documentation (e.g. `README.md`, `contributor_guide.rst`) should discuss the style guidelines for the repository. 

In the past (https://github.com/open-source-economics/Tax-Calculator/issues/30) we decided to enforce PEP8 and optionally allow developers to run pylint locally. However, PEP8 only offers guidance on a subset of all possible style questions, and our lack of pylint enforcement leaves developers wondering whether their work should be pylint compliant or if should be left up to the contributors that _choose_ to run pylint. Even if pylint was enforced, we still would have a lot of holes in our style guidance.

**I would like to have a section of the developer docs that:**
- discusses our enforcement of PEP8 and pylint
- discusses how to analyze the current code state for PEP and pylint
- lists any style guides that should guide our hand in other cases, in priority order (e.g. [google's python style guide](https://code.google.com/archive/p/soc/wikis/PythonStyleGuide.wiki))
- lists specific cases not covered by anything above where we've decided the best approach
- discusses the correct approach when encountering something not covered above (preferably "use your best judgement and open an issue for discussion," the result of which will be listed in the section mentioned in the above point

I believe this could provide a ton of value without being particularly verbose.

**I also think that if our developers are finding pylint useful, we should aim to begin enforcing it.**

A couple examples of times I was coding and needed the above:
- When listing imports in my `TaxForm` work (and more recently), I was unsure of the proper sort order. The PEP8 style guide had some useful notes on this, but it didn't answer all my questions, and [it turns out](http://stackoverflow.com/questions/20762662/whats-the-correct-way-to-sort-python-import-x-and-from-x-import-y-statement#answer-20763446) that even if you look through all the available style documentation this isn't fully agreed upon. 
- When writing my `TaxForm` classes, I left out the pylint ignore blocks that I saw in other files because I didn't receive any PEP8 errors when running the tests as specified in `.travis.yml` and didn't realize that pylint and PEP8 were actually two separate things due to my relative inexperience with python (and the fact that pylint isn't listed as a dependency). I ran into a similar issue more recently when improving fixture usage in the test suite.

@talumbau @martinholmer @MattHJensen @Amy-Xu @GoFroggyRun @andersonfrailey

**Comment by martinholmer** [comment]
@zrisher began a thoughtful comment with the following statement:
> I believe the developer documentation (e.g. README.md, contributor_guide.rst) should discuss the style guidelines for the [Tax-Calculator] repository.

I agree with you.

I would favor leaving the already-lengthy [Contributor Guide](http://taxcalc.readthedocs.io/en/latest/contributor_guide.html) unchanged and adding the coding-style documentation to a new `CODING.md` file, which would be referenced in the `README.md` file in the same way as the existing `TESTING.md` file is.

Then there is the question of what to say in the `CODING.md` file.  Your initial comment in issue #946 covers all the potential issues to discuss.

Maybe the way to start developing this coding-style documentation is for me to prepare a pull request containing the new `CODING.md` file and then the discussion of that pull request can air the important issues raised in issue #946.  Does this make sense?  Is there a better approach?

@MattHJensen @talumbau @Amy-Xu @GoFroggyRun @andersonfrailey

**Comment by talumbau** [comment]
I think it would be worthwhile to explore the use of a tool to handle these style issues:

https://github.com/google/yapf

`yapf` has been around for a while now and I think a lot of people are happy with it. We could agree on a set of knobs/options on this tool and then it would automatically format the code according to those rules. @zrisher do you think `yapf` could handle the issues you mention above?

**Comment by martinholmer** [comment]
@talumbau said:
> I think it would be worthwhile to explore the use of a tool to handle these style issues:
>
> https://github.com/google/yapf
> 
> `yapf` has been around for a while now and I think a lot of people are happy with it. We could agree on a set of knobs/options on this tool and then it would automatically format the code according to those rules. @zrisher do you think yapf could handle the issues you mention above?

Frankly, I think this is a very bad idea.  It just adds yet another tool that you have to understand and is likely to promote sloppy coding, not all of which may be reformatted by `yapf`.  Editors can use `pep8` and `pylint` to quickly find style warnings in an interactive way that makes it very easy to find and correct coding-style problems.  If contributors are not using such editors --- ones like Emacs --- then moving them to a modern editor would be a better step than adding another layer of complexity with `yapf` doing **automatic formatting**.

@MattHJensen @zrisher @Amy-Xu @GoFroggyRun @andersonfrailey

**Comment by zrisher** [comment]
First, thanks @martinholmer for your excellent PR #978, which:

* discusess our enforcement of PEP8 and pylint
* discusses how to analyze the current code state for PEP and pylint
* declares `pep8` and `pylint` packages as environment requirements

**I would still like something to handle style cases not covered by PEP8 or pylint** but common to our repo, where some consistency would be helpful. 

**Thus my original request** that the style doc:

* lists any style guides that should guide our hand in other cases, in priority order (e.g. google's python style guide)
* lists specific cases not covered by anything above where we've decided the best approach
* discusses the correct approach when encountering something not covered above (preferably "use your best judgement and open an issue for discussion," the result of which will be listed in the section mentioned in the above point

Something like the above would give a definitive answer to every possible style question, which would improve consistency and hopefully help the repository become more usable. 

**Another possible approach** is what @talumbau suggested - apply an automatic code formatter like `yapf` as part of the contribution process. Then we could simply say "leave it up to yapf unless it looks truly abysmal." I haven't personally used code formatters before, but something that can: 

* ensure a repo's style is maintained across commits
* obviate the majority of style communication and documentation
* automatically stay up to date with the Python community's style recommendations and the style of other major projects

sounds like a powerful tool. It seems like it could make the repo more navigable for new users, decrease the effort of incorporating commits from new contributors, and save the rest of us from researching the proper way to style unusual corner cases. 

@martinholmer makes some good points when he mentions the possible problems with this tool:

> It just adds yet another tool that you have to understand

True, though with this running you could argue you have less of a need to understand `pep8` or `pylint`. And when combined with a swiss-army-knife code quality tool like Continuum's [ciocheck](https://github.com/ContinuumIO/ciocheck), the average contributor might only need to be familiar with a single tool to get the benefit of all the linters, formatters, and testers. 

> is likely to promote sloppy coding

Can't argue with this one. The important question would be "how much of that sloppiness leaks into the actual logic?"

Also, it would likely take longer to get `yapf` set up and configured to our liking than it would to write out the remaining style pointers in our developer docs and leave it up to the contributors themselves to properly follow them for cases not covered by pep8 & pylint. It's more of an investment in the future, where if we had many new contributors it might save us all time. 

Here's what a lightly configured `yapf` would do the the `taxcalc` folder as it currently stands:
https://github.com/zrisher/Tax-Calculator/commit/99c99ac8dc751b846768c8575d88d84328ba73ed

**Either way, I'm happy to help.** Applying more code maintenance tools like `yapf` and `ciocheck` may or may not be the best approach for this project.

@MattHJensen @martinholmer @talumbau @Amy-Xu @GoFroggyRun @andersonfrailey

**Comment by martinholmer** [comment]
@zrisher, Thank you for your thoughtful 27-Oct-2016 comments on issue #946 with respect to coding style documentation.

First of all, in case anybody else is reading this conversation, we need to clarify some terms.  The `pep8` and `yapf` programs mostly (exclusively?) address the horizontal and vertical positioning of Python source code.  I suppose you could say they check "coding style", but it seems more accurate to say they check "formatting style".  On the other hand, the `pylint` program focuses on more substantive logical issues: it checks that every function argument is used in that function, for example.  (Note that there is code in Tax-Calculator that fails this test.)

Currently, all Tax-Calculator Python code is checked using `pep8` and this is enforced by the Travis-CI utility.  Some Python files in the Tax-Calculator repository have been developed so that they do not generate any `pylint` warnings, but this is optional and is not enforced by the Travis-CI utility.

You seem to want more.  Let's discuss whether something more would have a positive net benefit (that is, benefits minus costs) for the Tax-Calculator project.

> I would still like something to handle style cases not covered by PEP8 or pylint but common to our repo, where some consistency would be helpful.
> ... [list of suggestions] ...
> Something like the above would give a definitive answer to every possible style question, which would improve consistency and hopefully help the repository become more usable.

I doubt whether the project will experience a positive net benefit from enforcing a formatting style that goes beyond `pep8` rules to "give a definitive answer to every possible style question".  To me this goal is a Holy Grail.  Personally, I'm happy with enforcing the `pep8` formatting rules.  I think that generates a good balance of benefits (in terms of code readability) and costs (of complying with the enforced rules).

The rest of your comment discusses the possible use of `yapf` in this project.

> Here's what a lightly configured yapf would do the the taxcalc folder as it currently stands:
zrisher@413a57f

Thanks for doing this; it is very informative.  The `yapf` reformatting makes sense in some cases, but in other cases the `yapf` reformatting makes the code virtually unreadable.

First an example of a `yapf` reformatting that makes sense to me:
```
# default price inflation rates by year
 -    __pirates = {2013: 0.0148, 2014: 0.0159, 2015: 0.0013, 2016: 0.0135,
 -                 2017: 0.0233, 2018: 0.0236, 2019: 0.0238, 2020: 0.0245,
 -                 2021: 0.0242, 2022: 0.0240, 2023: 0.0239, 2024: 0.0240,
 -                 2025: 0.0245, 2026: 0.0242}
 +    __pirates = {
 +        2013: 0.0148,
 +        2014: 0.0159,
 +        2015: 0.0013,
 +        2016: 0.0135,
 +        2017: 0.0233,
 +        2018: 0.0236,
 +        2019: 0.0238,
 +        2020: 0.0245,
 +        2021: 0.0242,
 +        2022: 0.0240,
 +        2023: 0.0239,
 +        2024: 0.0240,
 +        2025: 0.0245,
 +        2026: 0.0242
 +    }
```
The placement of one year:rate pair on a line makes the code easier to read.  But if the dictionary elements had been misplaced (with the years out of order), I imaging `yapf` would have continued to place them in the wrong order.  But, I guess, the whole point of this reformatting is to make such an irregular year ordering more apparent to the eye.

Now an example of a `yapf` reformatting that makes **no** sense to me:
```
 -    return (rate1 * min(income, brk1) +
 -            rate2 * min(brk2 - brk1, max(0., income - brk1)) +
 -            rate3 * min(brk3 - brk2, max(0., income - brk2)) +
 -            rate4 * min(brk4 - brk3, max(0., income - brk3)) +
 -            rate5 * min(brk5 - brk4, max(0., income - brk4)) +
 -            rate6 * min(brk6 - brk5, max(0., income - brk5)) +
 -            rate7 * min(brk7 - brk6, max(0., income - brk6)) +
 -            rate8 * max(0., income - brk7))
 +    return (rate1 * min(income, brk1) + rate2 * min(brk2 - brk1,
 +                                                    max(0., income - brk1)) +
 +            rate3 * min(brk3 - brk2, max(0., income - brk2)) + rate4 * min(
 +                brk4 - brk3, max(0., income - brk3)) + rate5 * min(
 +                    brk5 - brk4, max(0., income - brk4)) + rate6 * min(
 +                        brk6 - brk5, max(0., income - brk5)) + rate7 * min(
 +                            brk7 - brk6, max(0., income - brk6)) + rate8 * max(
 +                                0., income - brk7))
```
To my eye this `yapf` reformatting makes the return statement unreadable.  This reformatting seems to be generated by a quest to squeeze as much code as will fit on a line.  But notice how this is totally at variance with the unrolling of the dictionary elements in the first example.

Now, I suppose, one response to these observations might be that `yapf` can be configured to not do stupid things like the second example above.  But, even if that is true, it simply reinforces my guess that the costs of using `yapf` would be high, the readability benefits of reformatting the code would be positive but not large, and therefore, the net benefits of using `yapf` would be negative.

If we want to put more effort into improving the code, it would seem to me that we would get more net benefit from eliminating `pylint` warnings than we would get from imposing more consistent formatting by using `ypaf`.

So, you can see that people have widely varying ideas about Python code formatting and about substantive Python coding style, and hence, different ideas whether or not certain tools should be used to enforce certain rules.  As as you can see, I'm in the minimalist camp: I'm just fine with what the Tax-Calculator project is doing now.

@MattHJensen @talumbau @Amy-Xu @GoFroggyRun @andersonfrailey

**Comment by martinholmer** [comment]
What is the status of issue #946?  This issue, which is titled "Provide style guidelines in the developer docs", was opened about two months ago, and the last comment in the discussion was posted over three weeks ago.  Is there any reason to keep this issue open?

@MattHJensen @feenberg @zrisher @Amy-Xu @GoFroggyRun @andersonfrailey

**Comment by zrisher** [comment]
@martinholmer You provided the majority of what I was asking for via PR #978. 

As you mentioned, the remaining ask boils down to "provide exact guidance via documentation and/or automated tools for nearly all style cases," which wasn't intended to be an *immediate* need, but possibly something to track for the long term. 

There are easy ways to fix the issues you demonstrated with the `yapf` output; it's a well known case it can't handle. Given your feedback and the absence of other input, though, I agree that both the increased documentation and the automated tool solutions would be more effort than they're currently worth.

Thanks for your work on this!
