### ISSUE TITLE
Activating the new _CG_nodiff parameter generates unanticipated results

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/Tax-Calculator#974]
These reforms generate different results. We should understand why and either adjust how _CG_as_II works or document the difference. 

p_yy = Policy()
reform1 = {2016: {
'_II_rt2': [0.1],
'_PT_rt2': [0.1],
'_II_rt4': [0.25],
'_PT_rt4': [0.25],
'_II_rt5': [0.25],
'_PT_rt5': [0.25],
'_II_rt6': [0.25],
'_PT_rt6': [0.25],
'_CG_as_II': [1],
}
}

$ -23.4 B

reform2 = {2016: {
'_II_rt2': [0.1],
'_PT_rt2': [0.1],
'_II_rt4': [0.25],
'_PT_rt4': [0.25],
'_II_rt5': [0.25],
'_PT_rt5': [0.25],
'_II_rt6': [0.25],
'_PT_rt6': [0.25],
'_CG_rt1': [0.1],
'_CG_rt2': [0.25],
'_CG_rt3': [0.396],
'_AMT_CG_rt1': [0.1],
'_AMT_CG_rt2': [0.25],
'_AMT_CG_rt3': [0.396]

}
}

$ -28.1 B 

When AMT is removed entirely from the baseline and reforms, the results are very close:

p_yy = Policy()
reform1 = {2016: {
'_II_rt2': [0.1],
'_PT_rt2': [0.1],
'_II_rt4': [0.25],
'_PT_rt4': [0.25],
'_II_rt5': [0.25],
'_PT_rt5': [0.25],
'_II_rt6': [0.25],
'_PT_rt6': [0.25],
'_CG_as_II': [1],
'_AMT_trt1':[0.0],
'_AMT_trt2':[0.0]
}
}

-67.4

reform2 = {2016: {
'_II_rt2': [0.1],
'_PT_rt2': [0.1],
'_II_rt4': [0.25],
'_PT_rt4': [0.25],
'_II_rt5': [0.25],
'_PT_rt5': [0.25],
'_II_rt6': [0.25],
'_PT_rt6': [0.25],
'_CG_rt1': [0.1],
'_CG_rt2': [0.25],
'_CG_rt3': [0.396],
'_AMT_trt1':[0.0],
'_AMT_trt2':[0.0]
}
}

-68.8 

cc @codykallen @martinholmer

**Comment by martinholmer** [comment]
@MattHJensen,  Do you get expected results using pull request #975?

**Comment by martinholmer** [comment]
@MattHJensen, Given your issue #974, do you have any concerns with pull request #975?  I'm planning on merging #975 into master just after merging #981 into master, hopefully later today.

**Comment by MattHJensen** [comment]
@martinholmer, I'll check this out right now.

**Comment by MattHJensen** [comment]
@martinholmer, when AMT is in the baseline, I am getting -$23.3 for reform 1 and -$28.2 for reform 2 with PR 975.


reform1 = {2016: {
'_II_rt2': [0.1],
'_PT_rt2': [0.1],
'_II_rt4': [0.25],
'_PT_rt4': [0.25],
'_II_rt5': [0.25],
'_PT_rt5': [0.25],
'_II_rt6': [0.25],
'_PT_rt6': [0.25],
'_CG_nodiff': [1],
}
}

reform2 = {2016: {
'_II_rt2': [0.1],
'_PT_rt2': [0.1],
'_II_rt4': [0.25],
'_PT_rt4': [0.25],
'_II_rt5': [0.25],
'_PT_rt5': [0.25],
'_II_rt6': [0.25],
'_PT_rt6': [0.25],
'_CG_rt1': [0.1],
'_CG_rt2': [0.25],
'_CG_rt3': [0.396],
'_AMT_CG_rt1': [0.1],
'_AMT_CG_rt2': [0.25],
'_AMT_CG_rt3': [0.396]

}
}

**Comment by martinholmer** [comment]
@MattHJensen said:
> When AMT is in the baseline, I am getting -$23.3 for reform 1 and -$28.2 for reform 2 with PR 975.
>
>```
reform1 = {2016: {
'_II_rt2': [0.1],
'_PT_rt2': [0.1],
'_II_rt4': [0.25],
'_PT_rt4': [0.25],
'_II_rt5': [0.25],
'_PT_rt5': [0.25],
'_II_rt6': [0.25],
'_PT_rt6': [0.25],
'_CG_nodiff': [1],
}}
reform2 = {2016: {
'_II_rt2': [0.1],
'_PT_rt2': [0.1],
'_II_rt4': [0.25],
'_PT_rt4': [0.25],
'_II_rt5': [0.25],
'_PT_rt5': [0.25],
'_II_rt6': [0.25],
'_PT_rt6': [0.25],
'_CG_rt1': [0.1],
'_CG_rt2': [0.25],
'_CG_rt3': [0.396],
'_AMT_CG_rt1': [0.1],
'_AMT_CG_rt2': [0.25],
'_AMT_CG_rt3': [0.396]
}}
```

Are these results what you would expect?  If not, what results would you expect?

**Comment by MattHJensen** [comment]
@martinholmer said:

> Are these results what you would expect? If not, what results would you expect?

These are the differences that motivated me to open this issue. I would expect the two reforms to be nearly identical. (@codykallen originally suggested this comparison, which I think is pretty clever.)

**Comment by martinholmer** [comment]
The Issue
----------

Issue #974 proposes two tests of the new CG_nodiff policy parameter, which offers an easy way to eliminate the differential tax treatment of LTCG+QDIV income in both the regular tax and the AMT.

The point of these two tests is to see if complex reforms that eliminate the differential tax treatment of LTCG+QDIV income (by manipulating many policy parameters) produce the same results as do simple reforms that use the CG_nodiff policy parameter to achieve the same no-differential tax-treatment goal.

The first test eliminates the AMT and then compares output from reform3.json, which uses the CG_nodiff parameter, and reform4.json, which manually sets the CG rate schedule equal to a simplified II and PT rate schedule.

The second test does not eliminate the AMT and compares output from reform1.json, which uses the CG_nodiff parameter, and reform2.json, which manually does two things: (a) sets the CG rate schedule equal to a simplified II and PT rate schedule (as in the first test), and (b) eliminates differential AMT taxation by setting the AMT_CG rates to 100% to ensure that all AMT taxable income is taxed using the current-law AMT (non-CG) rate schedule.

Notice that the AMT same tax schedule is not equal to the regular same tax schedule, but LTCG+QDIV income and non-LTCG+DIV income are treated the same within the regular tax and they are treated the same within the AMT.

Short Answer
--------------

Both tests pass: the easy way to eliminate differential tax treatment of LTCG+QDIV income using the CG_nodiff parameter produces exactly the same results as the complex way that involves many changes in the tax rates.  The value of the easy way to accomplish this kind of reform is underlined by the fact the the original proposed tests were wrong in several ways.  So, there is a big advantage in having an easy-to-use single parameter to accomplish a complex reform.

Unless you want the full details of the corrected tests and test results, you can stop reading now.

Long Answer
-------------

**The Reforms**

The two AMT-eliminated reform files are reform3.json and reform4.json.
```
$ cat reform3.json
// AMT-eliminated reform3 with CG_nodiff true
{
    //-- eliminate AMT:
    "_AMT_trt1": {"2016": [0.0]},
    "_AMT_trt2": {"2016": [0.0]},
    //-- specify three-tier regular tax rate schedule for non-LTCG+QDIV income:
    //II_rt1 =           0.10      PT_rt1 =           0.10 by default
    "_II_rt2": {"2016": [0.10]}, "_PT_rt2": {"2016": [0.10]},
    //brk2 = [ 37650,  75300,  37650,  50400,  75300,  37650] by default
    //II_rt3 =           0.25      PT_rt1 =           0.25 by default
    "_II_rt4": {"2016": [0.25]}, "_PT_rt4": {"2016": [0.25]},
    "_II_rt5": {"2016": [0.25]}, "_PT_rt5": {"2016": [0.25]},
    "_II_rt6": {"2016": [0.25]}, "_PT_rt6": {"2016": [0.25]},
    //brk6 = [415050, 466950, 233475, 441000, 466950, 233475] by default
    //II_rt7 =           0.396     PT_rt7 =           0.396 by default
    //-- same regular tax rate schedule for LTCG+QDIV as for other income:
    "_CG_nodiff": {"2016": [1]}
}

$ cat reform4.json 
// AMT-eliminated reform4 with LTCG+QDIV tax rates set the same by hand
{
    //-- eliminate AMT:
    "_AMT_trt1": {"2016": [0.0]},
    "_AMT_trt2": {"2016": [0.0]},
    //-- specify three-tier regular tax rate schedule for non-LTCG+QDIV income:
    //II_rt1 =           0.10      PT_rt1 =           0.10 by default
    "_II_rt2": {"2016": [0.10]}, "_PT_rt2": {"2016": [0.10]},
    //brk2 = [ 37650,  75300,  37650,  50400,  75300,  37650] by default
    //II_rt3 =           0.25      PT_rt1 =           0.25 by default
    "_II_rt4": {"2016": [0.25]}, "_PT_rt4": {"2016": [0.25]},
    "_II_rt5": {"2016": [0.25]}, "_PT_rt5": {"2016": [0.25]},
    "_II_rt6": {"2016": [0.25]}, "_PT_rt6": {"2016": [0.25]},
    //brk6 = [415050, 466950, 233475, 441000, 466950, 233475] by default
    //II_rt7 =           0.396     PT_rt7 =           0.396 by default
    //-- same regular tax rate schedule for LTCG+QDIV as for other income:
    "_CG_rt1": {"2016": [0.10]},
    //brk1 = [ 37650,  75300,  37650,  50400,  75300,  37650] by default
    "_CG_rt2": {"2016": [0.25]},
    //brk2 = [415050, 466950, 233475, 441000, 466950, 233475] by default
    "_CG_rt3": {"2016": [0.396]}
}
```

The two AMT-present reform files are reform1.json and reform2.json.
```
$ cat reform1.json 
// AMT-present reform1 with CG_nodiff true
{
    //-- specify three-tier regular tax rate schedule for non-LTCG+QDIV income:
    //II_rt1 =           0.10      PT_rt1 =           0.10 by default
    "_II_rt2": {"2016": [0.10]}, "_PT_rt2": {"2016": [0.10]},
    //brk2 = [ 37650,  75300,  37650,  50400,  75300,  37650] by default
    //II_rt3 =           0.25      PT_rt1 =           0.25 by default
    "_II_rt4": {"2016": [0.25]}, "_PT_rt4": {"2016": [0.25]},
    "_II_rt5": {"2016": [0.25]}, "_PT_rt5": {"2016": [0.25]},
    "_II_rt6": {"2016": [0.25]}, "_PT_rt6": {"2016": [0.25]},
    //brk6 = [415050, 466950, 233475, 441000, 466950, 233475] by default
    //II_rt7 =           0.396     PT_rt7 =           0.396 by default
    //-- leave default two-tier AMT tax rates schedule for non-LTCG+QDIV income
    //   (rt1 = 0.26 and rt2 = 0.28 and
    //    brk1 = [186300, 186300, 186300/2, 186300, 186300, 186300/2])
    //-- same regular,AMT tax rate schedule for LTCG+QDIV as for other income:
    "_CG_nodiff": {"2016": [1]}
}

$ cat reform2.json 
// AMT-present reform2 with LTCG+QDIV tax rates set the same by hand
{
    //-- specify three-tier regular tax rate schedule for non-LTCG+QDIV income:
    //II_rt1 =           0.10      PT_rt1 =           0.10 by default
    "_II_rt2": {"2016": [0.10]}, "_PT_rt2": {"2016": [0.10]},
    //brk2 = [ 37650,  75300,  37650,  50400,  75300,  37650] by default
    //II_rt3 =           0.25      PT_rt1 =           0.25 by default
    "_II_rt4": {"2016": [0.25]}, "_PT_rt4": {"2016": [0.25]},
    "_II_rt5": {"2016": [0.25]}, "_PT_rt5": {"2016": [0.25]},
    "_II_rt6": {"2016": [0.25]}, "_PT_rt6": {"2016": [0.25]},
    //brk6 = [415050, 466950, 233475, 441000, 466950, 233475] by default
    //II_rt7 =           0.396     PT_rt7 =           0.396 by default
    //-- same regular tax rate schedule for LTCG+QDIV as for other income:
    "_CG_rt1": {"2016": [0.10]},
    //brk1 = [ 37650,  75300,  37650,  50400,  75300,  37650] by default
    "_CG_rt2": {"2016": [0.25]},
    //brk2 = [415050, 466950, 233475, 441000, 466950, 233475] by default
    "_CG_rt3": {"2016": [0.396]},
    //-- leave default two-tier AMT tax rates schedule for non-LTCG+QDIV income
    //   (rt1 = 0.26 and rt2 = 0.28 and
    //    brk1 = [186300, 186300, 186300/2, 186300, 186300, 186300/2])
    //-- same AMT tax rate schedule for LTCG+QDIV as for other AMT income:
    "_AMT_CG_rt1": {"2016": [1.00]}, // high rate to stop differential taxation
    "_AMT_CG_thd1": {"2016": [[9.9E99,9.9E99,9.9E99,9.9E99,9.9E99,9.9E99]]}
}
```

**First Test**

Conduct the first (AMT-eliminated) test using the standard puf.csv file:
```
$ cp ../tax-calculator-data/puf.csv .

$ python inctax.py puf.csv 2016 --weights --blowup --reform reform3.json
You loaded data for 2009.
Your data have been extrapolated to 2016.

$ python inctax.py puf.csv 2016 --weights --blowup --reform reform4.json
You loaded data for 2009.
Your data have been extrapolated to 2016.

$ ls puf-16*
puf-16.out-inctax-reform3	puf-16.out-inctax-reform4

$ awk '{rev+=$4*$29}END{print rev}' puf-16.out-inctax-reform3
1.36418e+12

$ awk '{rev+=$4*$29}END{print rev}' puf-16.out-inctax-reform4
1.36285e+12
```
Above difference in income tax revenue is $1.33 billion, which is close to the result in the first entry of issue #974, which is (-67.4 - -68.8) = 1.4, with aggregate revenue less under reform4 than under reform3.

The question is why are reform3 and reform4 results not exactly equal.

The answer to that question is that the presence of two input variables in the puf.csv file cause the execution of GainsTax code that contains hardwired tax rates (that is, tax rates that cannot be changed by a policy reform).  Here are the lines in the GainsTax function that contain the hardwired tax rates:
```
        dwks38 = 0.25 * dwks37  # <----- 0.25 is hardwired in the code
        # break in worksheet lines
        dwks39 = dwks19 + dwks20 + dwks28 + dwks31 + dwks37
        dwks40 = dwks1 - dwks39
        dwks41 = 0.28 * dwks40  # <----- 0.28 is hardwired in the code
```
The two input variables are e24515 and e24518 (for descriptions of these two variables see [this webpage](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/validation/CSV_INPUT_VARS.md)).  So, for these tests we need to create pufx.csv that includes only filing units that have zero values for both e24515 and e24518. We do that as follows:
```
$ cp ../tax-calculator-data/puf.csv .

$ awk -F, 'NR==1{for(i=1;i<=NF;i++)print i,$i}' puf.csv | grep e24515
59 e24515

$ awk -F, 'NR==1{for(i=1;i<=NF;i++)print i,$i}' puf.csv | grep e24518
60 e24518

$ awk -F, 'NR==1||($59==0&&$60==0)' puf.csv > pufx.csv

$ awk -F, 'NR>1{n++;w+=$71}END{print n,w}' puf.csv
219814 1.59049e+10

$ awk -F, 'NR>1{n++;w+=$71}END{print n,w}' pufx.csv
217242 1.58524e+10
```
So, the pufx.csv file eliminates a small fraction of the filing units in the full puf.csv file: 0.33% weighted and 1.17% unweighted.

Because the tests can never pass with these filing units included in the input sample, we conduct both tests using the pufx.csv input file.

On the master branch, comparing reform3 and reform4 output using pufx.csv input shows no differences:
```
$ python inctax.py pufx.csv 2016 --blowup --reform reform3.json
You loaded data for 2009.
Your data have been extrapolated to 2016.

$ python inctax.py pufx.csv 2016 --blowup --reform reform4.json
You loaded data for 2009.
Your data have been extrapolated to 2016.

$ tclsh taxcalc/validation/taxdiffs.tcl pufx-16.out-inctax-reform3 pufx-16.out-inctax-reform4 ; date
                               <----- NO DIFFERENCES
Fri Oct 21 11:21:59 EDT 2016
```

**Second Test**

On the master branch, comparing reform1 and reform2 output using pufx.csv input shows no differences:
```
$ python inctax.py pufx.csv 2016 --blowup --reform reform1.json
You loaded data for 2009.
Your data have been extrapolated to 2016.

$ python inctax.py pufx.csv 2016 --blowup --reform reform2.json
You loaded data for 2009.
Your data have been extrapolated to 2016.

$ tclsh taxcalc/validation/taxdiffs.tcl pufx-16.out-inctax-reform1 pufx-16.out-inctax-reform2 ; date
                               <----- NO DIFFERENCES
Fri Oct 21 11:24:03 EDT 2016
```

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen

**Comment by MattHJensen** [comment]
**@martinholmer, is this an accurate summary of your findings?** 

There are two kinds of CG income that are not taxed at the regular CG and QDIV rate schedule. Because the rates at which that irregular income is taxed are hardwired into functions.py, it will continue to be taxed at current law rates even if we modify the regular CG and QDIV rate schedule. Therefore, when we change the the regular CG and QDIV rate schedule to match the II and PT rate schedule, this income is left behind and we get a slightly different answer than when we use the `CG_nodiff` parameter tax all CG and QDIV income (including the irregular CG income) as II income. 

**If so, does the musing below also make sense? I am not necessarily suggesting that we do this, but the thought experiment clarifies my understanding of the issue.** 

If we really want the two reforms to match, we would need to parameterize the rates applied to each of the irregular types of CG income. To keep this exact test, we would actually need to parameterize three rates for each of these two types of income so that we could match the progressive rate schedules modeled in these test reforms  (all three rates for each set would be the same under current law). Alternatively, we could simplify the tests to adopt a flat rate structure for both CG&QDIV and II&PT, and then we would only need to parameterize one rate for each of these two types of income in order to get the test to pass on the full dataset.  

cc @codykallen

**Comment by martinholmer** [comment]
@MattHJensen said:
> @martinholmer, is this an accurate summary of your findings?
>
> There are two kinds of CG income that are not taxed at the regular CG and QDIV rate schedule. Because the rates at which that irregular income is taxed are hardwired into functions.py, it will continue to be taxed at current law rates even if we modify the regular CG and QDIV rate schedule. Therefore, when we change the the regular CG and QDIV rate schedule to match the II and PT rate schedule, this income is left behind and we get a slightly different answer than when we use the CG_nodiff parameter tax all CG and QDIV income (including the irregular CG income) as II income.

Yes, the above is an clear and accurate summary of the situation with respect to issue #974.

And then @MattHJensen continued:
> If so, does the musing below also make sense? I am not necessarily suggesting that we do this, but the thought experiment clarifies my understanding of the issue.
>
> If we really want the two reforms to match, we would need to parameterize the rates applied to each of the irregular types of CG income. To keep this exact test, we would actually need to parameterize three rates for each of these two types of income so that we could match the progressive rate schedules modeled in these test reforms (all three rates for each set would be the same under current law). Alternatively, we could simplify the tests to adopt a flat rate structure for both CG&QDIV and II&PT, and then we would only need to parameterize one rate for each of these two types of income in order to get the test to pass on the full dataset.

Your second, alternative or flat-rate-schedule, approach definitely seems like it would work.  I'm not so sure about the first approach, but maybe I haven't thought hard enough about this issue.  I haven't figured out how to determine which of the three new rates to apply to the two types of "irregular" gains income for any particular filing unit in order to mimic this "irregular" income being taxed at the same tax rate as II&PT income.

@feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen

**Comment by martinholmer** [comment]
@MattHJensen,  Has Tax-Calculator issue #974 been resolved to your satisfaction?  If not, can you raise the remaining issues; of if so, can you close #974?

@feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen

**Comment by MattHJensen** [comment]
@martinholmer, this is resolved. Thanks a lot! Closing.
